### PR TITLE
fix: TopK operator should return correct results on dictionary column with nulls

### LINKED ISSUE #1030: `TopK` operator (i.e. `CometTakeOrderedAndProjectExec`) may return incorrect result
### Describe the bug

We found an interesting bug recently. For some cases, `Dataset.show` and `Dataset.collectAsList` return different results.
We investigated the bug and found that it is due to the implementation of`take_bytes`.

In the cases, Comet reads a dictionary array of string. It unpacks dictionary array to string array. In a query where `TopK` operator is used, the operator will store input arrays into internal store and emit after all inputs are consumed. In Comet, the output arrays from scan reuse same buffers across batches. For operators that cache input arrays, Comet will do deep copy on these arrays.

However, when unpacking dictionary array to string array by calling `take_bytes `, if the indices array has no null, `take_bytes` kernel simply takes a full slice of the null buffer of indices (i.e., reusing it) as the null buffer of output array. So in the next batch, once the null buffer is updated (as Comet reuses underlying buffer), the stored array in `TopK` operator is also changed. It makes the query result indeterministic.

Consider the semantics of `take` kernel, its output array should not reuse input array. The current behavior looks incorrect.

We are going to fix it at the arrow-rs: https://github.com/apache/arrow-rs/issues/6617

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #1030.

### CODE REVIEW

**Comment by viirya** [comment]
cc @huaxingao With this patch, the failed Iceberg test can pass now.

File: native/core/src/execution/operators/copy.rs [hunk 1]
```diff
@@ -262,7 +262,13 @@ fn copy_or_unpack_array(array: &Arc<dyn Array>, mode: &CopyMode) -> Result<Array
     match array.data_type() {
         DataType::Dictionary(_, value_type) => {
             let options = CastOptions::default();
-            cast_with_options(array, value_type.as_ref(), &options)
+            // We need to copy the array after `cast` because arrow-rs `take` kernel which is used
+            // to unpack dictionary array might reuse the input array's null buffer.
+            Ok(copy_array(&cast_with_options(
```
Comment (viirya) [inline native/core/src/execution/operators/copy.rs:267]: If https://github.com/apache/arrow-rs/pull/6616 can merge, we don't need this extra copy.

This will do extra copy on data buffer too, although the issue happens on null buffer only.

Actually we can have custom unpack dictionary and take implementation to only copy null buffer, but I put this simply with the expectation that the fix at arrow-rs could be merged eventually.

If it is blocked on merging eventually, I will open another PR to have custom unpack dictionary and take implementation to reduce the copy cost here.

**Review by huaxingao — APPROVED** [review]
LGTM. Thanks for the fix @viirya

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @viirya

**Comment by andygrove** [comment]
I ran TPC-H benchmarks comparing this PR to main and did not see any regression

**Comment by viirya** [comment]
Thanks @huaxingao @andygrove
