### PR TITLE
fix: pass scale to DF round in spark_round

### LINKED ISSUE #1340: Scale argument is not passed to DF `round` in `spark_round`
### Describe the bug

Scale argument is not passed to DF `round` in `spark_round`

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cht42**
## Which issue does this PR close?

Closes #1340.

### CODE REVIEW

File: native/spark-expr/src/math_funcs/round.rs [hunk 1]
```diff
@@ -85,9 +85,10 @@ pub fn spark_round(
                 let (precision, scale) = get_precision_scale(data_type);
                 make_decimal_array(array, precision, scale, &f)
             }
-            DataType::Float32 | DataType::Float64 => {
-                Ok(ColumnarValue::Array(round(&[Arc::clone(array)])?))
-            }
+            DataType::Float32 | DataType::Float64 => Ok(ColumnarValue::Array(round(&[
```
Comment (kazuyukitanimura) [inline native/spark-expr/src/math_funcs/round.rs:88]: FYI round for float is disabled https://github.com/apache/datafusion-comet/blob/main/spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala#L1739

BTW we should be able to use `point` instead of `args[1]`?

Comment (cht42) [reply native/spark-expr/src/math_funcs/round.rs:88]: point is being set to the scalar value on this line and we want to pass the columnar value to DF
```
    let ColumnarValue::Scalar(ScalarValue::Int64(Some(point))) = point else 
```

Comment (cht42) [reply native/spark-expr/src/math_funcs/round.rs:88]: in my use case, im not using comet's query planning so it should be fine

Comment (andygrove) [reply native/spark-expr/src/math_funcs/round.rs:88]: Since this isn't being tested end-to-end, could you add a Rust unit test so that we protect against regressions in the future?

Comment (kazuyukitanimura) [reply native/spark-expr/src/math_funcs/round.rs:88]: Still for the reason mentioned in the link, it may not work some cases.

Comment (cht42) [reply native/spark-expr/src/math_funcs/round.rs:88]: added tests for floats

**Review by kazuyukitanimura — APPROVED** [review]
I am ok to accept this PR as round is disabled for floating points. Current round behavior is not Spark compatible and we will change the logic to match with the Spark behavior in the future though.

File: native/spark-expr/src/math_funcs/round.rs [hunk 2]
```diff
@@ -135,3 +136,50 @@ fn decimal_round_f(scale: &i8, point: &i64) -> Box<dyn Fn(i128) -> i128> {
...
+
+    use arrow::array::{Float32Array, Float64Array};
+    use arrow_schema::DataType;
+    use datafusion_common::cast::{as_float32_array, as_float64_array};
+    use datafusion_common::{Result, ScalarValue};
+    use datafusion_expr::ColumnarValue;
+
+    #[test]
+    fn test_round_f32() -> Result<()> {
+        let args = vec![
```
[the remark this answers is not in the document]
Comment (cht42) [reply native/spark-expr/src/math_funcs/round.rs:154]: can we get it merged ? or do you want more tests ? also how would we use spark results in test ?

[the remark this answers is not in the document]
Comment (kazuyukitanimura) [reply native/spark-expr/src/math_funcs/round.rs:154]: Thanks @cht42 merged.
For the Spark results, you would need to get them manually for testing in Rust.
We can enable tests like https://github.com/apache/datafusion-comet/blob/main/spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala#L1239 once we fully support round for floating points
