### PR TITLE
fix: cast map types correctly in schema adapter

### LINKED ISSUE #1754: [native_datafusion] Spark SQL failure "select nested field from a complex map key using map_keys"
### Describe the bug

`SELECT map_keys(map1) FROM tbl` works.
`SELECT map_keys(map1).id2 FROM tbl` does not work.

Repro:

```scala
  ignore("read map[struct, struct] from parquet") {
    assume(usingDataSourceExec(conf))

    withTempPath { dir =>
      // create input file with Comet disabled
      withSQLConf(CometConf.COMET_ENABLED.key -> "false") {
        val df = spark
          .range(5)
          .withColumn("id2", col("id"))
          .withColumn("id3", col("id"))
          // Spark does not allow null as a key but does allow null as a
          // value, and the entire map be null
          .select(
            when(col("id") > 1, map(struct(col("id"), col("id2"), col("id3")), when(col("id") > 2,
              struct(col("id"), col("id2"), col("id3"))))).alias("map1"))
        df.write.parquet(dir.toString())
      }

      Seq("", "parquet").foreach { v1List =>
        withSQLConf(SQLConf.USE_V1_SOURCE_LIST.key -> v1List) {
          val df = spark.read.parquet(dir.toString())
          df.createOrReplaceTempView("tbl")
          if (v1List.isEmpty) {
            checkSparkAnswer(df.select("map1"))
          } else {
            checkSparkAnswerAndOperator(df.select("map1"))
          }
          checkSparkAnswer(spark.sql("SELECT map_keys(map1).id2 FROM tbl"))
        }
      }
    }
  }
```

Error:

```
org.apache.comet.CometNativeException: Invalid argument error: column types must match schema types, 
```

## Expected

```
Map(Field { name: "entries", data_type: Struct([
  Field { name: "key", data_type: Struct([
    Field { name: "id2", data_type: Int64 }
  ]) }, 
  Field { name: "value", data_type: Struct([
    Field { name: "id", data_type: Int64 }, 
    Field { name: "id2", data_type: Int64 }, 
    Field { name: "id3", data_type: Int64 }
  ]) }
]) }, false) 
```

## Found

```
Map(Field { name: "key_value", data_type: Struct([
  Field { name: "key", data_type: Struct([
    Field { name: "id", data_type: Int64 }, 
    Field { name: "id2", data_type: Int64 }, 
    Field { name: "id3", data_type: Int64 }]) }, 
  Field { name: "value", data_type: Struct([
    Field { name: "id", data_type: Int64 }, 
    Field { name: "id2", data_type: Int64 }, 
    Field { name: "id3", data_type: Int64 }
  ]) }
]) }, false) at column index 0
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by parthchandra**
## Which issue does this PR close?

Closes #1754 

## Rationale for this change

In schema_adapter Map types are cast using arrow's cast which assumes that all nested fields within the map are also castable. However, the check to verify if the fields can be cast does not take into account nested struct fields with a different number of fields. 

## What changes are included in this PR?

The PR changes the cast method to a copy of the original that calls the schema adapter's struct cast method which can handle such structs

## How are these changes tested?

Unit test was already added. This PR enables the test

### CODE REVIEW

**Comment by parthchandra** [comment]
Marking as draft. Spark diffs may need to be updated as well.

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @parthchandra!

File: native/core/src/parquet/parquet_support.rs [hunk 1]
```diff
@@ -241,6 +246,71 @@ fn cast_struct_to_struct(
     }
 }
 
+/// Cast a map type to another map type. The same as arrow-cast except we recursively call our own
+/// cast_array
+pub(crate) fn cast_map_values(
```
Comment (comphead) [inline native/core/src/parquet/parquet_support.rs:251]: do we really need pub(crate)?

**Review by comphead — APPROVED** [review]
Thanks @parthchandra 

however I feel we need to add some more later. the test passed because 

```
          checkSparkAnswer(spark.sql("SELECT map_keys(map1).id2 FROM tbl"))
```

and will prob fail for 

```
          checkSparkAnswerAndOperator(spark.sql("SELECT map_keys(map1).id2 FROM tbl"))
```

**Comment by comphead** [comment]
in followup PR I'll add a rust test case for map

**Comment by parthchandra** [comment]
> Thanks @parthchandra
> 
> however I feel we need to add some more later. the test passed because
> 
> ```
>           checkSparkAnswer(spark.sql("SELECT map_keys(map1).id2 FROM tbl"))
> ```
> 
> and will prob fail for
> 
> ```
>           checkSparkAnswerAndOperator(spark.sql("SELECT map_keys(map1).id2 FROM tbl"))
> ```

Good point @comphead .

The test cannot use `checkSparkAnswerAndOperator` atm but should eventually.
The plan is not fully native for two reasons - 
native_datafusion and native_iceberg_compat do not support DSV2 so the Scan falls back to Spark 
with DSV2 the plan is
```
plan: *(1) Project [map_keys(map1#12).id2 AS map_keys(map1).id2#54]
+- *(1) ColumnarToRow
   +- BatchScan parquet file:/private/var/folders/bz/gg_fqnmj4c17j2c7mdn8ps1m0000gn/T/spark-e0fd616e-7fdc-4d0a-be8a-e6453797e243[map1#12] ParquetScan DataFilters: [], Format: parquet, Location: InMemoryFileIndex(1 paths)[file:/private/var/folders/bz/gg_fqnmj4c17j2c7mdn8ps1m0000gn/T/spark-e0..., PartitionFilters: [], PushedAggregation: [], PushedFilters: [], PushedGroupBy: [], ReadSchema: struct<map1:map<struct<id2:bigint>,struct<id:bigint,id2:bigint,id3:bigint>>> RuntimeFilters: []
```

with DSV1 sources, the scan is Native but the Project is not. 
```
plan: *(1) Project [map_keys(map1#82).id2 AS map_keys(map1).id2#118]
+- *(1) CometColumnarToRow
   +- CometNativeScan parquet [map1#82] Batched: true, DataFilters: [], Format: CometParquet, Location: InMemoryFileIndex(1 paths)[file:/private/var/folders/bz/gg_fqnmj4c17j2c7mdn8ps1m0000gn/T/spark-d0..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<map1:map<struct<id2:bigint>,struct<id:bigint,id2:bigint,id3:bigint>>>

```

**Comment by comphead** [comment]
Filed https://github.com/apache/datafusion-comet/issues/1781
