### PR TITLE
fix: get_struct field is incorrect when struct in array

### LINKED ISSUE #1681: [Experimental scans] schema adapter does not apply required schema for structs within lists
### Describe the bug

The following test currently fails:

```scala
  test("nested data - array of struct") {
    val data = (1 to 10).map(i => Tuple1(Seq(i -> s"val_$i")))
    withParquetTable(data, "t") {
      withSQLConf(CometConf.COMET_NATIVE_SCAN_IMPL.key -> CometConf.SCAN_NATIVE_ICEBERG_COMPAT) {
        checkSparkAnswerAndOperator(sql("SELECT _1[0]._2 FROM t"))
      }
    }
  }

```

The parquet file contains an array of struct, where the struct has fields `_1` and `_2`.

The required schema in the scan filters out the `_1` from the struct:

```
required_schema = Field { name: "_1", data_type: List(Field { name: "item", data_type: Struct([Field { name: "_2", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }
```

The projection contains `GetStructField` with ordinal `0` to represent field `_2` in the struct.

Comet does not apply the required schema and therefore selects both `_1` and `_2` from the struct, and the `GetStructField` with `ordinal=0` returns `_1` instead of `_2`.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by comphead**
## Which issue does this PR close?

Closes #1681 .

### CODE REVIEW

File: native/core/src/parquet/parquet_support.rs [hunk 1]
```diff
@@ -171,7 +178,36 @@ fn cast_array(
...
+}
+
+fn cast_list_to_list(
+    array: &ListArray,
+    from_type: &DataType,
+    to_type: &DataType,
+    parquet_options: &SparkParquetOptions,
+) -> DataFusionResult<ArrayRef> {
+    match (from_type, to_type) {
+        (DataType::List(_), DataType::List(to_inner_type)) => {
```
Comment (andygrove) [inline native/core/src/parquet/parquet_support.rs:196]: I think you could just pass `to_inner_type` directly into this method to avoid matching on `List` again here?

Comment (andygrove) [reply native/core/src/parquet/parquet_support.rs:196]: Also `from_type` doesn't need to be passed in?

File: native/core/src/parquet/parquet_support.rs [hunk 2]
```diff
@@ -171,7 +178,36 @@ fn cast_array(
                     .with_timezone(Arc::clone(tz)),
             ))
         }
-        _ => Ok(cast_with_options(&array, to_type, &PARQUET_OPTIONS)?),
+        // If Arrow cast supports the cast, delegate the cast to Arrow
+        _ if can_cast_types(from_type, to_type) => {
```
Comment (andygrove) [inline native/core/src/parquet/parquet_support.rs:182]: :+1:

File: native/core/src/parquet/parquet_support.rs [hunk 3]
```diff
@@ -171,7 +178,36 @@ fn cast_array(
...
+            Ok(cast_with_options(&array, to_type, &PARQUET_OPTIONS)?)
+        }
+        _ => Ok(array),
```
Comment (andygrove) [inline native/core/src/parquet/parquet_support.rs:185]: Should this be an error rather than ignoring the cast request?

**Review by andygrove — APPROVED** [review]
LGTM with some nits / questions. This is a huge step forward :rocket:.

File: native/core/src/parquet/parquet_support.rs (hunk 3 above)
Comment (comphead) [reply native/core/src/parquet/parquet_support.rs:185]: simplified

File: native/core/src/parquet/parquet_support.rs (hunk 1 above)
Comment (comphead) [reply native/core/src/parquet/parquet_support.rs:196]: simplified
