### PR TITLE
test: Add tests for Scalar and Inverval values for UnaryMinus

### LINKED ISSUE #508: Add tests for Scalar and Inverval values for UnaryMinus
### Describe the bug

Related to #471, we should add tests for Scalar and Inverval values for UnaryMinus

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vaibhawvipul**
## Which issue does this PR close?

Closes #508 .

## Rationale for this change

Improves test coverage for various unary minus.

## What changes are included in this PR?

Tests for scalar values and intervals.

## How are these changes tested?

All tests pass.

### CODE REVIEW

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 1]
```diff
@@ -1583,66 +1585,61 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+          val dayTimeDf = Seq(106751991L, 106751991L, 2L)
+            .map(Duration.ofDays)
+            .toDF("v")
+          Seq(longDf, yearMonthDf, dayTimeDf).foreach { df =>
+            withSQLConf(
+              "spark.sql.optimizer.excludedRules" -> "org.apache.spark.sql.catalyst.optimizer.ConstantFolding",
+              SQLConf.ANSI_ENABLED.key -> "true",
+              CometConf.COMET_ANSI_MODE_ENABLED.key -> "true",
+              CometConf.COMET_ENABLED.key -> "true",
+              CometConf.COMET_EXEC_ENABLED.key -> "true") {
```
Comment (kazuyukitanimura) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1638]: This is still inside the earlier `withSQLConf` that has the same confs, so I guess this can be removed?

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 2]
```diff
@@ -1583,66 +1585,61 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+      // scalar tests
+      withParquetTable((0 until 5).map(i => (i % 5, i % 3)), "tbl") {
+        withSQLConf(
+          "spark.sql.optimizer.excludedRules" -> "org.apache.spark.sql.catalyst.optimizer.ConstantFolding",
+          SQLConf.ANSI_ENABLED.key -> "true",
+          CometConf.COMET_ANSI_MODE_ENABLED.key -> "true",
+          CometConf.COMET_ENABLED.key -> "true",
+          CometConf.COMET_EXEC_ENABLED.key -> "true") {
+          for (n <- Seq("2147483647", "-2147483648")) {
+            checkOverflow(s"select -(cast(${n} as int)) FROM tbl", "integer")
```
Comment (kazuyukitanimura) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1610]: I wonder if we can call `checkSparkAnswerAndOperator` to make sure whether native code is actually executed.
Perhaps something like when `checkSparkMaybeThrows` returns `(None, None)` currently it runs `assert(true)` but perhaps we can run `checkSparkAnswerAndOperator` instead...

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 3]
```diff
@@ -1583,66 +1585,61 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
-          checkOverflow("select a, -a from t_float", "float")
+      // scalar tests
+      withParquetTable((0 until 5).map(i => (i % 5, i % 3)), "tbl") {
+        withSQLConf(
+          "spark.sql.optimizer.excludedRules" -> "org.apache.spark.sql.catalyst.optimizer.ConstantFolding",
+          SQLConf.ANSI_ENABLED.key -> "true",
+          CometConf.COMET_ANSI_MODE_ENABLED.key -> "true",
+          CometConf.COMET_ENABLED.key -> "true",
+          CometConf.COMET_EXEC_ENABLED.key -> "true") {
+          for (n <- Seq("2147483647", "-2147483648")) {
```
Comment (kazuyukitanimura) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1609]: nit: probably `"2147483647"` => Int.MaxValue

**Review by kazuyukitanimura — COMMENTED** [review]
Mostly looks good.
Somehow Github failed launching CI...

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 4]
```diff
@@ -1583,66 +1585,51 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+            checkOverflow(s"select -(cast(${n} as float)) FROM tbl", "float")
+          }
+          // interval test without cast
+          val longDf = Seq(Long.MaxValue, Long.MaxValue, 2)
+          val yearMonthDf = Seq(Int.MaxValue, Int.MaxValue, 2)
+            .map(Period.ofMonths)
+          val dayTimeDf = Seq(106751991L, 106751991L, 2L)
+            .map(Duration.ofDays)
+          Seq(longDf, yearMonthDf, dayTimeDf).foreach { df =>
+            checkOverflow(s"select -(_1) FROM tbl", "")
```
Comment (kazuyukitanimura) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1631]: nit: I think these become array values instead of scalar. So these belong to the `Array values test` section

**Review by kazuyukitanimura — APPROVED** [review]

**Comment by kazuyukitanimura** [comment]
pending ci

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala (hunk 4 above)
Comment (vaibhawvipul) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala]: moved to array section.

**Comment by andygrove** [comment]
Thanks @vaibhawvipul and @kazuyukitanimura

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 5]
```diff
@@ -1635,7 +1637,7 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
         case (Some(sparkException), Some(cometException)) =>
           assert(sparkException.getMessage.contains(dtype + " overflow"))
           assert(cometException.getMessage.contains(dtype + " overflow"))
-        case (None, None) => assert(true) // got same outputs
+        case (None, None) => checkSparkAnswerAndOperator(sql(query))
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1640]: nit: we call `checkSparkMaybeThrows,`, and if that doesn't fail, then we call `checkSparkAnswerAndOperator`. I think this could all be streamlined, but this is beyond the scope of this PR

**Review by andygrove — APPROVED** [review]
