### PR TITLE
fix: check overflow for decimal integral division

### LINKED ISSUE #1506: Incorrect results for `div` expression
### Describe the bug

I saw this test failure on a PR that was unrelated to `div` and seems like the test may be non-deterministic i.e. not using a fixed seed but I am not 100% sure.

```
2025-03-11T22:58:01.9967969Z - Decimal random number tests *** FAILED *** (30 seconds, 904 milliseconds)
2025-03-11T22:58:01.9969097Z   Results do not match for query:
2025-03-11T22:58:01.9977137Z   Timezone: sun.util.calendar.ZoneInfo[id="America/Los_Angeles",offset=-28800000,dstSavings=3600000,useDaylight=true,transitions=185,lastRule=java.util.SimpleTimeZone[id=America/Los_Angeles,offset=-28800000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=3,startMonth=2,startDay=8,startDayOfWeek=1,startTime=7200000,startTimeMode=0,endMode=3,endMonth=10,endDay=1,endDayOfWeek=1,endTime=7200000,endTimeMode=0]]
2025-03-11T22:58:01.9980015Z   Timezone Env: 
2025-03-11T22:58:01.9980331Z   
2025-03-11T22:58:01.9980616Z   == Parsed Logical Plan ==
2025-03-11T22:58:01.9981131Z   Project [a#135012, b#135013, (a#135012 div b#135013) AS (a div b)#135734L]
2025-03-11T22:58:01.9981700Z   +- SubqueryAlias spark_catalog.default.test
2025-03-11T22:58:01.9982301Z      +- Relation spark_catalog.default.test[a#135012,b#135013] parquet
2025-03-11T22:58:01.9982819Z   
2025-03-11T22:58:01.9983112Z   == Analyzed Logical Plan ==
2025-03-11T22:58:01.9983541Z   a: decimal(38,0), b: decimal(2,2), (a div b): bigint
2025-03-11T22:58:01.9984839Z   Project [a#135012, b#135013, (a#135012 div b#135013) AS (a div b)#135734L]
2025-03-11T22:58:01.9985492Z   +- SubqueryAlias spark_catalog.default.test
2025-03-11T22:58:01.9986089Z      +- Relation spark_catalog.default.test[a#135012,b#135013] parquet
2025-03-11T22:58:01.9986625Z   
2025-03-11T22:58:01.9986920Z   == Optimized Logical Plan ==
2025-03-11T22:58:01.9987447Z   Project [a#135012, b#135013, (a#135012 div b#135013) AS (a div b)#135734L]
2025-03-11T22:58:01.9988130Z   +- Relation spark_catalog.default.test[a#135012,b#135013] parquet
2025-03-11T22:58:01.9988643Z   
2025-03-11T22:58:01.9988907Z   == Physical Plan ==
2025-03-11T22:58:01.9989257Z   *(1) CometColumnarToRow
2025-03-11T22:58:01.9990132Z   +- CometProject [a#135012, b#135013, (a div b)#135734L], [a#135012, b#135013, (a#135012 div b#135013) AS (a div b)#135734L]
2025-03-11T22:58:01.9992392Z      +- CometScan parquet spark_catalog.default.test[a#135012,b#135013] Batched: true, DataFilters: [], Format: CometParquet, Location: InMemoryFileIndex(1 paths)[file:/__w/datafusion-comet/datafusion-comet/spark/spark-warehouse/test], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<a:decimal(38,0),b:decimal(2,2)>
2025-03-11T22:58:01.9993933Z   
2025-03-11T22:58:01.9994494Z   == Results ==
2025-03-11T22:58:01.9994774Z   
2025-03-11T22:58:01.9995035Z   == Results ==
2025-03-11T22:58:01.9995345Z   !== Correct Answer - 10 ==                                            == Spark Answer - 10 ==
2025-03-11T22:58:01.9995879Z    struct<a:decimal(38,0),b:decimal(2,2),(a div b):bigint>              struct<a:decimal(38,0),b:decimal(2,2),(a div b):bigint>
2025-03-11T22:58:01.9996562Z    [-28357995361121806525706862761593208487,0.87,7291161238655874692]   [-28357995361121806525706862761593208487,0.87,7291161238655874692]
2025-03-11T22:58:01.9997287Z   ![-62672277069777110394022909049981876593,-0.40,null]                 [-62672277069777110394022909049981876593,-0.40,8770993997598117786]
2025-03-11T22:58:01.9997921Z   ![-68299431870253176399167726913574455270,-0.22,null]                 [-68299431870253176399167726913574455270,-0.22,-1]
2025-03-11T22:58:01.9998580Z    [-76493436389033420298984674631443469720,0.77,2047302896757186509]   [-76493436389033420298984674631443469720,0.77,2047302896757186509]
2025-03-11T22:58:01.9999251Z   ![-77532633078952291817347741106477071062,0.36,null]                  [-77532633078952291817347741106477071062,0.36,-1]
2025-03-11T22:58:02.0000258Z   ![-79918484954351746825313746420585672848,0.44,null]                  [-79918484954351746825313746420585672848,0.44,-1]
2025-03-11T22:58:02.0001474Z    [19561074799139924791894966896645366893,0.84,-1511920647582873129]   [19561074799139924791894966896645366893,0.84,-1511920647582873129]
2025-03-11T22:58:02.0002855Z    [22053918435415460642219818022907905627,0.37,6750894698372871109]    [22053918435415460642219818022907905627,0.37,6750894698372871109]
2025-03-11T22:58:02.0004080Z   ![54400354300704342908577384819323710194,0.18,null]                   [54400354300704342908577384819323710194,0.18,-1]
2025-03-11T22:58:02.0005374Z   ![78585488402645143056239590008272527352,-0.51,null]                  [78585488402645143056239590008272527352,-0.51,-4252079254050434654] (QueryTest.scala:243)
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wForget**
## Which issue does this PR close?

Closes #1506.

## Rationale for this change

keep same logic as spark

## What changes are included in this PR?

check overflow for decimal integral division

## How are these changes tested?

added unit test

### CODE REVIEW

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 1]
```diff
@@ -655,8 +655,23 @@ object QueryPlanSerde extends Logging with ShimQueryPlanSerde with CometExprShim
...
+                .newBuilder()
+                .setCheckOverflow(builder)
+                .build())
+          } else {
+            divideExpr
+          }
+
           // cast result to long
-          castToProto(expr, None, LongType, divideExpr.get, CometEvalMode.LEGACY)
+          castToProto(expr, None, LongType, childExpr.get, CometEvalMode.LEGACY)
```
Comment (kazuyukitanimura) [inline spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:674]: Could be just naming issue but why it is `child`?

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 2]
```diff
@@ -655,8 +655,23 @@ object QueryPlanSerde extends Logging with ShimQueryPlanSerde with CometExprShim
           (builder, mathExpr) => builder.setIntegralDivide(mathExpr))
 
         if (divideExpr.isDefined) {
+          val childExpr = if (dataType.isInstanceOf[DecimalType]) {
+            // check overflow for decimal type
+            val builder = ExprOuterClass.CheckOverflow.newBuilder()
+            builder.setChild(divideExpr.get)
+            builder.setFailOnError(false)
```
Comment (kazuyukitanimura) [inline spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:662]: Is it always `false` even for ANSI mode?

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 3]
```diff
@@ -2734,4 +2734,18 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
     }
   }
 
+  test("test integral divide overflow for decimal") {
```
Comment (kazuyukitanimura) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:2737]: would you mind testing both ANSI and non-ANSI?

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala (hunk 1 above)
Comment (wForget) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:674]: > Could be just naming issue but why it is `child`?

It is for castToLong that is `child`, and it could be divide expr or checkoverflow expor so I can't think of a better name, do you have any suggestions?

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala (hunk 2 above)
Comment (wForget) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala]: > Is it always `false` even for ANSI mode?

Sorry, I mistakenly thought that comet does not support ansi mode

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 4]
```diff
@@ -2734,4 +2734,28 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+    // decimal support requires Spark 3.4 or later
+    assume(isSpark34Plus)
+    if (isSpark40Plus) {
+      Seq(true, false)
+    } else
+      {
+        // ansi mode only supported in Spark 4.0+
+        Seq(false)
+      }.foreach { ansiMode =>
+        withSQLConf(SQLConf.ANSI_ENABLED.key -> ansiMode.toString) {
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:2747]: ANSI support in Comet is currently experimental and has to be enabled by also setting the internal config `spark.comet.ansi.enabled=true`.

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 5]
```diff
@@ -2734,4 +2734,28 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
   }
 
+  test("test integral divide overflow for decimal") {
+    // decimal support requires Spark 3.4 or later
+    assume(isSpark34Plus)
+    if (isSpark40Plus) {
+      Seq(true, false)
+    } else
+      {
+        // ansi mode only supported in Spark 4.0+
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:2744]: ANSI mode is supported by all 3.x versions as well, but I think it would be ok for Comet to only support ANSI mode with Spark 4 since this is the version that enables it by default

**Review by andygrove — APPROVED** [review]
Thanks @wForget. I am about to create the 0.7.0 release so am going to merge this fix.

I am a little surprised that the ANSI test for Spark 4 is passing, so I filed a follow on issue to investigate this - https://github.com/apache/datafusion-comet/issues/1526.

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala (hunk 4 above)
Comment (wForget) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:2747]: In spark 4, `spark.comet.ansi.enabled` defaults to `true`:

https://github.com/apache/datafusion-comet/blob/382ac938f2d10666eefc08ec5c1c82025ddf3726/common/src/main/scala/org/apache/comet/CometConf.scala#L578-L585

https://github.com/apache/datafusion-comet/blob/382ac938f2d10666eefc08ec5c1c82025ddf3726/common/src/main/spark-4.0/org/apache/comet/shims/ShimCometConf.scala#L24
