### PR TITLE
fix: CometShuffleExchangeExec logical link should be correct

### LINKED ISSUE #323: CometShuffleExchangeExec logical link is different to Spark ShuffleExchangeExec
### Describe the bug

Enabling columnar shuffle by default PR #250 causes a lot of test failures in Spark `org.apache.spark.sql.execution.adaptive.AdaptiveQueryExecSuite`.

This is a tricky bug.

I found that it is because Comet sets incorrect logical link to `CometShuffleExchangeExec`. Because logical link is used in Spark AQE framework to do query planning, incorrect logical links cause test failures there.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #323.

### CODE REVIEW

File: spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala [hunk 1]
```diff
@@ -373,6 +405,7 @@ class CometExecSuite extends CometTestBase {
     withSQLConf(
       SQLConf.EXCHANGE_REUSE_ENABLED.key -> "true",
       SQLConf.AUTO_BROADCASTJOIN_THRESHOLD.key -> "-1",
+      SQLConf.ADAPTIVE_AUTO_BROADCASTJOIN_THRESHOLD.key -> "-1",
```
Comment (viirya) [inline spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala:408]: Same reason here.

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala [hunk 2]
```diff
@@ -192,6 +195,21 @@ case class CometShuffleExchangeExec(
...
+    obj match {
+      case other: CometShuffleExchangeExec =>
+        this.outputPartitioning == other.outputPartitioning &&
+        this.shuffleOrigin == other.shuffleOrigin && this.child == other.child &&
+        this.shuffleType == other.shuffleType &&
+        this.advisoryPartitionSize == other.advisoryPartitionSize
+      case _ =>
+        false
+    }
+  }
```
Comment (viirya) [inline spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:209]: Because `CometShuffleExchangeExec` adds `originalPlan` parameter which is not covered by canonicalization in Spark, we need to exclude it when compare two `CometShuffleExchangeExec`.

File: spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala [hunk 3]
```diff
@@ -62,6 +62,37 @@ class CometExecSuite extends CometTestBase {
...
+
+      withSQLConf(
+        SQLConf.ADAPTIVE_EXECUTION_ENABLED.key -> "false",
+        CometConf.COMET_COLUMNAR_SHUFFLE_ENABLED.key -> "false") {
+        val df = sql("SELECT * FROM v where c1 = 1 order by c1, c2")
+        val shuffle = find(df.queryExecution.executedPlan) {
+          case _: ShuffleExchangeExec => true
+          case _ => false
+        }.get.asInstanceOf[ShuffleExchangeExec]
+        assert(shuffle.logicalLink.isEmpty)
```
Comment (kazuyukitanimura) [inline spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala:91]: nit: these two clauses can be one in a loop to reduce the duplication

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala [hunk 4]
```diff
@@ -192,6 +195,24 @@ case class CometShuffleExchangeExec(
...
+
+  override def hashCode(): Int =
+    Objects.hashCode(outputPartitioning, shuffleOrigin, shuffleType, advisoryPartitionSize, child)
+
+  override def stringArgs: Iterator[Any] =
+    Iterator(outputPartitioning, shuffleOrigin, shuffleType, child) ++ Iterator(s"[plan_id=$id]")
```
Comment (viirya) [inline spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:215]: Follow Spark `Exchange.stringArgs`.

**Review by kazuyukitanimura — APPROVED** [review]

File: spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala (hunk 3 above)
Comment (viirya) [reply spark/src/test/scala/org/apache/comet/exec/CometExecSuite.scala:91]: Okay

File: spark/src/test/scala/org/apache/spark/sql/CometTPCHQuerySuite.scala [hunk 5]
```diff
@@ -91,6 +91,7 @@ class CometTPCHQuerySuite extends QueryTest with CometTPCBase with SQLQueryTestH
     conf.set(CometConf.COMET_EXEC_ALL_OPERATOR_ENABLED.key, "true")
     conf.set(CometConf.COMET_EXEC_ALL_EXPR_ENABLED.key, "true")
     conf.set(CometConf.COMET_EXEC_SHUFFLE_ENABLED.key, "true")
+    conf.set(CometConf.COMET_COLUMNAR_SHUFFLE_ENABLED.key, "true")
```
Comment (viirya) [inline spark/src/test/scala/org/apache/spark/sql/CometTPCHQuerySuite.scala:94]: See #336

**Comment by viirya** [comment]
cc @sunchao @andygrove

**Comment by viirya** [comment]
cc @sunchao @andygrove

**Comment by viirya** [comment]
cc @andygrove Can you take a look if you have time? Thanks.

File: spark/src/main/scala/org/apache/spark/sql/comet/operators.scala [hunk 6]
```diff
@@ -263,6 +264,13 @@ abstract class CometNativeExec extends CometExec {
               inputs += c.setNumPartitions(firstNonBroadcastPlanNumPartitions).executeColumnar()
             case BroadcastQueryStageExec(_, c: CometBroadcastExchangeExec, _) =>
               inputs += c.setNumPartitions(firstNonBroadcastPlanNumPartitions).executeColumnar()
+            case ReusedExchangeExec(_, c: CometBroadcastExchangeExec) =>
+              inputs += c.setNumPartitions(firstNonBroadcastPlanNumPartitions).executeColumnar()
+            case BroadcastQueryStageExec(
+                  _,
+                  ReusedExchangeExec(_, c: CometBroadcastExchangeExec),
+                  _) =>
+              inputs += c.setNumPartitions(firstNonBroadcastPlanNumPartitions).executeColumnar()
```
Comment (viirya) [inline spark/src/main/scala/org/apache/spark/sql/comet/operators.scala:273]: These are necessary but missed to add previously. This fix exposes that.

**Review by sunchao — APPROVED** [review]

**Comment by viirya** [comment]
Merged. Thanks @sunchao
