### PR TITLE
fix: Fix memory bloat caused by holding too many unclosed `ArrowReaderIterator`s

### LINKED ISSUE #927: Excessive memory usage when running TPC-H Query 21 on a large cluster
### Describe the bug

We observed excessive memory usage when running [TPC-H Query 21](https://github.com/apache/datafusion-benchmarks/blob/main/tpch/queries/q21.sql) with scale factor = 1000 on a large cluster. The cluster is composed of 48 worker nodes, each worker node has 6 vCPUs and 48 GB memory. We only use 3 cores for each worker node (`spark.executor.cores = 3`). Please refer to the **Additional context** section for detailed environment and spark configurations. Running TPC-H Q21 repeatedly yields the following memory usage plot on one of the executors. 

image

All other executors have similar memory usage patterns, the RSS gradually climbs to over 30 GB and get stabilized. 8 GB of them is taken by JVM, and the rest 22 GB are native memory allocated by datafusion-comet. This does not seem to be a memory leak, but a memory bloat problem. This amount of memory used by comet makes it impossible to use all 6 cores of the executor pod on EC2 instances with CPU:MEM = 1:8, and infeasible to run on EC2 instances with CPU:MEM = 1:4 (general purpose instances).

### Steps to reproduce

Running TPC-H query 21 repeatedly on a Spark cluster. The detailed environment and spark configurations are listed in **Additional context**.

This problem cannot be reproduced locally using `spark.master = local[*]`.

### Expected behavior

Comet uses less memory to make it feasible to work on commodity EC2 instances where CPU:MEM = 1:4.

### Additional context

The problem was produced on a self-deployed K8S Spark cluster on AWS.

* Driver/executor instance type: r7i.2xlarge (8 vCPUs, 64GB memory)
* Executor pod resource limit: 6 vCPUs, 48GB memory. We reserved some resources for some reason
* Number of executor instances: 48
* Spark version: 3.4.0
* Java version: 17
* Comet version: commit https://github.com/apache/datafusion-comet/commit/80e4a2e98faeacc2fb0c041bd75158014921b9d6

Here are relevant spark configurations:

```
spark.executor.cores 3
spark.executor.memory 8192m
# Reserve most of the memory (40 GB) for comet
spark.executor.memoryOverheadFactor 4.99
spark.comet.memory.overhead.factor 0.12

spark.sql.extensions org.apache.comet.CometSparkSessionExtensions
spark.comet.enabled true
spark.comet.exec.enabled true
spark.comet.exec.all.enabled true
spark.comet.exec.shuffle.enabled true
spark.comet.exec.shuffle.mode auto
spark.shuffle.manager org.apache.spark.sql.comet.execution.shuffle.CometShuffleManager
```

### PR DESCRIPTION
**Pull request by Kontinuation**
## Which issue does this PR close?

Closes #927.

## Rationale for this change

Please refer to the comments of #927 for details.

## What changes are included in this PR?

* Holds at most one unclosed `ArrowReaderIterator` in `CometBlockStoreShuffleReader`.
* (optional) automatically close the `ArrowReaderIterator` when reading the end of the stream.

## How are these changes tested?

It is pretty hard to add tests for this fix, so we manually tested this and relying on existing tests to make sure that it does not break anything.

### CODE REVIEW

File: common/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/ArrowReaderIterator.scala [hunk 1]
```diff
@@ -42,10 +46,12 @@ class ArrowReaderIterator(channel: ReadableByteChannel, source: String)
     // memory leak.
     if (currentBatch != null) {
       currentBatch.close()
+      currentBatch = null
     }
 
     batch = nextBatch()
     if (batch.isEmpty) {
+      close()
```
Comment (Kontinuation) [inline common/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/ArrowReaderIterator.scala:54]: This is because I am paranoid and want to close the iterator early. I can revert changes to this file if you don't like it :)

File: common/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometBlockStoreShuffleReader.scala [hunk 2]
```diff
@@ -88,20 +88,20 @@ class CometBlockStoreShuffleReader[K, C](
...
+
+    // Closes last read iterator after the task is finished.
+    // We need to close read iterator during iterating input streams,
+    // instead of one callback per read iterator. Otherwise if there are too many
+    // read iterators, it may blow up the call stack and cause OOM.
+    context.addTaskCompletionListener[Unit] { _ =>
+      if (currentReadIterator != null) {
+        currentReadIterator.close()
+      }
+    }
```
Comment (viirya) [inline common/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometBlockStoreShuffleReader.scala:101]: Based on the issue description, this is the major fix, right?

Comment (Kontinuation) [reply common/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometBlockStoreShuffleReader.scala:101]: Yes.

**Comment by Kontinuation** [comment]
> This looks good to me.
> 
> @Kontinuation Could you rebase this? I would like to make sure this change can pass CI after latest CI change in main branch. Thank you.

Rebased. One of the tests failed because of failing to download dependencies from maven central, it should be transient.

**Comment by viirya** [comment]
> Rebased. One of the tests failed because of failing to download dependencies from maven central, it should be transient.

Thanks. I re-triggered the test. Usually it will pass after that.

**Review by viirya — APPROVED** [review]
