### PR TITLE
fix: Native window operator should be CometUnaryExec

### LINKED ISSUE #775: Native window operator should be CometUnaryExec
### Describe the bug

Found this bug during fixing Spark SQL failures for #651.

`window.sql` in `org.apache.spark.sql.SQLQueryTestSuite` failed:
```
window.sqlESC[0mESC[0m
2024-08-02T22:26:39.9959102Z ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0mESC[31m  Expected "struct<[val:int,cate:string,count(val) OVER (PARTITION BY cate ORDER BY val ASC NULLS FIRST ROWS BETWEEN CURRENT ROW AND CURRENT ROW):bigint
]>", but got "struct<[]>" Schema did not match for query #3ESC[0mESC[0m
2024-08-02T22:26:39.9963875Z ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0mESC[31m  SELECT val, cate, count(val) OVER(PARTITION BY cate ORDER BY val ROWS CURRENT ROW) FROM testDataESC[0mESC[0m
2024-08-02T22:26:39.9966397Z ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0mESC[31m  ORDER BY cate, val: -- !queryESC[0mESC[0m
2024-08-02T22:26:39.9969624Z ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0mESC[31m  SELECT val, cate, count(val) OVER(PARTITION BY cate ORDER BY val ROWS CURRENT ROW) FROM testDataESC[0mESC[0m
2024-08-02T22:26:39.9971356Z ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0mESC[31m  ORDER BY cate, valESC[0mESC[0m
2024-08-02T22:26:39.9972335Z ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0mESC[31m  -- !query schemaESC[0mESC[0m
2024-08-02T22:26:39.9973219Z ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0mESC[31m  struct<>ESC[0mESC[0m
2024-08-02T22:26:39.9974488Z ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0mESC[31m  -- !query outputESC[0mESC[0m
2024-08-02T22:26:39.9975682Z ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0mESC[31m  org.apache.comet.CometNativeExceptionESC[0mESC[0m
2024-08-02T22:26:39.9977303Z ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0mESC[31m  Expects PARTITION BY expression to be ordered (SQLQueryTestSuite.scala:491)ESC[0mESC[0m

```

The current `CometWindowExec` implementation wrongly extends `CometExec`. For Comet native operator, it should be `CometNativeExec`.

Currently, `CometWindowExec` creates a pseudo native scan for the native window operator, but the native plan is incorrect. It uses the window operator's output as the pseudo scan's output, but it should be the child plan's output. The incorrect output causes errors in DataFusion Window operator.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #775.

### CODE REVIEW

File: spark/src/main/scala/org/apache/spark/sql/comet/CometWindowExec.scala [hunk 1]
```diff
@@ -65,71 +65,27 @@ case class CometWindowExec(
...
+
+  override def equals(obj: Any): Boolean = {
+    obj match {
+      case other: CometWindowExec =>
+        this.windowExpression == other.windowExpression && this.child == other.child &&
+        this.partitionSpec == other.partitionSpec && this.orderSpec == other.orderSpec &&
+        this.serializedPlanOpt == other.serializedPlanOpt
+      case _ =>
+        false
     }
```
Comment (viirya) [inline spark/src/main/scala/org/apache/spark/sql/comet/CometWindowExec.scala:86]: This native plan is incorrect. This uses the window operator's output as the pseudo scan's output, but it should be the child plan's output. The incorrect output causes errors in DataFusion Window operator.

File: spark/src/main/scala/org/apache/spark/sql/comet/CometWindowExec.scala [hunk 2]
```diff
@@ -65,71 +65,27 @@ case class CometWindowExec(
...
 
   override def outputPartitioning: Partitioning = child.outputPartitioning
 
   protected def withNewChildInternal(newChild: SparkPlan): SparkPlan =
     this.copy(child = newChild)
 
-}
-
-object CometWindowExec {
-  def getNativePlan(
```
Comment (viirya) [inline spark/src/main/scala/org/apache/spark/sql/comet/CometWindowExec.scala:90]: Because `Window` is native operator, we should chain it in the native operators instead of creating a pseudo scan for it.

Comment (viirya) [reply spark/src/main/scala/org/apache/spark/sql/comet/CometWindowExec.scala:90]: It also can improve performance as we don't need additional native/JVM bridge.

File: spark/src/main/scala/org/apache/spark/sql/comet/CometWindowExec.scala (hunk 1 above)
Comment (viirya) [reply spark/src/main/scala/org/apache/spark/sql/comet/CometWindowExec.scala:82]: Besides, native window operator requires correct partitioning and ordering information from its child operator. The current native scan operator doesn't have these information.

**Review by huaxingao — APPROVED** [review]
Thanks for catching the problem!

**Comment by viirya** [comment]
Thanks @huaxingao
