### PR TITLE
fix: Making shuffle files generated in native shuffle mode reclaimable

### LINKED ISSUE #1567: Shuffle files written by native CometExchange operator cannot be cleaned
### Describe the bug

Running TPC-H SF=100 on a single node repeatedly will eventually run out of disk when native or auto shuffle mode is enabled. The shuffle files generated when running the queries never gets deleted. Setting `spark.cleaner.periodicGC.interval=60s` or manually trigger driver GC does not help.

This problem only happens when `spark.comet.exec.shuffle.mode` is `native` or `auto`. It does not happen when shuffle mode is `jvm`.

### Steps to reproduce

Run [tpcbench.py](https://github.com/apache/datafusion-benchmarks/blob/main/runners/datafusion-comet/tpcbench.py) with `--iterations 10` will take hundreds of gigs of disk space. Here is an example:

```
spark-submit \
        --master local[8] \
        --conf spark.driver.memory=3g \
        --conf spark.memory.offHeap.enabled=true \
        --conf spark.memory.offHeap.size=16g \
        --conf spark.cleaner.periodicGC.interval=60s \
        --conf spark.jars=/path/to/comet-spark-spark3.5_2.12-0.8.0-SNAPSHOT.jar \
        --conf spark.driver.extraClassPath=/path/to/comet-spark-spark3.5_2.12-0.8.0-SNAPSHOT.jar \
        --conf spark.executor.extraClassPath=/path/to/comet-spark-spark3.5_2.12-0.8.0-SNAPSHOT.jar \
        --conf spark.sql.extensions=org.apache.comet.CometSparkSessionExtensions \
        --conf spark.shuffle.manager=org.apache.spark.sql.comet.execution.shuffle.CometShuffleManager \
        --conf spark.comet.enabled=true \
        --conf spark.comet.exec.shuffle.enabled=true \
        --conf spark.comet.exec.shuffle.mode=native \
        --conf spark.comet.exec.shuffle.fallbackToColumnar=true \
        --conf spark.comet.exec.shuffle.compression.codec=lz4 \
        --conf spark.comet.exec.replaceSortMergeJoin=true \
        tpcbench.py \
        --benchmark tpch \
        --data /path/to/tpch/sf100_parquet \
        --queries ../../tpch/queries \
        --output tpc-results \
        --iterations 10
```

### Expected behavior

Unused shuffle files should be deleted when GC was triggered on Spark driver.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Kontinuation**
## Which issue does this PR close?

Closes #1567.

## Rationale for this change

Shuffle file deletes were handled by the [`unregisterShuffle`](https://github.com/apache/datafusion-comet/blob/0.7.0/spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleManager.scala#L214-L221) method of shuffle manager. `CometShuffleManager` uses a map [taskIdMapsForShuffle](https://github.com/apache/datafusion-comet/blob/0.7.0/spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleManager.scala#L58-L61) to keep track of which shuffle files to delete for a given task. This map only gets updated when [`getWriter`](https://github.com/apache/datafusion-comet/blob/0.7.0/spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleManager.scala#L175-L184) is called.

In JVM shuffle mode, shuffle writers are obtained by calling the `getWriter` method of CometShuffleManager, the map gets updated to remember which shuffle file was created for a task, so `unregisterShuffle` could work correctly in this case. However, we use a [custom shuffle write processor](https://github.com/apache/datafusion-comet/blob/0.7.0/spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala#L236) in native mode, which does not call `getWriter` method when performing shuffle writes. The shuffle files written in native mode were not tracked by `taskIdMapsForShuffle` and won't be deleted when `unregisterShuffle` was called.

## What changes are included in this PR?

This PR refactored the native shuffle writer to implement `org.apache.spark.shuffle.ShuffleWriter`, and make all shuffle writers being created by calling the `getWriter` method of `CometShuffleManager`. Now `CometShuffleManager` will be able to keep track of shuffle files of all tasks, and delete them on unregistration.

## How are these changes tested?

* Added a unit test.
* Tested manually using TPC-H SF=100 benchmarks

### CODE REVIEW

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometNativeShuffleWriter.scala [hunk 1]
```diff
@@ -0,0 +1,221 @@
...
+class CometNativeShuffleWriter[K, V](
+    outputPartitioning: Partitioning,
+    outputAttributes: Seq[Attribute],
+    metrics: Map[String, SQLMetric],
+    numParts: Int,
+    shuffleId: Int,
+    mapId: Long,
+    context: TaskContext,
+    metricsReporter: ShuffleWriteMetricsReporter)
+    extends ShuffleWriter[K, V] {
```
Comment (Kontinuation) [inline spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometNativeShuffleWriter.scala:53]: This class is mostly copy-pasted from CometShuffleExchangeExec.scala, with a few additional changes noted in review comments.

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometNativeShuffleWriter.scala [hunk 2]
```diff
@@ -0,0 +1,221 @@
...
+      outputAttributes.length,
+      nativePlan,
+      nativeMetrics,
+      numParts,
+      context.partitionId())
+
+    while (cometIter.hasNext) {
+      cometIter.next()
+    }
+    cometIter.close()
```
Comment (Kontinuation) [inline spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometNativeShuffleWriter.scala:104]: Added a `cometIter.close()` call.

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometNativeShuffleWriter.scala [hunk 3]
```diff
@@ -0,0 +1,221 @@
...
+      .drop(1) // first partition offset is always 0
+      .map(indexBytes => {
+        val partitionOffset =
+          ByteBuffer.wrap(indexBytes).order(ByteOrder.LITTLE_ENDIAN).getLong
+        val partitionLength = partitionOffset - offset
+        offset = partitionOffset
+        partitionLength
+      })
+      .toArray
+    Files.delete(tempIndexFilePath)
```
Comment (Kontinuation) [inline spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometNativeShuffleWriter.scala:120]: Delete the temp index file, it won't be used after reading all partition lengths from it.

File: spark/src/test/scala/org/apache/comet/exec/CometNativeShuffleSuite.scala [hunk 4]
```diff
@@ -201,6 +202,23 @@ class CometNativeShuffleSuite extends CometTestBase with AdaptiveSparkPlanHelper
     }
   }
 
+  test("fix: Comet native shuffle deletes shuffle files after query") {
+    withParquetTable((0 until 5).map(i => (i, i + 1)), "tbl") {
+      sql("SELECT count(_2), sum(_2) FROM tbl GROUP BY _1").collect()
+      val diskBlockManager = SparkEnv.get.blockManager.diskBlockManager
+      var hasShuffleFiles = true
+      var counter = 0
+      while (hasShuffleFiles && counter < 30) {
```
Comment (wForget) [inline spark/src/test/scala/org/apache/comet/exec/CometNativeShuffleSuite.scala:211]: nit: use [eventually](https://www.scalatest.org/scaladoc/3.2.16/org/scalatest/concurrent/Eventually.html), like:

```
eventually(timeout(30.seconds), interval(1.seconds)) {
  System.gc()
  assert(diskBlockManager.getAllFiles().isEmpty)
}
```

Comment (Kontinuation) [reply spark/src/test/scala/org/apache/comet/exec/CometNativeShuffleSuite.scala]: That's neat! Switched to eventually in https://github.com/apache/datafusion-comet/pull/1568/commits/8855913b56280b602215136cd3367d509318a11e.

**Comment by mbutrovich** [comment]
Thank you for the good fix! I'll take a pass through this.

**Review by mbutrovich — CHANGES_REQUESTED** [review]
Minor nits. Thanks for the great fix!

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala [hunk 5]
```diff
@@ -232,14 +222,17 @@ object CometShuffleExchangeExec extends ShimCometShuffleExchangeExec {
...
         override def getPartition(key: Any): Int = key.asInstanceOf[Int]
       },
-      decodeTime = metrics("decode_time"))
+      decodeTime = metrics("decode_time"),
+      outputPartitioning = Some(outputPartitioning),
+      outputAttributes = outputAttributes,
+      shuffleWriteMetrics = metrics,
+      numParts = numParts)
     dependency
   }
```
[the remark this answers is not in the document]
Comment (Kontinuation) [reply spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:238]: Made this change in latest commit.

File: spark/src/test/scala/org/apache/comet/exec/CometNativeShuffleSuite.scala [hunk 6]
```diff
@@ -201,6 +204,17 @@ class CometNativeShuffleSuite extends CometTestBase with AdaptiveSparkPlanHelper
     }
   }
 
+  test("fix: Comet native shuffle deletes shuffle files after query") {
+    withParquetTable((0 until 5).map(i => (i, i + 1)), "tbl") {
+      sql("SELECT count(_2), sum(_2) FROM tbl GROUP BY _1").collect()
+      val diskBlockManager = SparkEnv.get.blockManager.diskBlockManager
+      eventually(timeout(30.seconds), interval(1.seconds)) {
```
[the remark this answers is not in the document]
Comment (Kontinuation) [reply spark/src/test/scala/org/apache/comet/exec/CometNativeShuffleSuite.scala:214]: Asserted that the files list is non-empty. I have to hold the reference to the DataFrame while asserting to prevent from GC kicking in just before the assertion.

**Review by mbutrovich — APPROVED** [review]
I think that's an unrelated CI failure. LGTM!

**Review by kazuyukitanimura — COMMENTED** [review]
Looks good, one pure question

File: spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala [hunk 7]
```diff
@@ -232,20 +222,23 @@ object CometShuffleExchangeExec extends ShimCometShuffleExchangeExec {
         (0, _)
       ), // adding fake partitionId that is always 0 because ShuffleDependency requires it
       serializer = serializer,
-      shuffleWriterProcessor =
-        new CometShuffleWriteProcessor(outputPartitioning, outputAttributes, metrics, numParts),
+      shuffleWriterProcessor = ShuffleExchangeExec.createShuffleWriteProcessor(metrics),
```
[the remark this answers is not in the document]
Comment (Kontinuation) [reply spark/src/main/scala/org/apache/spark/sql/comet/execution/shuffle/CometShuffleExchangeExec.scala:225]: Yes. `ShuffleExchangeExec.createShuffleWriteProcessor` will call `getWriter` of the shuffle manager internally (will be `CometShuffleManager` when comet shuffle is enabled). `CometShuffleManager.getWriter` will initialize a `CometNativeShuffleWriter` when shuffle type is `CometNativeShuffle`.

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @Kontinuation

**Comment by andygrove** [comment]
Thanks for the reviews @mbutrovich and @kazuyukitanimura
