### PR TITLE
fix: Executor memory overhead overriding

### LINKED ISSUE #1460: Comet executor memory overriding to absurd numbers (unified mode)
### Describe the bug

When initialization Spark session in unified mode, Comet overrides `spark.executor.memoryOverhead` to over 100GB memory requirements.

https://github.com/apache/datafusion-comet/blob/928e1a2bbea6b19bdcefd620395fd7ffffc4773c/spark/src/main/scala/org/apache/spark/Plugins.scala#L65-L72

First the `if` clause seems to be reversed. Secondly, `CometSparkSessionExtensions.getCometShuffleMemorySize` returns memory in bytes, which is added to memory in MB. This leads overriding memory allocation to absurd sizes.

### Steps to reproduce

Create spark session and see `spark.executor.memoryOverhead`.

```scala
import org.apache.spark.sql.SparkSession

val spark = SparkSession.builder()
    .appName("sample") 
    .config("spark.executor.memory", "2G")
    .config("spark.executor.memoryOverhead", "5G")
    .config("spark.driver.memory", "2G") 
    .config("spark.driver.memoryOverhead", "2G")
    
    .config("spark.comet.exec.enabled", "true")
    .config("spark.shuffle.manager", "org.apache.spark.sql.comet.execution.shuffle.CometShuffleManager")
    .config("spark.comet.shuffle.enabled", "true")
    .config("spark.comet.explainFallback.enabled", "true")
    .config("spark.memory.offHeap.enabled", "true")
    .config("spark.memory.offHeap.size", "3G")
    .config("spark.comet.memory.overhead.factor", "0.2")    
    .config("spark.comet.convert.json.enabled", "true")
    
    .config("spark.plugins", "org.apache.spark.CometPlugin")
    .config("spark.comet.enabled", "true")
    .getOrCreate()
```

### Expected behavior

Overriding executor memory to reasonable amounts set by `spark.comet.memoryOverhead` or computed in MB units

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LukMRVC**
## Which issue does this PR close?

Closes #1460 .

## Rationale for this change

Even when using unified memory, Comet would override `spark.executor.memoryOverhead` using inconsistent byte units.
This situation should not have happened in the first place.

## What changes are included in this PR?

Fixes for
* `shouldOverrideMemoryConf`
* Adds result of `getCometShuffleMemorySizeInMiB` to executor memoryOverhead 

## How are these changes tested?

Added `CometPluginsNonOverrideUnifiedModeSuite` to test that `spark.executor.memoryOverhead` is not overridden, which failed in previous versions.

### CODE REVIEW

**Comment by andygrove** [comment]
Thanks @LukMRVC. Could you fix the code formatting issue?

There are instructions in https://datafusion.apache.org/comet/contributor-guide/development.html#submitting-a-pull-request

**Comment by LukMRVC** [comment]
Yes, it should be fixed by now.

**Comment by wForget** [comment]
Thank you for finding this issue, which was introduced in my previous PR #1379

**Comment by wForget** [comment]
> Thank you for finding this issue, which was introduced in my previous PR #1379

My initial proposal was:
+ When unified memroy manager is disabled, we should use `getCometMemoryOverheadInMiB` override spark executor memory overhead.
+ When unified memroy manager is enabled but shuffle unified memroy manager is disabled, we should use `getCometShuffleMemorySizeInMiB` override spark executor memory overhead.
+ When unified memroy manager and shuffle unified memroy manager are enabled, we don't need to override spark executor memory overhead.

**Comment by LukMRVC** [comment]
Okay, @wForget I reverted some of my changes back to align with your proposal of overriding executor memory.

**Comment by andygrove** [comment]
PR builds are currently failing. This should be fixed by https://github.com/apache/datafusion-comet/pull/1465

**Comment by wForget** [comment]
> Okay, @wForget I reverted some of my changes back to align with your proposal of overriding executor memory.

Does newly added test case also need to be changed?

**Comment by LukMRVC** [comment]
That one should be fine, they passed with current changes to overriding spark executor memory, but fail without them.

File: spark/src/test/scala/org/apache/spark/CometPluginsSuite.scala [hunk 1]
```diff
@@ -143,3 +143,36 @@ class CometPluginsNonOverrideSuite extends CometTestBase {
...
+    conf.set("spark.comet.enabled", "true")
+    conf.set("spark.memory.offHeap.enabled", "true")
+    conf.set("spark.memory.offHeap.size", "2G")
+    conf.set("spark.comet.exec.shuffle.enabled", "true")
+    conf.set("spark.comet.exec.enabled", "true")
+    conf.set("spark.comet.memory.overhead.factor", "0.5")
+    conf
+  }
+
+  /** Since using unified memory, executor memory should not be overridden */
```
Comment (wForget) [inline spark/src/test/scala/org/apache/spark/CometPluginsSuite.scala:163]: > That one should be fine, they passed with current changes to overriding spark executor memory, but fail without them.

Indeed, I successfully run this test locally, but this comment seems incorrect

Comment (LukMRVC) [reply spark/src/test/scala/org/apache/spark/CometPluginsSuite.scala]: Yes, you are right. I overlooked it. I changed the comment.

**Review by wForget — APPROVED** [review]
Thanks, LGTM
