### PR TITLE
fix: partially fix consistency issue of hash functions with decimal input

### LINKED ISSUE #1294: Result mismatch with vanilla spark in hash function with decimal input
### Describe the bug

Result mismatch with vanilla spark in hash function with decimal input.

## Case 1: `precision <= 18`

When precision is less than or equal to 18, spark use unscaled long value of decimal to calculate hash.

https://github.com/apache/spark/blob/d12bb23e49928ae36b57ac5fbeaa492dadf7d28f/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/hash.scala#L560-L567

test: 

```
sql(s"create table t1(c1 decimal(18, 2)) using parquet")
sql(s"insert into t1 values(1.23), (-1.23), (0.0), (null)")
checkSparkAnswerAndOperator(s"select c1, hash(c1), xxhash64(c1) from t1 order by c1")
```

result:

```
!== Correct Answer - 4 ==                                    == Spark Answer - 4 ==
 struct<c1:decimal(18,2),hash(c1):int,xxhash64(c1):bigint>   struct<c1:decimal(18,2),hash(c1):int,xxhash64(c1):bigint>
 [null,42,42]                                                [null,42,42]
![-1.23,1993430267,-2573642654262063070]                     [-1.23,1891444694,1620882180304245068]
![0.00,-1670924195,-5252525462095825812]                     [0.00,-300363099,-3510225485978208079]
![1.23,-46242105,-3178482946328430151]                       [1.23,93356439,7126273675055069777]
```

## Case 1: `precision > 18`

When precision is greater than 18, spark use bytes of unscaled value to calculate hash. But the results are still inconsistent.

test:

```
sql(s"create table t2(c1 decimal(20, 2)) using parquet")
sql(s"insert into t2 values(1.23), (-1.23), (0.0), (null)")
checkSparkAnswerAndOperator(s"select c1, hash(c1), xxhash64(c1) from t2 order by c1")
```

result:

```
!== Correct Answer - 4 ==                                    == Spark Answer - 4 ==
 struct<c1:decimal(20,2),hash(c1):int,xxhash64(c1):bigint>   struct<c1:decimal(20,2),hash(c1):int,xxhash64(c1):bigint>
 [null,42,42]                                                [null,42,42]
![-1.23,1285747285,3359051433950298639]                      [-1.23,1891444694,1620882180304245068]
![0.00,-783713497,-8959994473701255385]                      [0.00,-300363099,-3510225485978208079]
![1.23,-1536290115,1973765065063347049]                      [1.23,93356439,7126273675055069777]
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wForget**
## Which issue does this PR close?

This is a partial fix for #1294, which fixes the consistency issue of hash functions for small decimal (precision <= 18).

## Rationale for this change

When precision is less than or equal to 18, spark use unscaled long value of decimal to calculate hash.

https://github.com/apache/spark/blob/d12bb23e49928ae36b57ac5fbeaa492dadf7d28f/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/hash.scala#L560-L567

## What changes are included in this PR?

When precision is less than or equal to 18, convert i128 native value of decimal to i64 to calculate hash.

## How are these changes tested?

added unit test

### CODE REVIEW

File: native/spark-expr/src/hash_funcs/utils.rs [hunk 1]
```diff
@@ -106,17 +106,28 @@ macro_rules! hash_array_primitive_float {
...
 macro_rules! hash_array_decimal {
-    ($array_type:ident, $column: ident, $hashes: ident, $hash_method: ident) => {
+    ($array_type:ident, $column: ident, $hashes: ident, $hash_method: ident, $precision: ident) => {
         let array = $column.as_any().downcast_ref::<$array_type>().unwrap();
+        let precision = *$precision;
 
         if array.null_count() == 0 {
             for (i, hash) in $hashes.iter_mut().enumerate() {
-                *hash = $hash_method(array.value(i).to_le_bytes(), *hash);
+                // when precision is less than or equal to 18, spark use deimal long value to calculate hash.
```
Comment (andygrove) [inline native/spark-expr/src/hash_funcs/utils.rs:115]:
```suggestion
                // when precision is less than or equal to 18, spark use decimal long value to calculate hash.
```

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 2]
```diff
@@ -1928,6 +1928,23 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+      // refer: org.apache.spark.sql.catalyst.expressions.InterpretedHashFunction.hash
+      sql("create table t1(c1 decimal(18, 2)) using parquet")
+      sql("insert into t1 values(1.23), (-1.23), (0.0), (null)")
+      checkSparkAnswerAndOperator("select c1, hash(c1), xxhash64(c1) from t1 order by c1")
+
+      // TODO: comet hash function is not compatible with spark for decimal with precision greater than 18.
+      // https://github.com/apache/datafusion-comet/issues/1294
+//       sql("create table t2(c1 decimal(20, 2)) using parquet")
+//       sql("insert into t2 values(1.23), (-1.23), (0.0), (null)")
+//       checkSparkAnswerAndOperator("select c1, hash(c1), xxhash64(c1) from t2 order by c1")
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1944]: To make sure I understand, this also needs to be fixed before we can close https://github.com/apache/datafusion-comet/issues/1294?

File: native/spark-expr/src/hash_funcs/utils.rs [hunk 3]
```diff
@@ -106,17 +106,28 @@ macro_rules! hash_array_primitive_float {
...
+                // refer: org.apache.spark.sql.catalyst.expressions.InterpretedHashFunction.hash
+                if precision <= 18 {
```
Comment (andygrove) [inline native/spark-expr/src/hash_funcs/utils.rs:117]: I wonder if we should create a separate version of the macro for the `precision <= 18` case to avoid branching?

File: native/spark-expr/src/hash_funcs/utils.rs (hunk 1 above)
Comment (comphead) [reply native/spark-expr/src/hash_funcs/utils.rs:115]: I would add original Spark comment
```
 Apache Spark:                 if it's a small decimal, i.e. precision <= 18, turn it into long  and hash it. Else, turn it into bytes and hash it.
```

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala (hunk 2 above)
Comment (kazuyukitanimura) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1944]: Alternatively we can change the PR description to part of #1294 and address this in a separate PR

File: native/spark-expr/src/hash_funcs/utils.rs (hunk 1 above)
Comment (wForget) [reply native/spark-expr/src/hash_funcs/utils.rs]: thank you, changed

File: native/spark-expr/src/hash_funcs/utils.rs (hunk 3 above)
Comment (wForget) [reply native/spark-expr/src/hash_funcs/utils.rs]: Thank you, that sounds good to me, I tried separating it

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala (hunk 2 above)
Comment (wForget) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1944]: Sorry, I have no idea to fix decimal to bytes consistency with spark yet, so I just submitted this partial fix. I will change the PR description.

**Review by andygrove — APPROVED** [review]
Thank you for the contribution @wForget!

File: native/spark-expr/src/hash_funcs/utils.rs [hunk 4]
```diff
@@ -104,6 +104,26 @@ macro_rules! hash_array_primitive_float {
...
+        if array.null_count() == 0 {
+            for (i, hash) in $hashes.iter_mut().enumerate() {
+                *hash = $hash_method(i64::try_from(array.value(i)).unwrap().to_le_bytes(), *hash);
+            }
+        } else {
+            for (i, hash) in $hashes.iter_mut().enumerate() {
+                if !array.is_null(i) {
+                    *hash =
+                        $hash_method(i64::try_from(array.value(i)).unwrap().to_le_bytes(), *hash);
+                }
```
[the remark this answers is not in the document]
Comment (wForget) [reply native/spark-expr/src/hash_funcs/utils.rs:121]: It seems not, `$hashes` is filled with seed value by default, and the hash function will return seed when input is empty. The test case has also covered null value.

[the remark this answers is not in the document]
Comment (wForget) [reply native/spark-expr/src/hash_funcs/utils.rs:121]: spark: https://github.com/apache/spark/blob/d12bb23e49928ae36b57ac5fbeaa492dadf7d28f/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/hash.scala#L550

comet: https://github.com/apache/datafusion-comet/blob/a856650d893c974aa7672a57ec8e7f6fcd615cda/native/spark-expr/src/hash_funcs/xxhash64.rs#L50
