### PR TITLE
fix: Fix various memory leaks problems

### LINKED ISSUE #884: Memory leaks when running the TPC-H benchmark repeatedly
### Describe the bug

I've built Datafusion Comet using commit https://github.com/apache/datafusion-comet/commit/f7f0bb1ed68367b8d3e1c88010c1f943f480ea11 for Spark 3.5.1. I found that the memory usage keeps increasing when repeatedly running the [TPC-H benchmark script](https://github.com/apache/datafusion-benchmarks/blob/main/runners/datafusion-comet/tpcbench.py) on a set of parquet files. The parquet files were generated using https://github.com/databricks/spark-sql-perf with scale factor = 10. The memory usage could be as high as 20GB. Given the spark and comet configurations I'm using to run the benchmarks (see **Additional context**) this seems to be problematic.

image

I've noticed that the native memory allocated by `Unsafe_AllocateMemory0` keeps increasing using `jcmd VM.native_memory detail.diff | grep Unsafe -A 2`. I'm not enabling offheap memory so the allocation should be initiated by the arrow `RootAllocator`:

Initially after setting the baseline:

```
[0x00000001099c98a8] Unsafe_AllocateMemory0(JNIEnv_*, _jobject*, long)+0xcc
[0x000000011a0523b4]
                             (malloc=870721KB type=Other +621478KB #6842866 +4937676)
--
[0x00000001099c98a8] Unsafe_AllocateMemory0(JNIEnv_*, _jobject*, long)+0xcc
[0x0000000119017be0]
                             (malloc=8463KB type=Other -469KB #221 -3)
```

After 10 minutes:

```
[0x00000001099c98a8] Unsafe_AllocateMemory0(JNIEnv_*, _jobject*, long)+0xcc
[0x000000011a0523b4]
                             (malloc=4349265KB type=Other +4100021KB #34671096 +32765906)
--
[0x00000001099c98a8] Unsafe_AllocateMemory0(JNIEnv_*, _jobject*, long)+0xcc
[0x0000000119017be0]
                             (malloc=8449KB type=Other -483KB #217 -7)
```

The leaked memory were allocated by the [`CometArrowAllocator`](https://github.com/apache/datafusion-comet/blob/33706125b8c7a7f347865c7fb38fede6aceb97e9/common/src/main/scala/org/apache/comet/package.scala#L35). I've verified this by attaching a debugger to the Spark process and inspected `CometArrowAllocator.getAllocatedMemory`:

image

I've also deliberately disabled AQE coalesce partitions since I noticed this issue: https://github.com/apache/datafusion-comet/issues/381. Although it is fixed I still disabled it for being safe.  See **Additional context** section for more details.

### Steps to reproduce

Run the [TPC-H benchmark script](https://github.com/apache/datafusion-benchmarks/blob/main/runners/datafusion-comet/tpcbench.py) with `--iterations=100` and observe the RSS of the Spark process increase over time.

### Expected behavior

Memory usage should not increase over time.

### Additional context

I'm simply running it locally with `master = local[4]`. Here are my test environment and spark configurations:

**Environment**:

* Operating System: macOS 14.6.1, arch: Apple M1 Pro
* Apache Spark: 3.5.1
* Datafusion Comet: commit https://github.com/apache/datafusion-comet/commit/f7f0bb1ed68367b8d3e1c88010c1f943f480ea11
* JVM: 17.0.10 (Eclipse Adoptium)

**Spark configurations**:

```
spark.master                     local[4]
spark.driver.cores               4
spark.executor.cores             4
spark.driver.memory              4g
spark.executor.memory            4g
spark.comet.memory.overhead.factor 0.4

spark.jars                     /path/to/workspace/github/datafusion-comet/spark/target/comet-spark-spark3.5_2.12-0.3.0-SNAPSHOT.jar

spark.driver.extraClassPath    /path/to/workspace/github/datafusion-comet/spark/target/comet-spark-spark3.5_2.12-0.3.0-SNAPSHOT.jar
spark.executor.extraClassPath  /path/to/workspace/github/datafusion-comet/spark/target/comet-spark-spark3.5_2.12-0.3.0-SNAPSHOT.jar

spark.serializer          org.apache.spark.serializer.KryoSerializer

spark.sql.extensions         org.apache.comet.CometSparkSessionExtensions
spark.comet.enabled          true
spark.comet.exec.enabled     true
spark.comet.exec.all.enabled true
spark.comet.explainFallback.enabled false

spark.comet.exec.shuffle.enabled true
spark.comet.exec.shuffle.mode auto
spark.shuffle.manager org.apache.spark.sql.comet.execution.shuffle.CometShuffleManager

# Disable AQE coalesce partitions
spark.sql.adaptive.enabled   false
spark.sql.adaptive.coalescePartitions.enabled  false

# Enable debugging and native memory tracking
spark.driver.extraJavaOptions  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -XX:NativeMemoryTracking=detail
```

### PR DESCRIPTION
**Pull request by Kontinuation**
## Which issue does this PR close?

Closes #884.

## Rationale for this change

Please refer to the comments in https://github.com/apache/datafusion-comet/issues/884 for details.

## What changes are included in this PR?

* Fixes `ArrowSchema` and `ArrowArray` base structure leaks in JVM
* Fixes AQE coalesce partition leaks by closing the ArrowStreamWriter

## How are these changes tested?

It is pretty hard to add tests for this fix, so we manually tested this and relying on existing tests to make sure that it does not break anything.

### CODE REVIEW

File: common/src/main/scala/org/apache/comet/vector/NativeUtil.scala [hunk 1]
```diff
@@ -44,43 +44,53 @@ class NativeUtil {
...
-      batch.column(index) match {
-        case a: CometVector =>
-          val valueVector = a.getValueVector
-
-          val provider = if (valueVector.getField.getDictionary != null) {
-            a.getDictionaryProvider
-          } else {
-            null
-          }
-
```
Comment (viirya) [inline common/src/main/scala/org/apache/comet/vector/NativeUtil.scala:64]: Unrelated change.

File: common/src/main/scala/org/apache/comet/vector/NativeUtil.scala [hunk 2]
```diff
@@ -44,43 +44,53 @@ class NativeUtil {
...
+        getFieldVector(valueVector, "export"),
+        provider,
+        arrowArray,
+        arrowSchema)
+
+      exportedVectors += arrowArray.memoryAddress()
+      exportedVectors += arrowSchema.memoryAddress()
     }
 
-    exportedVectors.toArray
```
Comment (viirya) [inline common/src/main/scala/org/apache/comet/vector/NativeUtil.scala:83]: You can return `ExportedBatch` without any above change.

File: spark/src/main/java/org/apache/comet/CometBatchIterator.java [hunk 3]
```diff
@@ -45,12 +49,27 @@ public class CometBatchIterator {
    * indicating the end of the iterator.
    */
   public long[] next() {
+    // The native executor should have moved the previous batch, it is safe for us to deallocate
+    // the ArrowSchema and ArrowArray base structures.
```
Comment (viirya) [inline spark/src/main/java/org/apache/comet/CometBatchIterator.java:53]: Not always. A native operator could possibly save batches internally.

File: common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala [hunk 4]
```diff
@@ -215,12 +215,8 @@ object Utils {
       val writer = new ArrowStreamWriter(root, provider, Channels.newChannel(out))
       writer.start()
       writer.writeBatch()
-
       root.clear()
-      writer.end()
-
-      out.flush()
-      out.close()
+      writer.close()
```
Comment (viirya) [inline common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala:219]: Closing the writer will close the dictionary provider. If the dictionary arrays are shared across batches, you will close them and empty later batches. I remember we hit the issue before.

File: common/src/main/scala/org/apache/comet/vector/NativeUtil.scala (hunk 1 above)
Comment (Kontinuation) [reply common/src/main/scala/org/apache/comet/vector/NativeUtil.scala:64]: This is for moving the sanity check for column types prior to the actual construction of the Arrow C data structure. It is tricky to release already constructed FFI data structures before raising the exception.

File: spark/src/main/java/org/apache/comet/CometBatchIterator.java (hunk 3 above)
Comment (Kontinuation) [reply spark/src/main/java/org/apache/comet/CometBatchIterator.java:53]: Yes, even though the native operator save batches internally, the batch would be moved to the native operator to be saved.

File: common/src/main/scala/org/apache/comet/vector/NativeUtil.scala (hunk 2 above)
Comment (Kontinuation) [reply common/src/main/scala/org/apache/comet/vector/NativeUtil.scala:83]: If you don't like the restructuring that moves the sanity checks, I can revert it to the original control flow.

File: common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala (hunk 4 above)
Comment (Kontinuation) [reply common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala:219]: Hmm... I need to take further look at this to fully understand if this fix is correct or not.

Comment (Kontinuation) [reply common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala:219]: This should be correct. The dictionary provider held by the writer [contains copied vectors](https://github.com/apache/arrow/blob/main/java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowStreamWriter.java#L159), so closing them does not interfere with the rest of the data structures.

File: common/src/main/scala/org/apache/comet/vector/ExportedBatch.scala [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+ *   the exported Arrow arrays, needs to be deallocated after being moved by the native executor
+ */
+case class ExportedBatch(
+    batch: Array[Long],
+    arrowSchemas: Array[ArrowSchema],
+    arrowArrays: Array[ArrowArray]) {
+  def close(): Unit = {
+    arrowSchemas.foreach { schema =>
+      val snapshot = schema.snapshot
+      if (snapshot.release != 0) schema.release()
```
Comment (viirya) [inline common/src/main/scala/org/apache/comet/vector/ExportedBatch.scala:43]: I don't think we should call `release` here. The release of exported array should be done when native side drops the imported array.

File: common/src/main/scala/org/apache/comet/vector/ExportedBatch.scala [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+      schema.close()
+    }
+    arrowArrays.foreach { array =>
+      val snapshot = array.snapshot
+      if (snapshot.release != 0) array.release()
+      array.close()
```
Comment (viirya) [inline common/src/main/scala/org/apache/comet/vector/ExportedBatch.scala:49]: It makes sense to close the internal `ArrowBuf` of `ArrowArray` and `ArrowSchema`. Good catch.

File: common/src/main/scala/org/apache/comet/vector/NativeUtil.scala (hunk 1 above)
Comment (viirya) [reply common/src/main/scala/org/apache/comet/vector/NativeUtil.scala:64]: Oh, okay.

File: common/src/main/scala/org/apache/comet/vector/ExportedBatch.scala (hunk 5 above)
Comment (Kontinuation) [reply common/src/main/scala/org/apache/comet/vector/ExportedBatch.scala:43]: Yes. I did this in case the native side not move away the array (by mistake maybe). This could be removed if the native side always move the array.

File: common/src/main/scala/org/apache/comet/vector/NativeUtil.scala (hunk 2 above)
Comment (viirya) [reply common/src/main/scala/org/apache/comet/vector/NativeUtil.scala:83]: It makes sense for the reason https://github.com/apache/datafusion-comet/pull/890/files#r1736808325

File: common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala (hunk 4 above)
Comment (viirya) [reply common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala:219]: I remember closing it will cause some errors in CI due the reason I mentioned. Let's see if CI can pass or not.

File: spark/src/main/java/org/apache/comet/CometBatchIterator.java (hunk 3 above)
Comment (viirya) [inline spark/src/main/java/org/apache/comet/CometBatchIterator.java:53]:
```suggestion
    // Native side already copied the content of ArrowSchema and ArrowArray. We should deallocate
    // the ArrowSchema and ArrowArray base structures allocated in JVM.
```

File: common/src/main/scala/org/apache/comet/vector/ExportedBatch.scala (hunk 5 above)
Comment (viirya) [reply common/src/main/scala/org/apache/comet/vector/ExportedBatch.scala]: Yea, I took another look. Native side moved them.

File: common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala (hunk 4 above)
Comment (Kontinuation) [reply common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala:219]: The CI passes on all commits of this PR, it has run 3 rounds without problem.

Comment (viirya) [reply common/src/main/scala/org/apache/spark/sql/comet/util/Utils.scala:219]: Yea, maybe there was some other changes before. Anyway it is good to close the writer without issue.

**Comment by viirya** [comment]
@Kontinuation I revised the current approach in https://github.com/apache/datafusion-comet/pull/893. So the ArrowSchema and ArrowArray are allocated in native. By doing that, I think we don't need to release the JVM structures.

**Comment by Kontinuation** [comment]
> @Kontinuation I revised the current approach in #893. So the ArrowSchema and ArrowArray are allocated in native. By doing that, I think we don't need to release the JVM structures.

Yes. They are allocated by the native side in #893,  so they should be released by the native side accordingly.

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Thank you @Kontinuation 

I will merge this first. And in #893, I will remove `ExportedBatch` as it allocates array/schema structures in native.
