### PR TITLE
fix: Supported nested types in HashJoin

### LINKED ISSUE #621: Support nested types in HashJoin
### Describe the bug

Datafusion currently does not support nested types in HashJoin, this was discovered in https://github.com/apache/datafusion-comet/pull/620#discussion_r1663002521 and a guard was added to prevent runtime failures.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

When we upgrade to the next datafusion containing https://github.com/apache/datafusion/pull/11117 and https://github.com/apache/datafusion/pull/11232 we can remove this guard.

### PR DESCRIPTION
**Pull request by eejbyfeldt**
## Which issue does this PR close?

Closes #621 .

## Rationale for this change

Allow more joins to be executed by comet.

## What changes are included in this PR?

The latest Datafusion contains fix for doing joins with struct keys, so this PR removes that limitation. The Spark diffs had to be upgrade to exclude one more test case for the same reason as ther other tests in that test suite.

## How are these changes tested?

Existing and new tests.

### CODE REVIEW

File: spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala [hunk 1]
```diff
@@ -192,6 +192,13 @@ class CometJoinSuite extends CometTestBase {
 
           // DataFusion HashJoin LeftAnti has bugs in handling nulls and is disabled for now.
           // left.join(right, left("_2") === right("_1"), "leftanti")
+
+          // Full join: struct key
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala:196]: Thanks for adding the test. I wonder if we should make this more comprehensive to cover structs containing different types, nulls, and nested structs?

Also, what happens with structs containing unsupported types such as array and map? Do we still fall back for those? It would be good to have a test for this case as well.

Comment (eejbyfeldt) [reply spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala:196]: Good call will add more test cases. Created #797 to make it easier to create nulls of struct type.

> Also, what happens with structs containing unsupported types such as array and map?

Do you mean unsupported by comet here? I think the answer for `map` is that spark does not support joining on `map` so it will fail during the Spark planning stage. I will add a test for array by I guess that requires something like #793 first since we do not support reading arrays from parquet. Or is there some other way testing with arrays?

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 2]
```diff
@@ -2718,11 +2718,6 @@ object QueryPlanSerde extends Logging with ShimQueryPlanSerde with CometExprShim
           return None
         }
 
-        if ((join.leftKeys ++ join.rightKeys).exists(_.dataType.isInstanceOf[StructType])) {
-          withInfo(join, "Unsupported struct data type in join keys")
-          return None
-        }
```
Comment (viirya) [inline spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:2724]: We should further check if the data types are supported using `supportedDataType`.

Comment (eejbyfeldt) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:2724]: So instead of removing this condition we change it to something like
```scala
        if ((join.leftKeys ++ join.rightKeys).exists(e => !supportedDataType(e.dataType, allowStruct = true))) {
          withInfo(join, "Unsupported data type in join keys")
          return None
        }
```
?

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 3]
```diff
@@ -2724,8 +2724,9 @@ object QueryPlanSerde extends Logging with ShimQueryPlanSerde with CometExprShim
           return None
         }
 
-        if ((join.leftKeys ++ join.rightKeys).exists(_.dataType.isInstanceOf[StructType])) {
-          withInfo(join, "Unsupported struct data type in join keys")
+        val keyTypes = (join.leftKeys ++ join.rightKeys).map(_.dataType)
```
Comment (andygrove) [inline spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:2727]: nit: could probably add a `.distinct` on the end of this line and reduce the number of calls to check supported types?

File: spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala (hunk 1 above)
Comment (andygrove) [reply spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala:222]: Good point about map not being supported by Spark.

I think we should fall back for array for now because we don't really support array yet.

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @eejbyfeldt

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala (hunk 2 above)
Comment (viirya) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala]: Oh, I rethink about this. `supportedDataType` doesn't mean Join operator key support. We don't need it.

Comment (eejbyfeldt) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:2730]: Removed.

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala (hunk 3 above)
Comment (eejbyfeldt) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala]: This got removed due to this comment: https://github.com/apache/datafusion-comet/pull/735#discussion_r1714452934

File: spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala (hunk 1 above)
Comment (andygrove) [reply spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala:222]: I think we could improve our test framework to make it easier to test for fallback but it is possible with code like this (must be used after calling collect on a DataFrame). I think we can improve the tests in a future PR.

```
 val str =
          new ExtendedExplainInfo().generateExtendedInfo(df.queryExecution.executedPlan)
        assert(str.contains(expectedMessage))
```
