### PR TITLE
fix: fix memory safety issue in native c2r

### LINKED ISSUE #3308: Native columnar-to-row: UnsafeRow may reference freed/overwritten native memory
## Summary

The native columnar-to-row conversion (`CometNativeColumnarToRowExec`) returns `UnsafeRow` objects that point directly into a Rust-owned buffer via raw pointer. This buffer is cleared and reused on each `convert()` call, which can cause SIGSEGV if any row reference outlives the current batch.

## Root Cause

In `NativeColumnarToRowConverter.scala`, the `NativeRowIterator` does:

```scala
unsafeRow.pointTo(null, rowAddress, rowSize)
```

This points the `UnsafeRow` at off-heap native memory owned by `ColumnarToRowContext.buffer` on the Rust side. The Rust `convert()` method calls `self.buffer.clear()` at the start of each invocation, invalidating all previous row pointers.

### Broadcast path (high risk)

In `CometNativeColumnarToRowExec.scala` (line ~110-130), multiple batches are lazily converted via `flatMap` and passed to `mode.transform(rows, ...)`. When the second batch's `convert()` runs, any `UnsafeRow` from the first batch that hasn't been copied yet points to overwritten or freed memory. Whether this is safe depends on `mode.transform()` eagerly copying each row before the iterator advances — a fragile assumption.

### Streaming path (lower risk)

The `doExecute()` path uses `flatMap` which naturally consumes one batch's iterator before requesting the next, so rows don't span batches. However, downstream Spark operators that retain `InternalRow` references (e.g., sort with spill, certain joins, caching) could still hold stale pointers.

## Symptoms

- SIGSEGV in CI (intermittent, timing-dependent)
- Likely became more visible after enabling native columnar-to-row by default (#3299)

## Suggested Fix

Return `unsafeRow.copy()` from `NativeRowIterator.next()` to copy each row to Java heap memory. This eliminates dangling pointer risk while preserving the performance benefit of native conversion (the copy is just a `memcpy` of already-serialized row bytes).

A more targeted fix would be to copy only in the broadcast path, or to change the Rust side to allocate a new buffer per batch instead of reusing.

## Related

- #3299 (feat: Enable native columnar-to-row by default)
- `native/core/src/execution/columnar_to_row.rs`
- `spark/src/main/scala/org/apache/comet/NativeColumnarToRowConverter.scala`
- `spark/src/main/scala/org/apache/spark/sql/comet/CometNativeColumnarToRowExec.scala`

### PR DESCRIPTION
**Pull request by andygrove**
## Which issue does this PR close?

Closes #3308

## Rationale for this change

`NativeRowIterator` reuses a single `UnsafeRow` object that points to native memory. The buffer is cleared on each convert() call, so any held row references become stale. Return `unsafeRow.copy()` to copy each row to Java heap memory.

### CODE REVIEW

**Comment by andygrove** [comment]
@sqlbenchmark run micro CometColumnarToRowBenchmark

File: spark/src/main/scala/org/apache/comet/NativeColumnarToRowConverter.scala [hunk 1]
```diff
@@ -139,6 +139,6 @@ private class NativeRowIterator(info: NativeColumnarToRowInfo, unsafeRow: Unsafe
     unsafeRow.pointTo(null, rowAddress, rowSize)
     currentIdx += 1
 
-    unsafeRow
+    unsafeRow.copy()
```
Comment (comphead) [inline spark/src/main/scala/org/apache/comet/NativeColumnarToRowConverter.scala:142]: Makes sense... as unsafeRow can be reused. it would inflate mem usage a bit, but it is better than corrupted memory

**Review by comphead — APPROVED** [review]
Thanks @andygrove especially for the local test, if we manage to find a solution without extra copy in future the test will help to guard against  corruption issues

**Comment by andygrove** [comment]
```
Running benchmark: Columnar to Row - Fixed Width Only (no strings)
  Running case: Spark (ColumnarToRowExec)
  Stopped after 24 iterations, 2031 ms
  Running case: Comet JVM (CometColumnarToRowExec)
  Stopped after 25 iterations, 2032 ms
  Running case: Comet Native (CometNativeColumnarToRowExec)
  Stopped after 25 iterations, 2059 ms

OpenJDK 64-Bit Server VM 17.0.18+8-Ubuntu-122.04.1 on Linux 6.8.0-90-generic
AMD Ryzen 9 7950X3D 16-Core Processor
Columnar to Row - Fixed Width Only (no strings):  Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
-------------------------------------------------------------------------------------------------------------------------------
Spark (ColumnarToRowExec)                                   81             85           3         13.0          77.1       1.0X
Comet JVM (CometColumnarToRowExec)                          78             81           3         13.4          74.6       1.0X
Comet Native (CometNativeColumnarToRowExec)                 77             82           9         13.6          73.4       1.0X

Running benchmark: Columnar to Row - Primitive Types
  Running case: Spark (ColumnarToRowExec)
  Stopped after 22 iterations, 2029 ms
  Running case: Comet JVM (CometColumnarToRowExec)
  Stopped after 21 iterations, 2048 ms
  Running case: Comet Native (CometNativeColumnarToRowExec)
  Stopped after 22 iterations, 2019 ms

OpenJDK 64-Bit Server VM 17.0.18+8-Ubuntu-122.04.1 on Linux 6.8.0-90-generic
AMD Ryzen 9 7950X3D 16-Core Processor
Columnar to Row - Primitive Types:           Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
---------------------------------------------------------------------------------------------------------------------------
Spark (ColumnarToRowExec)                               89             92           2         11.8          84.8       1.0X
Comet JVM (CometColumnarToRowExec)                      88             98          11         11.9          84.0       1.0X
Comet Native (CometNativeColumnarToRowExec)             89             92           2         11.8          85.0       1.0X

Running benchmark: Columnar to Row - String Types
  Running case: Spark (ColumnarToRowExec)
  Stopped after 13 iterations, 2012 ms
  Running case: Comet JVM (CometColumnarToRowExec)
  Stopped after 17 iterations, 2034 ms
  Running case: Comet Native (CometNativeColumnarToRowExec)
  Stopped after 15 iterations, 2092 ms

OpenJDK 64-Bit Server VM 17.0.18+8-Ubuntu-122.04.1 on Linux 6.8.0-90-generic
AMD Ryzen 9 7950X3D 16-Core Processor
Columnar to Row - String Types:              Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
---------------------------------------------------------------------------------------------------------------------------
Spark (ColumnarToRowExec)                              153            155           1          6.9         145.5       1.0X
Comet JVM (CometColumnarToRowExec)                     115            120           3          9.1         110.0       1.3X
Comet Native (CometNativeColumnarToRowExec)            136            139           3          7.7         130.0       1.1X

Running benchmark: Columnar to Row - Struct Types
  Running case: Spark (ColumnarToRowExec)
  Stopped after 10 iterations, 2119 ms
  Running case: Comet JVM (CometColumnarToRowExec)
  Stopped after 9 iterations, 2158 ms
  Running case: Comet Native (CometNativeColumnarToRowExec)
  Stopped after 8 iterations, 2248 ms

OpenJDK 64-Bit Server VM 17.0.18+8-Ubuntu-122.04.1 on Linux 6.8.0-90-generic
AMD Ryzen 9 7950X3D 16-Core Processor
Columnar to Row - Struct Types:              Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
---------------------------------------------------------------------------------------------------------------------------
Spark (ColumnarToRowExec)                              203            212          20          5.2         193.2       1.0X
Comet JVM (CometColumnarToRowExec)                     232            240           3          4.5         221.7       0.9X
Comet Native (CometNativeColumnarToRowExec)            267            281          19          3.9         254.9       0.8X

Running benchmark: Columnar to Row - Array Types
  Running case: Spark (ColumnarToRowExec)
  Stopped after 10 iterations, 2018 ms
  Running case: Comet JVM (CometColumnarToRowExec)
  Stopped after 13 iterations, 2063 ms
  Running case: Comet Native (CometNativeColumnarToRowExec)
  Stopped after 11 iterations, 2140 ms

OpenJDK 64-Bit Server VM 17.0.18+8-Ubuntu-122.04.1 on Linux 6.8.0-90-generic
AMD Ryzen 9 7950X3D 16-Core Processor
Columnar to Row - Array Types:               Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
---------------------------------------------------------------------------------------------------------------------------
Spark (ColumnarToRowExec)                              200            202           2          5.2         190.5       1.0X
Comet JVM (CometColumnarToRowExec)                     157            159           3          6.7         149.3       1.3X
Comet Native (CometNativeColumnarToRowExec)            180            195          34          5.8         171.6       1.1X

Running benchmark: Columnar to Row - Map Types
  Running case: Spark (ColumnarToRowExec)
  Stopped after 6 iterations, 2272 ms
  Running case: Comet JVM (CometColumnarToRowExec)
  Stopped after 7 iterations, 2262 ms
  Running case: Comet Native (CometNativeColumnarToRowExec)
  Stopped after 6 iterations, 2102 ms

OpenJDK 64-Bit Server VM 17.0.18+8-Ubuntu-122.04.1 on Linux 6.8.0-90-generic
AMD Ryzen 9 7950X3D 16-Core Processor
Columnar to Row - Map Types:                 Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
---------------------------------------------------------------------------------------------------------------------------
Spark (ColumnarToRowExec)                              371            379           5          2.8         354.2       1.0X
Comet JVM (CometColumnarToRowExec)                     320            323           2          3.3         305.1       1.2X
Comet Native (CometNativeColumnarToRowExec)            332            350          27          3.2         317.1       1.1X

Running benchmark: Columnar to Row - Complex Nested Types
  Running case: Spark (ColumnarToRowExec)
  Stopped after 5 iterations, 2191 ms
  Running case: Comet JVM (CometColumnarToRowExec)
  Stopped after 5 iterations, 2008 ms
  Running case: Comet Native (CometNativeColumnarToRowExec)
  Stopped after 5 iterations, 2331 ms

OpenJDK 64-Bit Server VM 17.0.18+8-Ubuntu-122.04.1 on Linux 6.8.0-90-generic
AMD Ryzen 9 7950X3D 16-Core Processor
Columnar to Row - Complex Nested Types:      Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
---------------------------------------------------------------------------------------------------------------------------
Spark (ColumnarToRowExec)                              434            438           6          2.4         413.9       1.0X
Comet JVM (CometColumnarToRowExec)                     389            402          22          2.7         370.9       1.1X
Comet Native (CometNativeColumnarToRowExec)            444            466          37          2.4         423.6       1.0X

Running benchmark: Columnar to Row - Wide Rows (50 columns)
  Running case: Spark (ColumnarToRowExec)
  Stopped after 3 iterations, 2038 ms
  Running case: Comet JVM (CometColumnarToRowExec)
  Stopped after 4 iterations, 2677 ms
  Running case: Comet Native (CometNativeColumnarToRowExec)
  Stopped after 3 iterations, 2062 ms

OpenJDK 64-Bit Server VM 17.0.18+8-Ubuntu-122.04.1 on Linux 6.8.0-90-generic
AMD Ryzen 9 7950X3D 16-Core Processor
Columnar to Row - Wide Rows (50 columns):    Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
---------------------------------------------------------------------------------------------------------------------------
Spark (ColumnarToRowExec)                              672            680           8          1.6         640.9       1.0X
Comet JVM (CometColumnarToRowExec)                     644            669          21          1.6         614.4       1.0X
Comet Native (CometNativeColumnarToRowExec)            668            687          19          1.6         637.3       1.0X
```

**Comment by schenksj** [comment]
hey @andygrove, would we be open to me iterating on this one a little bit when I get some time?  in my Delta testing this caused some (non-breaking) high-velocity allocation/gc cycles that I bet could be avoided with some sort of reference counting scheme.

**Comment by mbutrovich** [comment]
> hey @andygrove, would we be open to me iterating on this one a little bit when I get some time? in my Delta testing this caused some (non-breaking) high-velocity allocation/gc cycles that I bet could be avoided with some sort of reference counting scheme.

Are you able to measure with native C2R off? This topic came up again in https://github.com/apache/datafusion-comet/issues/4440

**Comment by schenksj** [comment]
> > hey @andygrove, would we be open to me iterating on this one a little bit when I get some time? in my Delta testing this caused some (non-breaking) high-velocity allocation/gc cycles that I bet could be avoided with some sort of reference counting scheme.
> 
> Are you able to measure with native C2R off? This topic came up again in #4440

I didn't explicitly disable it.  I did run some tests with the .copy() removed, and my allocs reduced by 80% and the speed of the specific test I was working though went down by nearly 1/2
