### PR TITLE
fix: null character not permitted in chr function

### LINKED ISSUE #479: bug: null character not permitted in chr function
### Describe the bug

The following query ran without error in Spark but failed in Comet. I discovered this bug using [Comet Fuzz](https://github.com/apache/datafusion-comet/pull/472).

```
SELECT chr(c9),chr(c4) FROM test0
```

```
Query failed in Comet: Job aborted due to stage failure: Task 13 in stage 83.0 failed 1 times, most recent failure: Lost task 13.0 in stage 83.0 (TID 749) (192.168.86.33 executor driver): org.apache.comet.CometNativeException: Execution error: null character not permitted.
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vaibhawvipul**
## Which issue does this PR close?

Closes #479 .

## Rationale for this change

Improves compatibility with apache spark.

## What changes are included in this PR?

Spark compatible implementation of chr scala func.

## How are these changes tested?

New test case added to check null character. All test case pass.

### CODE REVIEW

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 1]
```diff
@@ -980,6 +980,33 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
     }
   }
 
+  test("Chr with null character") {
+    // test compatibility with Spark, spark supports chr(0)
+    Seq(false, true).foreach { dictionary =>
+      withSQLConf(
+        "parquet.enable.dictionary" -> dictionary.toString,
+        SQLConf.ANSI_ENABLED.key -> "true",
+        CometConf.COMET_ANSI_MODE_ENABLED.key -> "true",
```
Comment (kazuyukitanimura) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:989]: Wondering if ANSI is related to this change...

File: core/src/execution/datafusion/expressions/scalar_funcs.rs [hunk 2]
```diff
@@ -130,6 +133,10 @@ pub fn create_comet_physical_fun(
             let func = Arc::new(spark_xxhash64);
             make_comet_scalar_udf!("xxhash64", func, without data_type)
         }
+        "chr" => {
```
Comment (kazuyukitanimura) [inline core/src/execution/datafusion/expressions/scalar_funcs.rs:136]: Is the expected behavior returning null if the input is null?
Another approach could be converting `chr(child)` to `If(IsNull(child), literalNull, chr(child))` to reuse existing `chr`

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala (hunk 1 above)
Comment (vaibhawvipul) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala]: not required, removed ANSI configs.

File: core/src/execution/datafusion/expressions/scalar_funcs.rs (hunk 2 above)
Comment (vaibhawvipul) [reply core/src/execution/datafusion/expressions/scalar_funcs.rs:136]: Question - 
 IsNull(child) won't work because we have an element there - 0 (int). Hence we will hit chr(Child) always. Is my understanding correct?

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 3]
```diff
@@ -980,6 +980,29 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+  test("Chr with null character") {
+    // test compatibility with Spark, spark supports chr(0)
+    Seq(false, true).foreach { dictionary =>
+      withSQLConf(
+        "parquet.enable.dictionary" -> dictionary.toString,
+        CometConf.COMET_CAST_ALLOW_INCOMPATIBLE.key -> "true") {
+        val table = "test0"
+        withTable(table) {
+          sql(s"create table $table(c9 int, c4 int) using parquet")
+          sql(s"insert into $table values(0, 0), (66, null), (null, 70), (null, null)")
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:992]: I'd like to see a wider range of values being tested here such as large numbers and negative numbers

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 4]
```diff
@@ -980,6 +980,29 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+          val query = s"SELECT chr(c9), chr(c4) FROM $table"
+          checkSparkMaybeThrows(sql(query)) match {
+            case (None, None) => {}
+            case (Some(e), None) => throw e
+            case (None, Some(e)) => throw e
+            case (Some(e1), Some(e2)) => throw new Exception(s"$e1, $e2")
+          }
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:999]: This seems redundant? You already call `checkSparkAnswerAndOperator` and we do not expect any exceptions to be thrown for the input values.

Comment (vaibhawvipul) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala]: +1 , removed `checkSparkMaybeThrows`.

File: core/src/execution/datafusion/expressions/scalar_funcs.rs (hunk 2 above)
Comment (andygrove) [reply core/src/execution/datafusion/expressions/scalar_funcs.rs:136]: @kazuyukitanimura The null handling was already correct. The issue was specifically for the input value zero.

Comment (andygrove) [reply core/src/execution/datafusion/expressions/scalar_funcs.rs:136]: I suppose it would be possible to build an `If(child == lit(0), lit("0"), chr(child))` but seems like that would add more runtime overhead and complexity

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @vaibhawvipul. I will plan on merging this early next week if there is no other feedback.

File: core/src/execution/datafusion/expressions/scalar_funcs/chr.rs [hunk 5]
```diff
@@ -0,0 +1,108 @@
...
+    fn invoke(&self, args: &[ColumnarValue]) -> Result<ColumnarValue> {
+        let array = args[0].clone();
+        match array {
+            ColumnarValue::Array(array) => {
+                let array = chr(&[array])?;
+                Ok(ColumnarValue::Array(array))
+            }
+            _ => {
+                exec_err!("The first argument must be an array, but got: {:?}", array)
+            }
```
Comment (kazuyukitanimura) [inline core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:105]: Is handling only Array correct?
It looks DataFusion is using `make_scalar_function`

File: core/src/execution/datafusion/expressions/scalar_funcs.rs (hunk 2 above)
Comment (kazuyukitanimura) [reply core/src/execution/datafusion/expressions/scalar_funcs.rs:136]: Got it, makes sense

File: core/src/execution/datafusion/expressions/scalar_funcs/chr.rs [hunk 6]
```diff
@@ -0,0 +1,108 @@
...
+        DataType::{Int64, Utf8},
+    },
+};
+
+use datafusion::logical_expr::{ColumnarValue, ScalarUDFImpl, Signature, Volatility};
+use datafusion_common::{cast::as_int64_array, exec_err, DataFusionError, Result};
+
+/// chr(65) = 'A'
+
+// Compatible with Apache Spark's Chr function
```
Comment (viirya) [inline core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:33]:
```suggestion
/// Returns the ASCII character having the binary equivalent to the input expression.
/// E.g., chr(65) = 'A'.
/// Compatible with Apache Spark's Chr function
```

File: core/src/execution/datafusion/expressions/scalar_funcs/chr.rs (hunk 5 above)
Comment (viirya) [reply core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:105]: We may need to handle `ColumnarValue::Scalar` too.

File: core/src/execution/datafusion/expressions/scalar_funcs/chr.rs [hunk 7]
```diff
@@ -94,15 +94,43 @@ impl ScalarUDFImpl for ChrFunc {
...
+}
+
+/// The make_scalar_function function is a higher-order function that:
+/// - Takes a function inner designed to operate on arrays.
+/// - Wraps this function in a closure that can accept a mix of scalar and array inputs.
+/// - Converts scalar inputs to arrays, calls the inner function, and then converts the result back to a scalar if the original inputs were all scalars.
+/// 
+/// taken from datafusion utils
+
+fn make_scalar_function<F>(inner: F) -> impl Fn(&[ColumnarValue]) -> Result<ColumnarValue>
```
Comment (viirya) [inline core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:109]: Hmm, as Spark `Chr` expression has only one argument. It is either a `ColumnarValue::Array` or a `ColumnarValue::Scalar`. We don't need to make it complicated like this.

We can do simply:

```rust
let array = args[0].clone();
match array {
    ColumnarValue::Array(array) => {
        let array = chr(&[array])?;
        Ok(ColumnarValue::Array(array))
    }
    ColumnarValue::Scalar(Utf8(Some(_))) => {
        let values = array.into_array(1);
        let array = chr(&[array])?;
        Ok(ColumnarValue::Scalar(Utf8(Some(array.value(0).to_string()))))
    }
    ColumnarValue::Scalar(Utf8(None)) => {
        Ok(ColumnarValue::Scalar(Utf8(None)))
    }
    _ => {
        ...
    }
```

Comment (vaibhawvipul) [reply core/src/execution/datafusion/expressions/scalar_funcs/chr.rs]: +1 , fixed it. Now the function is way simple. Thanks.

File: core/src/execution/datafusion/expressions/scalar_funcs/chr.rs [hunk 8]
```diff
@@ -0,0 +1,119 @@
...
+
+pub fn chr(args: &[ArrayRef]) -> Result<ArrayRef> {
+    let integer_array = as_int64_array(&args[0])?;
+
+    // first map is the iterator, second is for the `Option<_>`
+    let result = integer_array
+        .iter()
+        .map(|integer: Option<i64>| {
+            integer
+                .map(|integer| match core::char::from_u32(integer as u32) {
```
Comment (viirya) [inline core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:47]: Spark `Chr` expression has the behavior:

1. If input < 0, return empty char.
2. If input % 0xFF == 0, return `'\u0000'`.
3. Otherwise, return `input & 0xFF` as char.

Does `core::char::from_u32` follow all these behaviors?

Comment (viirya) [reply core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:47]: Seems this is for the issue of null char, it is okay to fix it in follow up.

Comment (vaibhawvipul) [reply core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:47]: Yes i am tracking that, #480 is the one I will work on next. That one handles the cases you mentioned above!

**Review by viirya — APPROVED** [review]
