### PR TITLE
fix: CometScanExec on Spark 3.5.2

### LINKED ISSUE #912: CometScanExec fails on Spark 3.5.2
### Describe the bug

Trying to use `CometScanExec` with Spark 3.5.2 results in a runtime exception.

### Steps to reproduce

Class not found error at runtime, but can also be replicated by trying to compile Comet with Spark 3.5.2:
```
[ERROR] /Users/abinford/projects/arrow-datafusion-comet/spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala:144: value OP_ID_TAG is not a member of object org.apache.spark.sql.catalyst.plans.QueryPlan
```

### Expected behavior

Compilation and runtime succeed

### Additional context

This is due to https://github.com/apache/spark/commit/88582e11519b18549b6ed19868e1749963a5299e which removed `OP_ID_TAG` and uses a different mechanism to track operator IDs.

### PR DESCRIPTION
**Pull request by Kimahriman**
## Which issue does this PR close?

Closes #912 

## Rationale for this change

Fixes CometScanExec running on Spark 3.5.2+. Currently it will fail with a runtime exception, and will fail to compile if specifying 3.5.2 with

```
[ERROR] /Users/abinford/projects/arrow-datafusion-comet/spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala:144: value OP_ID_TAG is not a member of object org.apache.spark.sql.catalyst.plans.QueryPlan
```

This is because `OP_ID_TAG` is removed in Spark 3.5.2+, and the operator ID tracking is replaced with a separate internal map of plan -> ID, so there's no way to manually pass the ID on to a delegating plan. Instead simply copies the implementation of `DataSourceScanExec`'s method.

## What changes are included in this PR?

The only effect of the change is the verbose string output for CometScanExec. Instead of delegating to the underlying DataSourceScanExec, just copied the implementation over. This is in line with other Comet operators that implement their own verbose string, and makes more sense in the formatted explain as the operator names line up.

Before:
```
== Physical Plan ==
* ColumnarToRow (2)
+- CometScan parquet  (1)


(1) Scan parquet 
Output [20]: [_1#146, _2#147, _3#148, _4#149, _5#150L, _6#151, _7#152, _8#153, _9#154, _10#155, _11#156L, _12#157, _13#158, _14#159, _15#160, _16#161, _17#162, _18#163, _19#164, _20#165]
Batched: true
Location: InMemoryFileIndex [file:.../arrow-datafusion-comet/spark/target/tmp/spark-a0b56a3c-caa2-4631-ad15-ec83e8522948/test.parquet]
ReadSchema: struct<_1:boolean,_2:tinyint,_3:smallint,_4:int,_5:bigint,_6:float,_7:double,_8:string,_9:smallint,_10:int,_11:bigint,_12:decimal(20,0),_13:string,_14:binary,_15:decimal(5,2),_16:decimal(18,10),_17:decimal(38,37),_18:timestamp,_19:timestamp,_20:date>

(2) ColumnarToRow [codegen id : 1]
Input [20]: [_1#146, _2#147, _3#148, _4#149, _5#150L, _6#151, _7#152, _8#153, _9#154, _10#155, _11#156L, _12#157, _13#158, _14#159, _15#160, _16#161, _17#162, _18#163, _19#164, _20#165]
```

After:
```
== Physical Plan ==
* ColumnarToRow (2)
+- CometScan parquet  (1)


(1) CometScan parquet 
Output [20]: [_1#146, _2#147, _3#148, _4#149, _5#150L, _6#151, _7#152, _8#153, _9#154, _10#155, _11#156L, _12#157, _13#158, _14#159, _15#160, _16#161, _17#162, _18#163, _19#164, _20#165]
Batched: true
Location: InMemoryFileIndex [file:.../arrow-datafusion-comet/spark/target/tmp/spark-36667e9a-75e0-4f90-8442-5f47ecd1cf4b/test.parquet]
ReadSchema: struct<_1:boolean,_2:tinyint,_3:smallint,_4:int,_5:bigint,_6:float,_7:double,_8:string,_9:smallint,_10:int,_11:bigint,_12:decimal(20,0),_13:string,_14:binary,_15:decimal(5,2),_16:decimal(18,10),_17:decimal(38,37),_18:timestamp,_19:timestamp,_20:date>

(2) ColumnarToRow [codegen id : 1]
Input [20]: [_1#146, _2#147, _3#148, _4#149, _5#150L, _6#151, _7#152, _8#153, _9#154, _10#155, _11#156L, _12#157, _13#158, _14#159, _15#160, _16#161, _17#162, _18#163, _19#164, _20#165]
```

## How are these changes tested?
Manually verified by building with Spark 3.5.2 `./mvnw clean package -Pspark-3.5 -Dspark.version=3.5.2 -DskipTests`.

### CODE REVIEW

**Comment by Kimahriman** [comment]
Oof this breaks a lot of explain plan comparison tests. If this change is ok I can try to work on updating them

**Comment by kazuyukitanimura** [comment]
Is the change in the `metadata`? If so, should we fix the metadata instead?

**Comment by kazuyukitanimura** [comment]
And perhaps we can try to upgrade the Comet dependency to Spark 3.5.2

**Comment by Kimahriman** [comment]
> Is the change in the `metadata`? If so, should we fix the metadata instead?

Are you referring to the compilation error or the change in explain output?

> And perhaps we can try to upgrade the Comet dependency to Spark 3.5.2 (separately)

Agreed. I thought about doing that here but I wasn't sure the best way to go about updating the diff for the Spark SQL tests

**Comment by kazuyukitanimura** [comment]
> > Is the change in the `metadata`? If so, should we fix the metadata instead?
> 
> Are you referring to the compilation error or the change in explain output?

I meant `CometScanExec. metadata` inherited from `DataSourceScanExec`

File: spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala [hunk 1]
```diff
@@ -141,8 +141,30 @@ case class CometScanExec(
     if (wrapped == null) Map.empty else wrapped.metadata
 
   override def verboseStringWithOperatorId(): String = {
-    getTagValue(QueryPlan.OP_ID_TAG).foreach(id => wrapped.setTagValue(QueryPlan.OP_ID_TAG, id))
-    wrapped.verboseStringWithOperatorId()
+    val metadataStr = metadata.toSeq.sorted
```
Comment (parthchandra) [inline spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala:144]: Since the original issue was that `OP_ID_TAG` has been removed, is it not sufficient to just remove the offending line

Comment (Kimahriman) [reply spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala:144]: Just removing setting the `OP_ID_TAG` leads to a formatted explain of:

```
== Physical Plan ==
* ColumnarToRow (2)
+- CometScan parquet  (1)


(unknown) Scan parquet 
Output [20]: [_1#0, _2#1, _3#2, _4#3, _5#4L, _6#5, _7#6, _8#7, _9#8, _10#9, _11#10L, _12#11, _13#12, _14#13, _15#14, _16#15, _17#16, _18#17, _19#18, _20#19]
Batched: true
Location: InMemoryFileIndex [file:/Users/abinford/projects/arrow-datafusion-comet/spark/target/tmp/spark-c0b82b7c-3de1-431b-96bf-56cb37f3a463/test.parquet]
ReadSchema: struct<_1:boolean,_2:tinyint,_3:smallint,_4:int,_5:bigint,_6:float,_7:double,_8:string,_9:smallint,_10:int,_11:bigint,_12:decimal(20,0),_13:string,_14:binary,_15:decimal(5,2),_16:decimal(18,10),_17:decimal(38,37),_18:timestamp,_19:timestamp,_20:date>

(2) ColumnarToRow [codegen id : 1]
Input [20]: [_1#0, _2#1, _3#2, _4#3, _5#4L, _6#5, _7#6, _8#7, _9#8, _10#9, _11#10L, _12#11, _13#12, _14#13, _15#14, _16#15, _17#16, _18#17, _19#18, _20#19]
```

which is the whole reason it was added in the first place, to fix the unknown operator ID https://github.com/apache/datafusion-comet/commit/bc35fa5a415f4a137177ab4fc66bd0167f9f23d3

Comment (Kimahriman) [reply spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala:144]: Plus by what I could see, every other operator is prefixed with `Comet` in the formatted explain, so it's weird for Scan to be the one thing that doesn't actually match up to the physical plan

Comment (parthchandra) [reply spark/src/main/scala/org/apache/spark/sql/comet/CometScanExec.scala:144]: I see, that makes sense.
On an unrelated note, wonder why `CometScanExec` extends `DataSourceScanExec` instead of `FileSourceScanExec` (if it had we would have got the verboseString for free)

**Review by parthchandra — APPROVED** [review]
lgtm

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @Kimahriman

**Comment by andygrove** [comment]
@Kimahriman would you be able to rebase this PR so that we can merge it?

**Comment by Kimahriman** [comment]
> @Kimahriman would you be able to rebase this PR so that we can merge it?

Oof 95 conflicts I would have to manually resolve, let me just regenerate these plans all again tonight

**Comment by Kimahriman** [comment]
Ok wasn't too bad to find/replace fix the issues again, we'll see if I messed anything up in the CI

**Comment by Kimahriman** [comment]
Done, I think CI failures are unrelated, looks like failures downloading dependencies in Hive tests

**Comment by andygrove** [comment]
> Done, I think CI failures are unrelated, looks like failures downloading dependencies in Hive tests

Thanks. I am re-running the failed jobs now.
