### PR TITLE
fix: Check sort order of SortExec instead of child output

### LINKED ISSUE #822: Check sort order of SortExec instead of child output
### Describe the bug

In #811, I checked the output of SortExec's child, but it should be sort order of SortExec.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #822.

### CODE REVIEW

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 1]
```diff
@@ -2501,10 +2501,7 @@ object QueryPlanSerde extends Logging with ShimQueryPlanSerde with CometExprShim
 
       case SortExec(sortOrder, _, child, _)
           if isCometOperatorEnabled(op.conf, CometConf.OPERATOR_SORT) =>
-        // TODO: Remove this constraint when we upgrade to new arrow-rs including
-        // https://github.com/apache/arrow-rs/pull/6225
-        if (child.output.length == 1 && child.output.head.dataType.isInstanceOf[StructType]) {
```
Comment (viirya) [inline spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:2506]: It should be the column to sort (i.e., sort order) instead of child output. I made it wrong in #811.

File: spark/src/main/scala/org/apache/spark/sql/comet/CometTakeOrderedAndProjectExec.scala [hunk 2]
```diff
@@ -137,6 +138,6 @@ object CometTakeOrderedAndProjectExec extends ShimCometTakeOrderedAndProjectExec
     val exprs = plan.projectList.map(exprToProto(_, plan.child.output))
     val sortOrders = plan.sortOrder.map(exprToProto(_, plan.child.output))
     exprs.forall(_.isDefined) && sortOrders.forall(_.isDefined) && getOffset(plan).getOrElse(
-      0) == 0
+      0) == 0 && supportedSortType(plan, plan.sortOrder)
```
Comment (viirya) [inline spark/src/main/scala/org/apache/spark/sql/comet/CometTakeOrderedAndProjectExec.scala:141]: `CometTakeOrderedAndProjectExec` will invoke DataFusion `SortExec` operator, so we should also check for it.

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 3]
```diff
@@ -3053,4 +3050,15 @@ object QueryPlanSerde extends Logging with ShimQueryPlanSerde with CometExprShim
     }
 
   }
+
+  // TODO: Remove this constraint when we upgrade to new arrow-rs including
+  // https://github.com/apache/arrow-rs/pull/6225
+  def supportedSortType(op: SparkPlan, sortOrder: Seq[SortOrder]): Boolean = {
+    if (sortOrder.length == 1 && sortOrder.head.dataType.isInstanceOf[StructType]) {
+      withInfo(op, "Sort on single struct column is not supported")
```
Comment (viirya) [inline spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:3058]: As @andygrove mentioned in #811, there are some more types that are not supported. I will add them in other PR.

**Review by andygrove — APPROVED** [review]

**Review by huaxingao — APPROVED** [review]
