### PR TITLE
fix: Mark SortOrder with floating-point as incompatible

### LINKED ISSUE #2626: Sorting on floating point with negative zero incompatible with Spark
### Describe the bug

This may be a duplicate issue, but sorting is inconsistent for zero vs negative zero in Comet and this prevents us from fuzz testing against data containing negative zero

### Steps to reproduce

```sql
SELECT floating_point_col FROM foo ORDER BY floating_point_col
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andygrove**
## Which issue does this PR close?

Closes https://github.com/apache/datafusion-comet/issues/2626

## Rationale for this change

Fall back to Spark by default when sorting on floating-point values. Users can opt in if they don't care about the different handling of +0.0 vs -0.0.

## What changes are included in this PR?

- [x] Refactor serde for `SortOrder`
- [x] Add specific tests
- [x] Write documentation (compatibility and tuning guide)

### CODE REVIEW

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 1]
```diff
@@ -60,6 +61,70 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+      spark,
+      schema,
+      1000,
+      DataGenOptions(generateNegativeZero = true))
+    df.createOrReplaceTempView("tbl")
+
+    withSQLConf(CometConf.getExprAllowIncompatConfigKey("SortOrder") -> "false") {
+      checkSparkAnswerAndFallbackReason(
+        "select * from tbl order by 1, 2",
+        "unsupported range partitioning sort order")
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:80]: I filed a follow-up issue for improving the fallback reason to show the root cause

https://github.com/apache/datafusion-comet/issues/2651

File: spark/src/main/scala/org/apache/comet/serde/CometSort.scala [hunk 2]
```diff
@@ -21,12 +21,70 @@ package org.apache.comet.serde
...
 import org.apache.comet.CometSparkSessionExtensions.withInfo
 import org.apache.comet.serde.OperatorOuterClass.Operator
-import org.apache.comet.serde.QueryPlanSerde.{exprToProto, supportedSortType}
+import org.apache.comet.serde.QueryPlanSerde.{exprToProto, exprToProtoInternal, supportedSortType}
+
+object CometSortOrder extends CometExpressionSerde[SortOrder] {
+
+  override def getSupportLevel(expr: SortOrder): SupportLevel = {
+
+    def containsFloatingPoint(dt: DataType): Boolean = {
```
Comment (comphead) [inline spark/src/main/scala/org/apache/comet/serde/CometSort.scala:37]:
```suggestion
    def dataTypeContainsFloatingPoint(dt: DataType): Boolean = {
```

**Review by comphead — APPROVED** [review]
Thanks @andygrove it is lgtm, just a small suggestion on naming

**Review by mbutrovich — APPROVED** [review]
I'll probably continue to grumble about what "incompatible" means but this LGTM. Thanks @andygrove!

File: spark/src/main/scala/org/apache/comet/serde/CometSort.scala (hunk 2 above)
Comment (andygrove) [reply spark/src/main/scala/org/apache/comet/serde/CometSort.scala:37]: The method takes a `DataType` parameter, so it seems redundant to include that in the method name as well?
