### PR TITLE
fix: requested character too large for encoding in chr function

### LINKED ISSUE #480: bug: requested character too large for encoding in chr function
### Describe the bug

The following query ran without error in Spark but failed in Comet. I discovered this bug using [Comet Fuzz](https://github.com/apache/datafusion-comet/pull/472).

```
SELECT chr(c8) FROM test0
```

```
Query failed in Comet: Job aborted due to stage failure: Task 12 in stage 97.0 failed 1 times, most recent failure: Lost task 12.0 in stage 97.0 (TID 878) (192.168.86.33 executor driver): org.apache.comet.CometNativeException: Execution error: requested character too large for encoding.
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vaibhawvipul**
## Which issue does this PR close?

Closes #480 .

## Rationale for this change

improves compatibility with spark

## What changes are included in this PR?

- added support for negative integers while encoding
- also added support for integers larger than 256

## How are these changes tested?

Test cases added, all the existing tests pass.

### CODE REVIEW

**Comment by vaibhawvipul** [comment]
@andygrove this is ready for review.

File: core/src/execution/datafusion/expressions/scalar_funcs/chr.rs [hunk 1]
```diff
@@ -110,7 +118,7 @@ fn handle_chr_fn(args: &[ColumnarValue]) -> Result<ColumnarValue> {
                 Some(ch) => Ok(ColumnarValue::Scalar(ScalarValue::Utf8(Some(
                     ch.to_string(),
                 )))),
-                None => exec_err!("requested character too large for encoding."),
+                None => exec_err!("requested character was incompatible for encoding."),
```
Comment (andygrove) [inline core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:121]: We don't have the checks for negative integers in the scalar path. I wonder if this code path is even possible to reach since Spark will likely evaluate `chr(scalar)` during planning and replace it with a literal value before the physical planning stage, so Comet would never see this case.

File: core/src/execution/datafusion/expressions/scalar_funcs/chr.rs [hunk 2]
```diff
@@ -44,10 +44,18 @@ pub fn chr(args: &[ArrayRef]) -> Result<ArrayRef> {
...
             integer
-                .map(|integer| match core::char::from_u32(integer as u32) {
-                    Some(integer) => Ok(integer.to_string()),
-                    None => {
-                        exec_err!("requested character too large for encoding.")
+                .map(|integer| {
+                    let adjusted_integer = if integer >= 0 { integer % 256 } else { integer };
+
+                    match core::char::from_u32(adjusted_integer as u32) {
+                        Some(integer) => Ok(integer.to_string()),
```
Comment (andygrove) [inline core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:51]:
```suggestion
                        Some(ch) => Ok(ch.to_string()),
```

File: core/src/execution/datafusion/expressions/scalar_funcs/chr.rs [hunk 3]
```diff
@@ -44,10 +44,18 @@ pub fn chr(args: &[ArrayRef]) -> Result<ArrayRef> {
...
+                        None => {
+                            if integer < 0 {
```
Comment (andygrove) [inline core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:53]: nit: could you check for negative integers earlier, before calling `core::char::from_u32(adjusted_integer as u32)`. If the input is a negative number then we should not attempt to convert to a char.

File: core/src/execution/datafusion/expressions/scalar_funcs/chr.rs (hunk 1 above)
Comment (vaibhawvipul) [reply core/src/execution/datafusion/expressions/scalar_funcs/chr.rs]: Added a test for scalar values to verify the corresponding code paths and removed the cases that were unreachable.

File: core/src/execution/datafusion/expressions/scalar_funcs/chr.rs [hunk 4]
```diff
@@ -44,10 +44,16 @@ pub fn chr(args: &[ArrayRef]) -> Result<ArrayRef> {
...
-                .map(|integer| match core::char::from_u32(integer as u32) {
-                    Some(integer) => Ok(integer.to_string()),
-                    None => {
-                        exec_err!("requested character too large for encoding.")
+                .map(|integer| {
+                    if integer < 0 {
+                        return Ok("".to_string()); // Return empty string for negative integers
+                    }
+                    let adjusted_integer = if integer >= 0 { integer % 256 } else { integer };
+                    match core::char::from_u32(adjusted_integer as u32) {
```
Comment (andygrove) [inline core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:52]: nit: I think you can make the same optimization here that you did for the scalar case

```suggestion
                    match core::char::from_u32((integer % 256) as u32) {
```

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @vaibhawvipul

File: core/src/execution/datafusion/expressions/scalar_funcs/chr.rs [hunk 5]
```diff
@@ -44,10 +44,15 @@ pub fn chr(args: &[ArrayRef]) -> Result<ArrayRef> {
         .iter()
         .map(|integer: Option<i64>| {
             integer
-                .map(|integer| match core::char::from_u32(integer as u32) {
-                    Some(integer) => Ok(integer.to_string()),
-                    None => {
-                        exec_err!("requested character too large for encoding.")
+                .map(|integer| {
+                    if integer < 0 {
```
Comment (parthchandra) [inline core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:48]: @andygrove can we use `unlikely` (requires nightly) to indicate a less likely branch

Comment (viirya) [reply core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:48]: I thought we are moving to stable?

File: core/src/execution/datafusion/expressions/scalar_funcs/chr.rs [hunk 6]
```diff
@@ -44,10 +44,15 @@ pub fn chr(args: &[ArrayRef]) -> Result<ArrayRef> {
...
+                        return Ok("".to_string()); // Return empty string for negative integers
+                    }
+                    match core::char::from_u32((integer % 256) as u32) {
```
[the remark this answers is not in the document]
Comment (viirya) [reply core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:51]: We probably need to add a test case for it.

[the remark this answers is not in the document]
Comment (vaibhawvipul) [reply core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:51]: hey @viirya, thank you for the review. 

char::from_u32 internally uses - 

```
const fn char_try_from_u32(i: u32) -> Result<char, CharTryFromError> {
    // This is an optimized version of the check
    // (i > MAX as u32) || (i >= 0xD800 && i <= 0xDFFF),
    // which can also be written as
    // i >= 0x110000 || (i >= 0xD800 && i < 0xE000).
    //
    // The XOR with 0xD800 permutes the ranges such that 0xD800..0xE000 is
    // mapped to 0x0000..0x0800, while keeping all the high bits outside 0xFFFF the same.
    // In particular, numbers >= 0x110000 stay in this range.
    //
    // Subtracting 0x800 causes 0x0000..0x0800 to wrap, meaning that a single
    // unsigned comparison against 0x110000 - 0x800 will detect both the wrapped
    // surrogate range as well as the numbers originally larger than 0x110000.
    //
    if (i ^ 0xD800).wrapping_sub(0x800) >= 0x110000 - 0x800 {
        Err(CharTryFromError(()))
    } else {
        // SAFETY: checked that it's a legal unicode value
        Ok(unsafe { transmute(i) })
    }
}
```

This returns unicode `'\0'` which is equivalent to Character. MIN_VALUE. 

Hence the implementation has same behaviour, as far as i understand.

[the remark this answers is not in the document]
Comment (vaibhawvipul) [reply core/src/execution/datafusion/expressions/scalar_funcs/chr.rs:51]: https://github.com/apache/datafusion-comet/pull/552#discussion_r1637622187

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 7]
```diff
@@ -1053,6 +1053,32 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+  test("Chr with negative and large value") {
+    Seq(false, true).foreach { dictionary =>
+      withSQLConf(
+        "parquet.enable.dictionary" -> dictionary.toString,
+        CometConf.COMET_CAST_ALLOW_INCOMPATIBLE.key -> "true") {
+        val table = "test0"
+        withTable(table) {
+          sql(s"create table $table(c9 int, c4 int) using parquet")
+          sql(
+            s"insert into $table values(0, 0), (61231, -61231), (-1700, 1700), (0, -4000), (-40, 40)")
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1065]: Let's add a test for the case where `integer & 0xFF == 0` since that is not currently covered (other than with the value 0).

```suggestion
            s"insert into $table values(0, 0), (61231, -61231), (-1700, 1700), (0, -4000), (-40, 40), {256, 512)")
```

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 8]
```diff
@@ -1053,6 +1053,32 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
     }
   }
 
+  test("Chr with negative and large value") {
+    Seq(false, true).foreach { dictionary =>
+      withSQLConf(
+        "parquet.enable.dictionary" -> dictionary.toString,
+        CometConf.COMET_CAST_ALLOW_INCOMPATIBLE.key -> "true") {
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1060]: I don't think that this test relies on any incompatible cast operations, so we can remove this config.

```suggestion
        "parquet.enable.dictionary" -> dictionary.toString) {
```

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala (hunk 7 above)
Comment (vaibhawvipul) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala]: added the test case.

**Review by andygrove — APPROVED** [review]
Thanks @vaibhawvipul. I think this addresses the feedback from @viirya so I will plan on merging this soon if there is no other feedback.

**Review by viirya — APPROVED** [review]

**Comment by viirya** [comment]
Thanks @vaibhawvipul
