### PR TITLE
fix: Fall back to `native_comet` when object store not supported by `native_iceberg_compat`

### LINKED ISSUE #2248: `auto` scan mode should not select `native_iceberg_compat` when there is an unsupported credential provider
### Describe the bug

`auto` scan mode should not select `native_iceberg_compat` when there is an unsupported credential provider.

Currently, we have no checks in `CometScanRule` to determine which credential provider, if any, will be used.

At runtime, `native_iceberg_compat` on the Scala side will call `org.apache.comet.objectstore.NativeConfig.extractObjectStoreOptions` to create a config `HashMap` that is passed into native code in `org.apache.comet.parquet.Native#initRecordBatchReader`. The native code calls `prepare_object_store_with_configs` which eventually calls `build_chained_aws_credential_provider_metadata` in the S3 case and this is where the logic is that determines whether the credential provider is supported.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andygrove**
## Which issue does this PR close?

Closes https://github.com/apache/datafusion-comet/issues/2248

## Rationale for this change

Check that S3 object store configs are valid at planning time rather than at execution time. Fall back to `native_comet` if object store configs are not valid for `native_iceberg_compat`.

### CODE REVIEW

**Comment by andygrove** [comment]
@Kontinuation fyi

File: native/core/src/parquet/mod.rs [hunk 1]
```diff
@@ -686,9 +715,9 @@ pub unsafe extern "system" fn Java_org_apache_comet_parquet_Native_initRecordBat
 ) -> jlong {
     try_unwrap_or_throw(&e, |mut env| unsafe {
         let session_config = SessionConfig::new().with_batch_size(batch_size as usize);
-        let planer =
+        let planner =
```
Comment (comphead) [inline native/core/src/parquet/mod.rs:718]: 👍

File: spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala [hunk 2]
```diff
@@ -288,8 +292,25 @@ case class CometScanRule(session: SparkSession) extends Rule[SparkPlan] with Com
     val fallbackReasons = new ListBuffer[String]()
 
     // native_iceberg_compat only supports local filesystem and S3
```
Comment (comphead) [inline spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala:297]: it seems the code doesn't support local filesystem anymore?

Comment (andygrove) [reply spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala:297]: No, the only change is that now we have additional checks for the s3 case.

It might not be clear from the diff, but the code changed from:

```
if (!local_filesystem_or_s3) {
  // fallback
}
```

to

```
if (local_filesystem_or_s3) {
  // additional checks
} else {
  // fallback
}
```

**Review by parthchandra — APPROVED** [review]
lgtm. I only wonder if this will end up making a bunch of S3 calls every time ScanRule is called (but perhaps for the time being this is ok until we address this better).

**Comment by andygrove** [comment]
> lgtm. I only wonder if this will end up making a bunch of S3 calls every time ScanRule is called (but perhaps for the time being this is ok until we address this better).

That is a great point. Let me see if there is a way to cache this so we don't keep re-validating the same config every time the rule runs.

File: spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala [hunk 3]
```diff
@@ -372,3 +388,64 @@ case class CometScanTypeChecker(scanImpl: String) extends DataTypeSupport with C
...
+
+    val cacheKey = objectStoreConfigMap
+      .map { case (k, v) =>
+        s"$k=$v"
+      }
+      .toList
+      .sorted
+      .mkString("\n")
+
+    if (configValidityMap.size >= configValidityMapMaxSize) {
```
Comment (parthchandra) [inline spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala:425]: I don't know if this is sufficient. The user may have changed the credentials provider class for instance. 
However, it is unlikely that this would happen in the middle of a session so I'm fine if you don't want to change this.

Comment (Kontinuation) [reply spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala:425]: AFAIK, Spark will reuse the same Hadoop FileSystem object for each URL scheme (bucket in case of S3). The Hadoop configuration will only be applied once when the bucket is first accessed. Further changes to Hadoop filesystem configurations won't be effective.

Using only the bucket name as the cache key should be sufficient according to the behavior (or implementation detail) of Spark, but I think the current more strict approach is better.
