### PR TITLE
fix: support `map_keys`

### LINKED ISSUE #1781: Make map_keys to work with projection
> Thanks @parthchandra
> 
> however I feel we need to add some more later. the test passed because
> 
> ```
>           checkSparkAnswer(spark.sql("SELECT map_keys(map1).id2 FROM tbl"))
> ```
> 
> and will prob fail for
> 
> ```
>           checkSparkAnswerAndOperator(spark.sql("SELECT map_keys(map1).id2 FROM tbl"))
> ```

Good point @comphead .

The test cannot use `checkSparkAnswerAndOperator` atm but should eventually.
The plan is not fully native for two reasons - 
native_datafusion and native_iceberg_compat do not support DSV2 so the Scan falls back to Spark 
with DSV2 the plan is
```
plan: *(1) Project [map_keys(map1#12).id2 AS map_keys(map1).id2#54]
+- *(1) ColumnarToRow
   +- BatchScan parquet file:/private/var/folders/bz/gg_fqnmj4c17j2c7mdn8ps1m0000gn/T/spark-e0fd616e-7fdc-4d0a-be8a-e6453797e243[map1#12] ParquetScan DataFilters: [], Format: parquet, Location: InMemoryFileIndex(1 paths)[file:/private/var/folders/bz/gg_fqnmj4c17j2c7mdn8ps1m0000gn/T/spark-e0..., PartitionFilters: [], PushedAggregation: [], PushedFilters: [], PushedGroupBy: [], ReadSchema: struct<map1:map<struct<id2:bigint>,struct<id:bigint,id2:bigint,id3:bigint>>> RuntimeFilters: []
```

with DSV1 sources, the scan is Native but the Project is not. 
```
plan: *(1) Project [map_keys(map1#82).id2 AS map_keys(map1).id2#118]
+- *(1) CometColumnarToRow
   +- CometNativeScan parquet [map1#82] Batched: true, DataFilters: [], Format: CometParquet, Location: InMemoryFileIndex(1 paths)[file:/private/var/folders/bz/gg_fqnmj4c17j2c7mdn8ps1m0000gn/T/spark-d0..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<map1:map<struct<id2:bigint>,struct<id:bigint,id2:bigint,id3:bigint>>>

```

_Originally posted by @parthchandra in https://github.com/apache/datafusion-comet/issues/1771#issuecomment-2902868329_

### PR DESCRIPTION
**Pull request by comphead**
## Which issue does this PR close?

Closes #1781.

### CODE REVIEW

**Comment by comphead** [comment]
`map_values` will be addressed in following PR. It got a correctness issue

```
- read map[struct, struct] from parquet *** FAILED *** (1 second, 478 milliseconds)
  Results do not match for query:
  Timezone: sun.util.calendar.ZoneInfo[id="America/Los_Angeles",offset=-28800000,dstSavings=3600000,useDaylight=true,transitions=185,lastRule=java.util.SimpleTimeZone[id=America/Los_Angeles,offset=-28800000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=3,startMonth=2,startDay=8,startDayOfWeek=1,startTime=7200000,startTimeMode=0,endMode=3,endMonth=10,endDay=1,endDayOfWeek=1,endTime=7200000,endTimeMode=0]]
  Timezone Env: 
  
  == Parsed Logical Plan ==
  Project [map_values(map1#508970).id2 AS map_values(map1).id2#509026]
  +- SubqueryAlias tbl
     +- View (`tbl`, [map1#508970])
        +- Relation [map1#508970] parquet
  
  == Analyzed Logical Plan ==
  map_values(map1).id2: array<bigint>
  Project [map_values(map1#508970).id2 AS map_values(map1).id2#509026]
  +- SubqueryAlias tbl
     +- View (`tbl`, [map1#508970])
        +- Relation [map1#508970] parquet
  
  == Optimized Logical Plan ==
  Project [map_values(map1#508970).id2 AS map_values(map1).id2#509026]
  +- Relation [map1#508970] parquet
  
  == Physical Plan ==
  *(1) CometColumnarToRow
  +- CometProject [map_values(map1).id2#509026], [map_values(map1#508970).id2 AS map_values(map1).id2#509026]
     +- CometScan parquet [map1#508970] Batched: true, DataFilters: [], Format: CometParquet, Location: InMemoryFileIndex(1 paths)[file:/__w/datafusion-comet/datafusion-comet/spark/target/tmp/spark-062..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<map1:map<struct<id:bigint,id2:bigint,id3:bigint>,struct<id2:bigint>>>
  
  == Results ==
  
  == Results ==
  !== Correct Answer - 5 ==                     == Spark Answer - 5 ==
   struct<map_values(map1).id2:array<bigint>>   struct<map_values(map1).id2:array<bigint>>
  ![ArrayBuffer(3)]                             [ArrayBuffer(0)]
  ![ArrayBuffer(4)]                             [ArrayBuffer(3)]
  ![ArrayBuffer(null)]                          [ArrayBuffer(4)]
   [null]                                       [null]
   [null]                                       [null] (QueryTest.scala:244)
```

File: native/core/src/execution/planner.rs [hunk 1]
```diff
@@ -3232,4 +3232,113 @@ mod tests {
...
+
+    select map_keys(m).b from (
+        select map(named_struct('a', 1, 'b', 'n', 'c', 'x'), named_struct('a', 1, 'b', 'n', 'c', 'x')) m
+     */
+    #[tokio::test]
+    async fn test_nested_types_map_keys_by_index() -> Result<(), DataFusionError> {
+        let session_ctx = SessionContext::new();
+
+        // generate test data in the temp folder
+        let test_data = "select map([named_struct('a', 1, 'b', 'n', 'c', 'x')], [named_struct('a', 1, 'b', 'n', 'c', 'x')]) c0";
```
Comment (parthchandra) [inline native/core/src/execution/planner.rs:3247]: minor: can we use a different struct for the key and the value, just to make it clear we are reading the correct fields.

File: spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala [hunk 2]
```diff
@@ -862,7 +862,8 @@ abstract class CometTestBase
       testName: String = "test",
       tableName: String = "tbl",
       sqlConf: Seq[(String, String)] = Seq.empty,
-      debugCometDF: DataFrame => Unit = _ => ()): Unit = {
+      debugCometDF: DataFrame => Unit = _ => (),
+      checkCometOperator: Boolean = true): Unit = {
```
Comment (parthchandra) [inline spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala:866]: Is this related?

File: native/core/src/execution/planner.rs [hunk 3]
```diff
@@ -3232,4 +3232,113 @@ mod tests {
...
     }
+
+    /*
+    Testing a nested types scenario map[struct, struct]
+
+    select map_keys(m).b from (
+        select map(named_struct('a', 1, 'b', 'n', 'c', 'x'), named_struct('a', 1, 'b', 'n', 'c', 'x')) m
+     */
+    #[tokio::test]
+    async fn test_nested_types_map_keys_by_index() -> Result<(), DataFusionError> {
```
Comment (parthchandra) [inline native/core/src/execution/planner.rs:3243]: nit: what does the by_index part of the name refer to?

**Review by parthchandra — APPROVED** [review]
lgtm. (Some minor comments)

File: native/core/src/execution/planner.rs (hunk 1 above)
Comment (comphead) [reply native/core/src/execution/planner.rs]: fixed

**Review by kazuyukitanimura — APPROVED** [review]

**Comment by comphead** [comment]
Thanks everyone
