### PR TITLE
fix: SortMergeJoin with unsupported key type should fall back to Spark

### LINKED ISSUE #354: SortMergeJoin with unsupported key type should fall back to Spark
### Describe the bug

DataFusion SortMergeJoin doesn't support all data types as join keys. See https://github.com/apache/datafusion/blob/dd5683745e7d527b01b804c8f4f1a0a53aa225e8/datafusion/physical-plan/src/joins/sort_merge_join.rs#L1521-L1523

Comet shouldn't transform Spark SortMergeJoin to DataFusion SortMergeJoin for unsupported join key types. Otherwise, we will see the following error currently:

```
  org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 6.0 failed 1 times, most recent failure: Lost task 0.0 in stage 6.0 (TID 4) (192.168.86.44 executor driver): org.apache.comet.CometNativeException
: This feature is not implemented: Unsupported data type in sort merge join comparator
        at org.apache.comet.Native.executePlan(Native Method)
        at org.apache.comet.CometExecIterator.executeNative(CometExecIterator.scala:71)
        at org.apache.comet.CometExecIterator.getNextBatch(CometExecIterator.scala:123)
        at org.apache.comet.CometExecIterator.hasNext(CometExecIterator.scala:138)
```

This is found during fixing test failures in #250.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #354.

### CODE REVIEW

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 1]
```diff
@@ -2318,6 +2330,13 @@ object QueryPlanSerde extends Logging with ShimQueryPlanSerde {
             return None
         }
 
+        for (key <- join.leftKeys) {
+          if (!supportedSortMergeJoinEqualType(key.dataType)) {
+            withInfo(op, s"Unsupported join key type ${key.dataType}")
```
[the remark this answers is not in the document]
Comment (viirya) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:2335]: okay

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 2]
```diff
@@ -2318,6 +2330,13 @@ object QueryPlanSerde extends Logging with ShimQueryPlanSerde {
             return None
         }
 
+        for (key <- join.leftKeys) {
+          if (!supportedSortMergeJoinEqualType(key.dataType)) {
+            withInfo(op, s"Unsupported join key type ${key.dataType} on key: ${key.sql}")
+            return None
```
Comment (andygrove) [inline spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:2336]: nit: do we want to stop checking as soon as we hit one unsupported key type or should we call `withInfo` for each unsupported key type (if there are multiple)

File: spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala [hunk 3]
```diff
@@ -40,6 +40,24 @@ class CometJoinSuite extends CometTestBase {
...
+      SQLConf.AUTO_BROADCASTJOIN_THRESHOLD.key -> "-1") {
+      withTable("t1", "t2") {
+        sql("CREATE TABLE t1(name STRING, time TIMESTAMP) USING PARQUET")
+        sql("INSERT OVERWRITE t1 VALUES('a', timestamp'2019-01-01 11:11:11')")
+
+        sql("CREATE TABLE t2(name STRING, time TIMESTAMP) USING PARQUET")
+        sql("INSERT OVERWRITE t2 VALUES('a', timestamp'2019-01-01 11:11:11')")
+
+        val df = sql("SELECT * FROM t1 JOIN t2 ON t1.time = t2.time")
+        checkSparkAnswer(df)
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala:56]: This doesn't appear to be asserting that the query actually falls back to Spark?

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala (hunk 2 above)
Comment (viirya) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:2336]: Changed it to for each unsupported key type.

File: spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala (hunk 3 above)
Comment (viirya) [reply spark/src/test/scala/org/apache/comet/exec/CometJoinSuite.scala:56]: Before the fix, the query will simply fail with exception. But it would be better to check if it falls back. Let me update it.

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @viirya

**Comment by planga82** [comment]
As an idea, I was thinking that we could put in tests to check the supported types in Datafusion, so that when we upgrade to a version of datafusion that supports these other types (like timestamp with timezone for example) we are aware that we should change the list of allowed types.

**Comment by viirya** [comment]
Merged. Thanks.

**Comment by viirya** [comment]
@planga82 Thanks for the suggestion. I created an issue to track it.
