### PR TITLE
fix: Simplify CometShuffleMemoryAllocator logic, rename classes, remove config

### LINKED ISSUE #1438: Columnar shuffle uses wrong memory allocator in unified memory mode
### Describe the bug

I am using unified memory management:

```
    --conf spark.memory.offHeap.enabled=true \
    --conf spark.memory.offHeap.size=2g \
```

I deliberately allocated a small amount of memory for testing purposes. However, the stack trace below shows that Comet is using `CometTestShuffleMemoryAllocator` which should not be the case.

```
Caused by: org.apache.spark.memory.SparkOutOfMemoryError: Unable to acquire 16777216 bytes of memory, got 2588672 bytes. Available: 2588672
	at org.apache.spark.shuffle.comet.CometTestShuffleMemoryAllocator.allocateMemoryBlock(CometTestShuffleMemoryAllocator.java:129)
	at org.apache.spark.shuffle.comet.CometTestShuffleMemoryAllocator.allocate(CometTestShuffleMemoryAllocator.java:116)
	at org.apache.spark.sql.comet.execution.shuffle.SpillWriter.initialCurrentPage(SpillWriter.java:158)
	at org.apache.spark.shuffle.sort.CometShuffleExternalSorter.insertRecord(CometShuffleExternalSorter.java:374)
	at org.apache.spark.sql.comet.execution.shuffle.CometUnsafeShuffleWriter.insertRecordIntoSorter(CometUnsafeShuffleWriter.java:278)
	at org.apache.spark.sql.comet.execution.shuffle.CometUnsafeShuffleWriter.write(CometUnsafeShuffleWriter.java:206)
```

This is created in the following code in `CometShuffleMemoryAllocatorTrait`:

```scala
    boolean useUnifiedMemAllocator =
        (boolean)
            CometConf$.MODULE$.COMET_COLUMNAR_SHUFFLE_UNIFIED_MEMORY_ALLOCATOR_IN_TEST().get();

    if (!useUnifiedMemAllocator) {
      synchronized (CometShuffleMemoryAllocator.class) {
        if (INSTANCE == null) {
          // CometTestShuffleMemoryAllocator handles pages by itself so it can be a singleton.
          INSTANCE = new CometTestShuffleMemoryAllocator(conf, taskMemoryManager, pageSize);
        }
      }
      return INSTANCE;
```

It seems that the wrong config is being checked here.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mbutrovich**
## Which issue does this PR close?

Closes #1438.

## Rationale for this change

We want to use the unified shuffle memory allocator in unified memory mode (off-heap) and the bounded shuffle memory allocator in on-heap mode.

## What changes are included in this PR?

- Rename both shuffle memory allocators to make their behavior more clear.
- Simplify shuffle memory allocator instantiation
- Remove config to get bounded allocator
- Remove test for config that we no longer support (unified memory with bounded allocator)

## How are these changes tested?

Existing tests.

### CODE REVIEW

File: spark/src/main/java/org/apache/spark/shuffle/comet/CometTestShuffleMemoryAllocator.java [hunk 1]
```diff
@@ -67,11 +68,10 @@ public final class CometTestShuffleMemoryAllocator extends CometShuffleMemoryAll
   private static final int OFFSET_BITS = 51;
   private static final long MASK_LONG_LOWER_51_BITS = 0x7FFFFFFFFFFFFL;
 
-  private static CometTestShuffleMemoryAllocator INSTANCE;
```
Comment (mbutrovich) [inline spark/src/main/java/org/apache/spark/shuffle/comet/CometTestShuffleMemoryAllocator.java:70]: The `isSparkTesting` variable in the other file made me glance at the unused warnings in the files I was touching, and this isn't used.

File: spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocator.java [hunk 2]
```diff
@@ -48,30 +48,30 @@ public final class CometShuffleMemoryAllocator extends CometShuffleMemoryAllocat
...
-            "CometShuffleMemoryAllocator should be used with off-heap "
-                + "memory mode, but got "
-                + taskMemoryManager.getTungstenMemoryMode());
-      }
+    }
 
-      // CometShuffleMemoryAllocator stores pages in TaskMemoryManager which is not singleton,
-      // but one instance per task. So we need to create a new instance for each task.
-      return new CometShuffleMemoryAllocator(taskMemoryManager, pageSize);
+    if (taskMemoryManager.getTungstenMemoryMode() != MemoryMode.OFF_HEAP) {
```
Comment (andygrove) [inline spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocator.java:65]: I'm still confused about this. This seems to imply that we only perform columnar shuffle when off-heap mode is enabled?

Comment (andygrove) [reply spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocator.java:65]: I tested with TPC-H without using off-heap and ran into this:

```
Caused by: java.lang.IllegalArgumentException: CometShuffleMemoryAllocator should be used with off-heap memory mode, but got ON_HEAP
	at org.apache.spark.shuffle.comet.CometShuffleMemoryAllocator.getInstance(CometShuffleMemoryAllocator.java:74)
	at org.apache.spark.sql.comet.execution.shuffle.CometDiskBlockWriter.<init>(CometDiskBlockWriter.java:142)
	at org.apache.spark.sql.comet.execution.shuffle.CometBypassMergeSortShuffleWriter.write(CometBypassMergeSortShuffleWriter.java:181)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
```

Comment (andygrove) [reply spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocator.java:65]: In Comet 0.3.0 we had a different implementation of CometShuffleMemoryAllocator that managed its own memory separately from Spark:

```
/**
 * A simple memory allocator used by `CometShuffleExternalSorter` to allocate memory blocks which
 * store serialized rows. We don't rely on Spark memory allocator because we need to allocate
 * off-heap memory no matter memory mode is on-heap or off-heap. This allocator is configured with
 * fixed size of memory, and it will throw `SparkOutOfMemoryError` if the memory is not enough.
 *
 * <p>Some methods are copied from `org.apache.spark.unsafe.memory.TaskMemoryManager` with
 * modifications. Most modifications are to remove the dependency on the configured memory mode.
 */
public final class CometShuffleMemoryAllocator extends MemoryConsumer {
```

In Comet 0.4.0 we forced use of off-heap memory and in Comet 0.5.0 we reverted that decision but inadvertently started using the test version of the allocator.

Perhaps we must re-instate this earlier version to support the on-heap use case. I am not sure, though. I wonder if @viirya can make any recommendation on this.

Comment (andygrove) [reply spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocator.java:65]: Oh, the original implementation was renamed to `CometTestShuffleMemoryAllocator`. So maybe we need to rename this.

Comment (viirya) [reply spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocator.java:65]: Yea, this memory allocator implementation doesn't change across the versions. It was just renamed to `CometTestShuffleMemoryAllocator` to reflect the decision to use it for test only purpose at the time.

File: spark/src/main/java/org/apache/spark/shuffle/comet/CometBoundedShuffleMemoryAllocator.java [hunk 3]
```diff
@@ -48,7 +48,7 @@
  * Thus, this allocator is used to allocate separate off-heap memory allocation for Comet JVM
  * shuffle and execution apart from Spark's on-heap memory configuration.
  */
-public final class CometTestShuffleMemoryAllocator extends CometShuffleMemoryAllocatorTrait {
+public final class CometBoundedShuffleMemoryAllocator extends CometShuffleMemoryAllocatorTrait {
```
Comment (andygrove) [inline spark/src/main/java/org/apache/spark/shuffle/comet/CometBoundedShuffleMemoryAllocator.java:51]: I like the new name 👍

File: spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocator.java [hunk 4]
```diff
@@ -42,36 +42,35 @@ public final class CometShuffleMemoryAllocator extends CometShuffleMemoryAllocat
   /**
    * Returns the singleton instance of `CometShuffleMemoryAllocator`. This method should be used
    * instead of the constructor to ensure that only one instance of `CometShuffleMemoryAllocator` is
-   * created. For Spark tests, this returns `CometTestShuffleMemoryAllocator` which is a test-only
-   * allocator that should not be used in production.
+   * created. For Spark tests, this returns `CometBoundedShuffleMemoryAllocator` which is a
+   * test-only allocator that should not be used in production.
    */
```
Comment (andygrove) [inline spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocator.java:47]: It is no longer true that this is just for testing. 

If the user enables Spark's off-heap memory then we want to use unified memory management, which means that we use `CometShuffleMemoryAllocator` which will interact with `TaskMemoryManager` to request memory and this will be sharing an off-heap pool with Spark.

If the user does not enable off-heap memory then we want to use `CometBoundedShuffleMemoryAllocator`. The tests also need to default to using this because off-heap is not enabled when running the Spark SQL tests. The `COMET_COLUMNAR_SHUFFLE_UNIFIED_MEMORY_ALLOCATOR_IN_TEST` flag allows us to use unified memory management in the tests (this does assume that off-heap is enabled). We enable this flag in `CometColumnarShuffleSuite` although I am not sure why.

File: spark/src/main/java/org/apache/spark/shuffle/comet/CometBoundedShuffleMemoryAllocator.java (hunk 3 above)
Comment (andygrove) [reply spark/src/main/java/org/apache/spark/shuffle/comet/CometBoundedShuffleMemoryAllocator.java:51]: Could you also rename `CometTestMemoryAllocatorShuffleSuite` to match

File: common/src/main/scala/org/apache/comet/CometConf.scala [hunk 5]
```diff
@@ -404,13 +404,15 @@ object CometConf extends ShimCometConf {
...
       .createWithDefault(1.0)
 
-  val COMET_COLUMNAR_SHUFFLE_UNIFIED_MEMORY_ALLOCATOR_IN_TEST: ConfigEntry[Boolean] =
-    conf("spark.comet.columnar.shuffle.unifiedMemoryAllocatorTest")
-      .doc("Whether to use Spark unified memory allocator for Comet columnar shuffle in tests." +
-        "If not configured, Comet will use a test-only memory allocator for Comet columnar " +
-        "shuffle when Spark test env detected. The test-ony allocator is proposed to run with " +
-        "Spark tests as these tests require on-heap memory configuration. " +
-        "By default, this config is false.")
+  val COMET_COLUMNAR_SHUFFLE_BOUNDED_MEMORY_ALLOCATOR: ConfigEntry[Boolean] =
```
Comment (andygrove) [inline common/src/main/scala/org/apache/comet/CometConf.scala:407]: I think that we should revert this config change. The original intent of the config was to force use of the unified memory allocator in tests even when running in on-heap mode. I still don't quite understand why we would want to do this, but the current tests are passing with this approach.

File: spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocator.java [hunk 6]
```diff
@@ -35,43 +35,47 @@
...
       SparkConf conf, TaskMemoryManager taskMemoryManager, long pageSize) {
     boolean isSparkTesting = Utils.isTesting();
-    boolean useUnifiedMemAllocator =
-        (boolean)
-            CometConf$.MODULE$.COMET_COLUMNAR_SHUFFLE_UNIFIED_MEMORY_ALLOCATOR_IN_TEST().get();
+    boolean useBoundedAllocator =
+        (boolean) CometConf$.MODULE$.COMET_COLUMNAR_SHUFFLE_BOUNDED_MEMORY_ALLOCATOR().get();
 
-    if (!useUnifiedMemAllocator) {
+    if (isSparkTesting || useBoundedAllocator) {
```
Comment (andygrove) [inline spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocator.java:59]: I think this loses the ability for us to force use of the unified memory allocator in tests

Comment (andygrove) [reply spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocator.java:59]: Also, if we run in on-heap mode, this condition doesn't get triggered so we end up using the unified memory allocator, which we don't want

Comment (andygrove) [reply spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocator.java:59]: I wonder if renaming `CometShuffleMemoryAllocator` to `CometShuffleUnifiedMemoryAllocator` would help reduce confusion?

**Review by andygrove — COMMENTED** [review]
This is looking good. I ran some quick tests locally and did not find any issues. I will test more thoroughly once the test regressions are fixed.

File: spark/src/main/scala/org/apache/spark/Plugins.scala [hunk 7]
```diff
@@ -101,14 +101,16 @@ class CometDriverPlugin extends DriverPlugin with Logging with ShimCometDriverPl
...
   private def shouldOverrideMemoryConf(conf: SparkConf): Boolean = {
-    conf.getBoolean(CometConf.COMET_ENABLED.key, true) && (
-      conf.getBoolean(
-        CometConf.COMET_EXEC_SHUFFLE_ENABLED.key,
-        CometConf.COMET_EXEC_SHUFFLE_ENABLED.defaultValue.get) ||
-        conf.getBoolean(
-          CometConf.COMET_EXEC_ENABLED.key,
-          CometConf.COMET_EXEC_ENABLED.defaultValue.get)
-    ) && CometSparkSessionExtensions.cometUnifiedMemoryManagerEnabled(conf)
+    val comet_enabled = conf.getBoolean(CometConf.COMET_ENABLED.key, true)
```
Comment (andygrove) [inline spark/src/main/scala/org/apache/spark/Plugins.scala:104]: This code was recently updated in main to remove the hard-coded default:

```suggestion
    val comet_enabled = conf.getBoolean(CometConf.COMET_ENABLED.key, CometConf.COMET_ENABLED.defaultValue.get)
```

File: spark/src/main/scala/org/apache/spark/Plugins.scala [hunk 8]
```diff
@@ -101,14 +101,16 @@ class CometDriverPlugin extends DriverPlugin with Logging with ShimCometDriverPl
...
+    val comet_exec_shuffle = conf.getBoolean(
```
Comment (andygrove) [inline spark/src/main/scala/org/apache/spark/Plugins.scala:105]: variable names should be camel case

File: spark/src/main/scala/org/apache/spark/Plugins.scala [hunk 9]
```diff
@@ -101,14 +101,16 @@ class CometDriverPlugin extends DriverPlugin with Logging with ShimCometDriverPl
...
+      CometConf.COMET_EXEC_SHUFFLE_ENABLED.key,
+      CometConf.COMET_EXEC_SHUFFLE_ENABLED.defaultValue.get)
+    val comet_exec = conf.getBoolean(
+      CometConf.COMET_EXEC_ENABLED.key,
+      CometConf.COMET_EXEC_ENABLED.defaultValue.get)
+    val unified_memory = CometSparkSessionExtensions.cometUnifiedMemoryManagerEnabled(conf)
+
+    comet_enabled && (comet_exec_shuffle || comet_exec) && !unified_memory
```
Comment (andygrove) [inline spark/src/main/scala/org/apache/spark/Plugins.scala:113]: this is much clearer

File: spark/src/test/scala/org/apache/spark/CometPluginsSuite.scala [hunk 10]
```diff
@@ -159,23 +159,4 @@ class CometPluginsUnifiedModeOverrideSuite extends CometTestBase {
     conf.set("spark.comet.memory.overhead.factor", "0.5")
     conf
   }
-
-  /*
-   * Since using unified memory, but not shuffle unified memory
-   * executor memory should be overridden by adding comet shuffle memory size
-   */
-  test("executor memory overhead is correctly overridden") {
```
[the remark this answers is not in the document]
Comment (mbutrovich) [reply spark/src/test/scala/org/apache/spark/CometPluginsSuite.scala:167]: It's effectively exercising the same path as above now (non-override) but I could make the values match. I'd argue that it's a redundant test but I can put it back.

File: spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocator.java [hunk 11]
```diff
@@ -19,91 +19,38 @@
...
-      return INSTANCE;
-    } else {
-      if (taskMemoryManager.getTungstenMemoryMode() != MemoryMode.OFF_HEAP) {
-        throw new IllegalArgumentException(
-            "CometShuffleMemoryAllocator should be used with off-heap "
-                + "memory mode, but got "
-                + taskMemoryManager.getTungstenMemoryMode());
-      }
 
+    if (CometSparkSessionExtensions.cometUnifiedMemoryManagerEnabled(conf)) {
```
Comment (andygrove) [inline spark/src/main/java/org/apache/spark/shuffle/comet/CometShuffleMemoryAllocator.java:42]: We can directly check the memory mode in the provided task manager rather than checking the configs here

```suggestion
    if (taskMemoryManager.getTungstenMemoryMode() == MemoryMode.OFF_HEAP) {
```

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @mbutrovich!
