### PR TITLE
fix: support read Struct by user schema

### LINKED ISSUE #1843: Spark Test fails `vectorized reader: missing all struct fields`
### Describe the bug

when reading with the specified schema
```
  test("vectorized reader: missing all struct fields") {
    Seq(true, false).foreach { offheapEnabled =>
      withSQLConf(
        SQLConf.USE_V1_SOURCE_LIST.key -> "parquet",
        CometConf.COMET_EXEC_ENABLED.key -> "true",
        CometConf.COMET_ENABLED.key -> "true",
        CometConf.COMET_EXPLAIN_FALLBACK_ENABLED.key -> "false",
        CometConf.COMET_NATIVE_SCAN_IMPL.key -> "native_datafusion",
        SQLConf.PARQUET_VECTORIZED_READER_NESTED_COLUMN_ENABLED.key -> "true",
        SQLConf.COLUMN_VECTOR_OFFHEAP_ENABLED.key -> offheapEnabled.toString) {
        val data = Seq(
          Tuple1((1, "a")),
          Tuple1((2, null)),
          Tuple1(null)
        )

        val readSchema = new StructType().add("_1",
          new StructType()
            .add("_3", IntegerType, nullable = true)
            .add("_4", LongType, nullable = true),
          nullable = true)

        withParquetFile(data) { file =>
          checkAnswer(spark.read.schema(readSchema).parquet(file),
            Row(null) :: Row(null) :: Row(null) :: Nil
          )
        }
      }
    }
  }
```

The test fails on correctness issue

```
!== Correct Answer - 3 ==   == Spark Answer - 3 ==
!struct<>                   struct<_1:struct<_3:int,_4:bigint>>
![null]                     [[null,null]]
![null]                     [[null,null]]
 [null]                     [null]
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by comphead**
## Which issue does this PR close?

Closes #1843 .

### CODE REVIEW

File: spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala [hunk 1]
```diff
@@ -862,6 +862,7 @@ abstract class CometTestBase
       testName: String = "test",
       tableName: String = "tbl",
       sqlConf: Seq[(String, String)] = Seq.empty,
+      readSchema: Option[StructType] = None,
```
Comment (comphead) [inline spark/src/test/scala/org/apache/spark/sql/CometTestBase.scala:864]: to support reading Comet with custom schema

File: native/core/src/parquet/parquet_support.rs [hunk 2]
```diff
@@ -239,14 +242,24 @@ fn cast_struct_to_struct(
...
                     cast_fields.push(cast_field);
+                    field_overlap = true;
                 } else {
                     cast_fields.push(new_null_array(to_fields[i].data_type(), array.len()));
                 }
             }
+
+            // If target schema doesn't contain any of the existing fields
+            // mark such a column in array as NULL
+            let nulls = if field_overlap {
```
Comment (comphead) [inline native/core/src/parquet/parquet_support.rs:253]: this is an actual fix

File: native/core/src/execution/planner.rs [hunk 3]
```diff
@@ -3331,4 +3347,146 @@ mod tests {
 
         Ok(())
     }
+
+    #[tokio::test]
+    async fn test_nested_types_extract_missing_struct_names() -> Result<(), DataFusionError> {
```
Comment (comphead) [inline native/core/src/execution/planner.rs:3334]: I'm planning to refactor rust planner tests into separate file and factor out common parts, like test parquet creation, test preparation, etc

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 4]
```diff
@@ -2728,4 +2728,35 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
     assert(cometWindowExecs.isEmpty)
   }
 
+  test("vectorized reader: missing all struct fields") {
+    Seq(true, false).foreach { offheapEnabled =>
+      withSQLConf(
+        SQLConf.USE_V1_SOURCE_LIST.key -> "parquet",
+        CometConf.COMET_EXEC_ENABLED.key -> "true",
+        CometConf.COMET_ENABLED.key -> "false",
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala]: Why is Comet disabled here?

Comment (comphead) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala]: nice catch, enabling it back

**Comment by andygrove** [comment]
miri failure due to https://github.com/apache/datafusion-comet/issues/1871

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @comphead.

**Review by parthchandra — APPROVED** [review]
lgtm. Thanks @comphead
