### PR TITLE
fix: Fallback to Spark for lpad/rpad for unsupported arguments & fix negative length handling

### LINKED ISSUE #2624: Fuzz test failure: lpad/rpad fail at runtime with "unsupported arguments"
### Describe the bug

Query worked in Spark but failed in Comet.

## SQL
```
SELECT c12, c16, c26, lpad(c12, c16, c26) AS x FROM test1 ORDER BY c12, c16, c26;
```
[ERROR] Query failed in Comet: Job aborted due to stage failure: Task 8 in stage 3548.0 failed 4 times, most recent failure: Lost task 8.3 in stage 3548.0 (TID 26460) (192.168.86.23 executor 10): org.apache.comet.CometNativeException: Unsupported arguments [Array(StringArray
[
  "儂ꢻ鱠蒡㥖\u{cdf}샪곛",
  "25",
  "0.3939222852601082",
  "剫蕚璆㕰\u{ab1a}䅅걣쪳",
  "ꖹ洛ᘣ맳쀚ঔ澟埲",
  "툨鱬掛盕Ӡ跁湦穆",
  "ဪ鶪쑓ᑙഥ悼ꬷ\u{243b}",
  "ᑸ䳃⿿髭ἀ簼襆❨",
  "ẑ\u{1779}闀鷁䶟ꗎ쿍ದ",
  null,
  "xZMzSucO",
  "鉕죹〦털髥㛃렙꧟",
  "56",
  "VAuzFSRE",
  "䊟㝉䋀믆༔娹䊎鲣",
  "27",
]), Array(PrimitiveArray<Int32>
[
  -19282,
  -31929,
  -17028,
  -30801,
  27411,
  14657,
  23256,
  -31023,
  13758,
  19326,
  -514,
  -19207,
  -25087,
  0,
  -9466,
  925,
]), Array(StringArray
[
  null,
  "qQAIDBgZ",
  "ၛ쀼ᇮ烒㞅⬊፬峇",
  null,
  "탧뭳꾔鎶郎☮活鋻",
  null,
  "숊史쐲烐鵗鉌ℨ鐅",
  "\u{4}嗃쩆鶌頜侥䦝泼",
  null,
  "ಈ夻삊苌窇죧䳷⣅",
  "0.27402197585631183",
  "ᘷ쾰溊ꕈ롊潕⬾⚞",
  "㊝鰎紼獻贰칻왇\u{82c}",
  "놭즓ॎ샶⺀˽翢薪",
  "ᎋ錮粵醒尬俪㦬™",
  "-34",
])] for function rpad/lpad/read_side_padding.
This issue was likely caused by a bug in DataFusion's code. Please help us to resolve this by filing a bug report in our issue tracker: https://github.com/apache/datafusion/issues

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### LINKED ISSUE #2631: lpad/rpad fail with `capacity overflow` due to overflow
### Describe the bug

I found this issue during fuzz testing:

```sql
SELECT str, lpad(str, len % 10, 'x') FROM t1 ORDER BY str
```

Test data:

```scala
    val schema = StructType(
      Seq(
        StructField("str", DataTypes.StringType, true),
        StructField("len", DataTypes.IntegerType, true),
        StructField("pad", DataTypes.StringType, true)))
    val df = FuzzDataGenerator.generateDataFrame(r, spark, schema, 100, DataGenOptions())
    df.createOrReplaceTempView("t1")
```

Causes:

```
Job aborted due to stage failure: Task 3 in stage 28.0 failed 1 times, most recent failure: Lost task 3.0 in stage 28.0 (TID 80) (woody.lan executor driver): org.apache.comet.CometNativeException: capacity overflow
        at comet::errors::init::{{closure}}(./native/core/src/errors.rs:151)
        at <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call(/rustc/1159e78c4747b02ef996e55082b704c09b970588/library/alloc/src/boxed.rs:1985)
        at std::panicking::rust_panic_with_hook(/rustc/1159e78c4747b02ef996e55082b704c09b970588/library/std/src/panicking.rs:841)
        at std::panicking::begin_panic_handler::{{closure}}(/rustc/1159e78c4747b02ef996e55082b704c09b970588/library/std/src/panicking.rs:699)
        at std::sys::backtrace::__rust_end_short_backtrace(/rustc/1159e78c4747b02ef996e55082b704c09b970588/library/std/src/sys/backtrace.rs:174)
        at __rustc::rust_begin_unwind(/rustc/1159e78c4747b02ef996e55082b704c09b970588/library/std/src/panicking.rs:697)
        at core::panicking::panic_fmt(/rustc/1159e78c4747b02ef996e55082b704c09b970588/library/core/src/panicking.rs:75)
        at alloc::raw_vec::capacity_overflow(/rustc/1159e78c4747b02ef996e55082b704c09b970588/library/alloc/src/raw_vec/mod.rs:29)
        at alloc::raw_vec::handle_error(/rustc/1159e78c4747b02ef996e55082b704c09b970588/library/alloc/src/raw_vec/mod.rs:797)
        at alloc::raw_vec::RawVecInner<A>::reserve::do_reserve_and_handle(/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:558)
        at alloc::raw_vec::RawVecInner<A>::reserve(/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:563)
        at alloc::raw_vec::RawVec<T,A>::reserve(/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec/mod.rs:331)
        at alloc::vec::Vec<T,A>::reserve(/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:1339)
        at alloc::string::String::reserve(/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/string.rs:1214)
        at <alloc::string::String as core::iter::traits::collect::Extend<char>>::extend(/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/string.rs:2406)
        at <alloc::string::String as core::iter::traits::collect::FromIterator<char>>::from_iter(/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/string.rs:2326)
        at core::iter::traits::iterator::Iterator::collect(/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2027)
        at datafusion_comet_spark_expr::static_invoke::char_varchar_utils::read_side_padding::add_padding_string(./native/spark-expr/src/static_invoke/char_varchar_utils/read_side_padding.rs:275)
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andygrove**
## Which issue does this PR close?

Closes https://github.com/apache/datafusion-comet/issues/2624
Closes https://github.com/apache/datafusion-comet/issues/2631

## Rationale for this change

Fix various bugs that caused queries to fail at runtime.

## What changes are included in this PR?

- Replace existing tests with one comprehensive test that is re-used for both lpad and road
- Fix handling of negative length
- Fallback to Spark for literal str argument
- Fallback to Spark for non-literal pad argument

## How are these changes tested?

New tests

### CODE REVIEW

**Comment by mbutrovich** [comment]
cc @coderfender since they were looking at this recently: https://github.com/apache/datafusion-comet/pull/2099

**Comment by coderfender** [comment]
Thank you for the mention @mbutrovich . @andygrove let me know if I can help in anyways to get this fixed soon

**Comment by andygrove** [comment]
> Thank you for the mention @mbutrovich . @andygrove let me know if I can help in anyways to get this fixed soon

It would be great if you could review the new test and make sure it covers everything the original tests covered. I believe that the underlying issues are resolved now.

**Comment by coderfender** [comment]
Sure @andygrove

**Comment by coderfender** [comment]
LGTM . Thank you for the prompt fix @andygrove

**Comment by andygrove** [comment]
Moving to draft until https://github.com/apache/datafusion-comet/pull/2635 is merged

File: native/spark-expr/src/static_invoke/char_varchar_utils/read_side_padding.rs [hunk 1]
```diff
@@ -204,14 +204,21 @@ fn spark_read_side_padding_internal<T: OffsetSizeTrait>(
...
                 match string {
-                    Some(string) => builder.append_value(add_padding_string(
-                        string.parse().unwrap(),
-                        length.unwrap() as usize,
-                        truncate,
-                        pad_string,
-                        is_left_pad,
-                    )?),
+                    Some(string) => {
+                        if length < 0 {
```
Comment (comphead) [inline native/spark-expr/src/static_invoke/char_varchar_utils/read_side_padding.rs]: its better to put happy path first in `if` stmt for compute intensive parts, so CPU won't have to execute eagerly instructions and then fall it back

File: spark/src/test/scala/org/apache/comet/CometStringExpressionSuite.scala [hunk 2]
```diff
@@ -19,12 +19,81 @@
...
+    val schema = StructType(
+      Seq(
+        StructField("str", DataTypes.StringType, nullable = true),
+        StructField("len", DataTypes.IntegerType, nullable = true),
+        StructField("pad", DataTypes.StringType, nullable = true)))
+    // scalastyle:off
+    val edgeCases = Seq(
+      "é", // unicode 'e\\u{301}'
+      "é", // unicode '\\u{e9}'
+      "తెలుగు")
```
Comment (parthchandra) [inline spark/src/test/scala/org/apache/comet/CometStringExpressionSuite.scala:60]: Out of curiosity, what makes this an edge case?

File: spark/src/main/scala/org/apache/comet/serde/strings.scala [hunk 3]
```diff
@@ -177,21 +187,16 @@ object CometStringRPad extends CometExpressionSerde[StringRPad] {
...
-   * @return
-   *   Protocol buffer representation, or None if the expression could not be converted. In this
-   *   case it is expected that the input expression will have been tagged with reasons why it
-   *   could not be converted.
-   */
+  override def getSupportLevel(expr: StringLPad): SupportLevel = {
+    if (expr.str.isInstanceOf[Literal]) {
+      return Unsupported(Some("Scalar values are not supported for the str argument"))
+    }
+    if (!expr.pad.isInstanceOf[Literal]) {
```
Comment (parthchandra) [inline spark/src/main/scala/org/apache/comet/serde/strings.scala:194]: I don't know if we'll ever hit this. As far as I can see (in `functions.lpad`), Spark expects the pad argument to be a literal as well.

**Review by parthchandra — APPROVED** [review]
lgtm.

File: native/spark-expr/src/static_invoke/char_varchar_utils/read_side_padding.rs (hunk 1 above)
Comment (andygrove) [reply native/spark-expr/src/static_invoke/char_varchar_utils/read_side_padding.rs]: Thanks. I have updated this.

File: spark/src/test/scala/org/apache/comet/CometStringExpressionSuite.scala (hunk 2 above)
Comment (andygrove) [reply spark/src/test/scala/org/apache/comet/CometStringExpressionSuite.scala:60]: The first two were added in https://github.com/apache/datafusion-comet/pull/772 to make sure Comet was consistent with Spark even though Rust and Java have different ways of representing unicode and graphemes.

File: spark/src/main/scala/org/apache/comet/serde/strings.scala (hunk 3 above)
Comment (andygrove) [reply spark/src/main/scala/org/apache/comet/serde/strings.scala:194]: Spark doesn't require pad to be a literal:

```
scala> spark.sql("select a, lpad('foo', 6, a) from t1").show
+---+---------------+
|  a|lpad(foo, 6, a)|
+---+---------------+
|  $|         $$$foo|
|  @|         @@@foo|
+---+---------------+
```

Comment (andygrove) [reply spark/src/main/scala/org/apache/comet/serde/strings.scala:194]:
```
case class StringRPad(str: Expression, len: Expression, pad: Expression = Literal(" "))
```

Comment (andygrove) [reply spark/src/main/scala/org/apache/comet/serde/strings.scala:194]: I suppose this is a good example of the benefit of fuzz testing (which is how this issue was discovered). The fuzzer will generate test cases that most developers would not consider. It does seem unlikely that anyone would want to use a column for the pad value, but I suppose it is possible that someone may have that requirement.

File: spark/src/test/scala/org/apache/comet/CometStringExpressionSuite.scala [hunk 4]
```diff
@@ -19,12 +19,81 @@
...
+      r,
+      spark,
+      schema,
+      1000,
+      DataGenOptions(maxStringLength = 6, customStrings = edgeCases))
+    df.createOrReplaceTempView("t1")
+
+    // test all combinations of scalar and array arguments
+    for (str <- Seq("'hello'", "str")) {
+      for (len <- Seq("6", "-6", "0", "len % 10")) {
```
Comment (hsiang-c) [inline spark/src/test/scala/org/apache/comet/CometStringExpressionSuite.scala:72]: 👍

File: spark/src/test/scala/org/apache/comet/CometStringExpressionSuite.scala [hunk 5]
```diff
@@ -19,12 +19,81 @@
...
+    val df = FuzzDataGenerator.generateDataFrame(
+      r,
+      spark,
+      schema,
+      1000,
+      DataGenOptions(maxStringLength = 6, customStrings = edgeCases))
+    df.createOrReplaceTempView("t1")
+
+    // test all combinations of scalar and array arguments
+    for (str <- Seq("'hello'", "str")) {
```
Comment (hsiang-c) [inline spark/src/test/scala/org/apache/comet/CometStringExpressionSuite.scala:71]: Spark [doc](https://spark.apache.org/docs/latest/api/sql/index.html#rpad) says it also supports binary string input: e.g `unhex('aabb')`.

Comment (andygrove) [reply spark/src/test/scala/org/apache/comet/CometStringExpressionSuite.scala:71]: Good catch, thanks. That opens up another set of issues! :sob:

Comment (andygrove) [reply spark/src/test/scala/org/apache/comet/CometStringExpressionSuite.scala:71]: I added separate tests for binary inputs

**Review by hsiang-c — APPROVED** [review]
LGTM
