### PR TITLE
fix: Make Sha2 fallback message more user-friendly

### LINKED ISSUE #2193: Improve SHA2 user-error message in serdes code
The SHA2 error message [here](https://github.com/rishvin/datafusion-comet/blob/440afb11ad7d9be3f16233d0a68dc57e36a44051/spark/src/main/scala/org/apache/comet/serde/hash.scala#L81) is not very user friendly. Previously it was [this](https://github.com/rishvin/datafusion-comet/blob/af27b37329c36c6c13626546166d2e8bd22b2de7/spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala#L1615). The ticket is about bringing back the older error message.

### PR DESCRIPTION
**Pull request by rishvin**
## Which issue does this PR close?

Closes #2193 

## Rationale for this change

With a recent change, the Sha2 fallback message is now not very user-friendly. This PR brings back the older message.

## What changes are included in this PR?

A simple fallback message change.

## How are these changes tested?

N/A

### CODE REVIEW

File: spark/src/main/scala/org/apache/comet/serde/hash.scala [hunk 1]
```diff
@@ -75,7 +75,7 @@ object CometSha2 extends CometExpressionSerde[Sha2] {
     // It's possible for spark to dynamically compute the number of bits from input
     // expression, however DataFusion does not support that yet.
     if (!expr.right.foldable) {
-      withInfo(expr, "For Sha2, non-foldable right argument is not supported")
+      withInfo(expr, "For Sha2, non literal numBits is not supported")
```
Comment (comphead) [inline spark/src/main/scala/org/apache/comet/serde/hash.scala:78]: I think its called `bitLength` https://spark.apache.org/docs/latest/api/sql/#sha2

Comment (rishvin) [reply spark/src/main/scala/org/apache/comet/serde/hash.scala:78]: Thanks for that link.

Looks like there is a bit of inconsistency between spark docs too.
If I look into 
Spark4: https://spark.apache.org/docs/latest/api/scala/org/apache/spark/sql/functions$.html#sha2(e:org.apache.spark.sql.Column,numBits:Int):org.apache.spark.sql.Column
and python-doc: https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.functions.sha2.html
they say `numBits`.

Since Spark4 doc says `numBits`, we can keep it the same.
