### PR TITLE
fix: Compute murmur3 hash with dictionary input correctly

### LINKED ISSUE #427: bug: hash expression is not consistent with Spark
### Describe the bug

Our `hash` implementation does not produce the same results as Spark for some inputs.

I added this test to `CometCastSuite` because that's where we have random data generators (we should move them into a common class that more test suites can use).

```scala
  test("hash") {
    val input = generateStrings(timestampPattern, 8).toDF("a")
    withTempPath { dir =>
      val data = roundtripParquet(input, dir).coalesce(1)
      data.createOrReplaceTempView("t")
      val df = spark.sql(s"select a, hash(a) from t order by a")
      checkSparkAnswerAndOperator(df)
    }
  }
```

Example output:

```
!== Correct Answer - 1000 ==    == Spark Answer - 1000 ==
 struct<a:string,hash(a):int>   struct<a:string,hash(a):int>
![,142593372]                   [,0]
![	099,-1611881412]             [	099,-881749019]
![	1 474,240523873]             [	1 474,-1111423867]
![	12852,-1057581169]           [	12852,-404859411]
![	18,-492750382]               [	18,1333608017]
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by advancedxy**
## Which issue does this PR close?
Closes #427 

## Rationale for this change
Bug fixes. When submitting #424, we found there's a bug in spark_hash, which doesn't handle dictionary array correctly.
This PR tries to fix this first.

## What changes are included in this PR?
1. refactor some part of spark_hash.rs and be ready for xxhash64 support
2. unpack dictionary when computing with hashes
3. updated test

This PR currently depends on #426, will rebase once that's merged.

## How are these changes tested?
Updated test with randomized input.

### CODE REVIEW

File: core/src/execution/datafusion/spark_hash.rs [hunk 1]
```diff
@@ -227,27 +248,11 @@ pub fn create_hashes<'a>(
...
-                    for (i, hash) in hashes_buffer.iter_mut().enumerate() {
-                        if !array.is_null(i) {
-                            *hash = spark_compatible_murmur3_hash(
-                                i32::from(array.value(i)).to_le_bytes(),
-                                *hash,
-                            );
-                        }
-                    }
-                }
+                hash_array_boolean!(BooleanArray, col, i32, hashes_buffer);
```
Comment (kazuyukitanimura) [inline core/src/execution/datafusion/spark_hash.rs:255]: I am wondering why this is a macro. It looks like this is the only use case?

File: spark/src/main/scala/org/apache/comet/expressions/CometCast.scala [hunk 2]
```diff
@@ -108,7 +108,7 @@ object CometCast {
         Compatible()
       case DataTypes.ByteType | DataTypes.ShortType | DataTypes.IntegerType |
           DataTypes.LongType =>
-        Compatible()
+        Incompatible(Some("Not all invalid inputs are detected"))
```
Comment (kazuyukitanimura) [inline spark/src/main/scala/org/apache/comet/expressions/CometCast.scala:111]: Will this be gone after rebasing/merging with main?

File: core/src/execution/datafusion/spark_hash.rs [hunk 3]
```diff
@@ -123,8 +115,31 @@ macro_rules! hash_array {
...
+                if !array.is_null(i) {
+                    *hash = spark_compatible_murmur3_hash(
+                        $hash_input_type::from(array.value(i)).to_le_bytes(),
+                        *hash,
+                    );
+                }
+            }
+        }
+    };
+}
```
Comment (viirya) [inline core/src/execution/datafusion/spark_hash.rs:139]: This is pull out as a macro because you will use different hash function other than `spark_compatible_murmur3_hash` later?

File: core/src/execution/datafusion/spark_hash.rs [hunk 4]
```diff
@@ -193,27 +208,33 @@ macro_rules! hash_array_decimal {
 fn create_hashes_dictionary<K: ArrowDictionaryKeyType>(
     array: &ArrayRef,
     hashes_buffer: &mut [u32],
+    multi_col: bool,
```
Comment (viirya) [inline core/src/execution/datafusion/spark_hash.rs:211]: `multi_col` looks strange. Maybe `first_col`? And

```rust
if !first_col {
  // unpack the dictionary array
  ...
} else {
  ...
}
```

File: core/src/execution/datafusion/spark_hash.rs [hunk 5]
```diff
@@ -227,27 +248,11 @@ pub fn create_hashes<'a>(
     arrays: &[ArrayRef],
     hashes_buffer: &'a mut [u32],
 ) -> Result<&'a mut [u32]> {
-    for col in arrays {
+    for (i, col) in arrays.iter().enumerate() {
+        let multi_col = i >= 1;
```
Comment (viirya) [inline core/src/execution/datafusion/spark_hash.rs:252]: `first_col`?

File: core/src/execution/datafusion/spark_hash.rs [hunk 6]
```diff
@@ -363,78 +368,64 @@ mod tests {
...
         };
     }
 
+    fn test_murmur3_hash<I: Clone, T: arrow_array::Array + From<Vec<Option<I>>> + 'static>(
+        values: Vec<Option<I>>,
+        expected: Vec<u32>,
+    ) {
+        // copied before inserting nulls
+        let mut input_with_nulls = values.clone();
+        let mut expected_with_nulls = expected.clone();
```
Comment (viirya) [inline core/src/execution/datafusion/spark_hash.rs:386]: I guess you mean?
```suggestion
        let mut expected_without_nulls = expected.clone();
```

Comment (viirya) [reply core/src/execution/datafusion/spark_hash.rs:386]: Oh, nvm. You use it below for the values with nulls.

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 7]
```diff
@@ -1452,17 +1452,55 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
           sql(s"create table $table(col string, a int, b float) using parquet")
           sql(s"""
-             |insert into $table values
-             |('Spark SQL  ', 10, 1.2), (NULL, NULL, NULL), ('', 0, 0.0), ('苹果手机', NULL, 3.999999)
-             |, ('Spark SQL  ', 10, 1.2), (NULL, NULL, NULL), ('', 0, 0.0), ('苹果手机', NULL, 3.999999)
-             |""".stripMargin)
+              |insert into $table values
+              |('Spark SQL  ', 10, 1.2), (NULL, NULL, NULL), ('', 0, 0.0), ('苹果手机', NULL, 3.999999)
+              |, ('Spark SQL  ', 10, 1.2), (NULL, NULL, NULL), ('', 0, 0.0), ('苹果手机', NULL, 3.999999)
+              |""".stripMargin)
```
Comment (viirya) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1458]: Did you insert extra space characters?

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 8]
```diff
@@ -1452,17 +1452,55 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+          val colA = dataGen.generateInts(randomNumRows)
+          val colB = dataGen.generateFloats(randomNumRows)
+          val data = col.zip(colA).zip(colB).map { case ((a, b), c) => (a, b, c) }
+          data
+            .toDF("col", "a", "b")
+            .write
+            .mode("append")
+            .insertInto(table)
+          // with random generated data
+          // disable cast(b as string) for now, as it may produce incompatible result
```
Comment (viirya) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1496]: Why there is incompatible result?

Comment (viirya) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1496]:
```suggestion
          // disable cast(b as string) for now, as the cast from float to string may produce incompatible result
```

**Review by kazuyukitanimura — APPROVED** [review]
LGTM

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 9]
```diff
@@ -1452,17 +1452,55 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+              |""".stripMargin)
+        }
+      }
+    }
+  }
+
+  test("hash functions with random input") {
+    val dataGen = DataGenerator.DEFAULT
+    // sufficient number of rows to create dictionary encoded ArrowArray.
+    val randomNumRows = 1000
```
[the remark this answers is not in the document]
Comment (kazuyukitanimura) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1474]: Potentially we can add repeated values to force dictionary. E.g. randomly generate 100 rows and repeat 10 times to make 1000 rows

[the remark this answers is not in the document]
Comment (kazuyukitanimura) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:1474]: Yes, `makeParquetFileAllTypes` or some existing dictionary related tests may be helpful

**Review by andygrove — APPROVED** [review]
LGTM. Thank you @advancedxy
