### PR TITLE
fix: Running cargo build always triggers rebuild

### LINKED ISSUE #578: Build always triggers a partial rebuild
### Describe the bug

When ever I run `cargo build` there is always a rebuild even if nothing changed.

Building with verbose logs
```
      Dirty datafusion-comet v0.1.0 (/home/eejbyfeldt/dev/apache/datafusion-comet/core): the file `src/execution/proto/*.proto` is missing
   Compiling datafusion-comet v0.1.0 (/home/eejbyfeldt/dev/apache/datafusion-comet/core)
```

so to me the issue seems to be that `rerun-if-changed` does not support globs and will look for a file acutally named `*.proto` (https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed).

### Steps to reproduce

Run `make core` and then `make core` again. Since nothing changed there should be no rebuild steps.

### Expected behavior

Running `make core` twice without changed should only build once.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by eejbyfeldt**
I don't think rerun-if-changed supports globs https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed but according to the docs passing a directory should work.

## Which issue does this PR close?

Closes #578.

## Rationale for this change

Quicker build in many cases.

## What changes are included in this PR?

Fixes our build.rs build script to only rebuild when there is actual changes in the proto files.

## How are these changes tested?
Running `make core` manually.

### CODE REVIEW

File: core/build.rs [hunk 1]
```diff
@@ -20,7 +20,7 @@
 use std::{fs, io::Result, path::Path};
 
 fn main() -> Result<()> {
-    println!("cargo:rerun-if-changed=src/execution/proto/*.proto");
+    println!("cargo:rerun-if-changed=src/execution/proto/");
```
Comment (andygrove) [inline core/build.rs:23]: This change seems correct to me. The docs state that the syntax is `[cargo::rerun-if-changed=PATH](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed) and adds these notes:

```
The rerun-if-changed instruction tells Cargo to re-run the build script if the file at the given path has changed. Currently, Cargo only uses the filesystem last-modified “mtime” timestamp to determine if the file has changed. It compares against an internal cached timestamp of when the build script last ran.

If the path points to a directory, it will scan the entire directory for any modifications.
```

**Review by andygrove — APPROVED** [review]
Thanks @eejbyfeldt

**Review by viirya — APPROVED** [review]
Thanks for fixing this. @eejbyfeldt
