### PR TITLE
fix: Fall back to `native_comet` for encrypted Parquet scans

### LINKED ISSUE #2198: decryption not supported when using `auto` scan mode to read from Parquet
### Describe the bug

When I implemented `auto` scan mode, I overlooked the checks for encryption being enabled.

We choose a specific scan in the following code, which does not check for encryption, so will likely pick `native_iceberg_compat` in most cases:

```scala
        // if scan is auto then pick the best available scan
        if (scanImpl == SCAN_AUTO) {
          scanImpl = selectScan(scanExec, r.partitionSchema)
        }
```

Later on we fall back to Spark if encryption is enabled and then scan is not `native_comet`.

```scala
        val encryptionEnabled: Boolean =
          conf.getConfString("parquet.crypto.factory.class", "").nonEmpty &&
            conf.getConfString("parquet.encryption.kms.client.class", "").nonEmpty

        if (scanImpl != CometConf.SCAN_NATIVE_COMET && encryptionEnabled) {
          fallbackReasons +=
            "Full native scan disabled because encryption is not supported"
          return withInfos(scanExec, fallbackReasons.toSet)
        }
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andygrove**
## Which issue does this PR close?

Closes https://github.com/apache/datafusion-comet/issues/2198

### CODE REVIEW

**Review by parthchandra — APPROVED** [review]
lgtm

File: spark/src/test/scala/org/apache/spark/sql/comet/ParquetEncryptionITCase.scala [hunk 1]
```diff
@@ -49,7 +49,7 @@ class ParquetEncryptionITCase extends CometTestBase with SQLTestUtils {
   private val key2 = encoder.encodeToString("1234567890123451".getBytes(StandardCharsets.UTF_8))
 
   test("SPARK-34990: Write and read an encrypted parquet") {
-    assume(CometConf.COMET_NATIVE_SCAN_IMPL.get() == CometConf.SCAN_NATIVE_COMET)
+    assume(CometConf.COMET_NATIVE_SCAN_IMPL.get() != CometConf.SCAN_NATIVE_DATAFUSION)
```
Comment (mbutrovich) [inline spark/src/test/scala/org/apache/spark/sql/comet/ParquetEncryptionITCase.scala:52]: ICEBERG_COMPAT shouldn't work here either, right?

Comment (andygrove) [reply spark/src/test/scala/org/apache/spark/sql/comet/ParquetEncryptionITCase.scala:52]: Right, `auto` and `native_comet` work. `native_datafusion` and `native_iceberg_compat` do not.

File: spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala [hunk 2]
```diff
@@ -131,11 +131,19 @@ case class CometScanRule(session: SparkSession) extends Rule[SparkPlan] with Com
...
+        val encryptionEnabled: Boolean =
+          conf.getConfString("parquet.crypto.factory.class", "").nonEmpty &&
+            conf.getConfString("parquet.encryption.kms.client.class", "").nonEmpty
+
         var scanImpl = COMET_NATIVE_SCAN_IMPL.get()
 
         // if scan is auto then pick the best available scan
         if (scanImpl == SCAN_AUTO) {
-          scanImpl = selectScan(scanExec, r.partitionSchema)
+          if (encryptionEnabled) {
```
Comment (comphead) [inline spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala:142]: should we log the reason for the switch?

Comment (andygrove) [reply spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala:142]: yes, good point

**Review by comphead — APPROVED** [review]
lgtm thanks @andygrove

File: spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala (hunk 2 above)
Comment (andygrove) [reply spark/src/main/scala/org/apache/comet/rules/CometScanRule.scala:142]: updated
