### PR TITLE
Use IfExpr to check when input to log2 is <=0 and return null

### LINKED ISSUE #485: bug: log2 produces different values than Spark in some cases
### Describe the bug

I discovered this bug using [Comet Fuzz](https://github.com/apache/datafusion-comet/pull/472).

```sql
SELECT Log2(c4) FROM test0
```

[ERROR] Spark and Comet produced different results.
### Spark Plan
```
*(1) Project [LOG2(cast(c4#4 as double)) AS LOG2(c4)#13927]
+- *(1) ColumnarToRow
   +- FileScan parquet [c4#4] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/Users/andy/git/apple/comet-fuzz/test0.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c4:tinyint>

```
### Comet Plan
```
*(1) ColumnarToRow
+- CometProject [LOG2(c4)#13931], [LOG2(cast(c4#4 as double)) AS LOG2(c4)#13931]
   +- CometScan parquet [c4#4] Batched: true, DataFilters: [], Format: CometParquet, Location: InMemoryFileIndex(1 paths)[file:/Users/andy/git/apple/comet-fuzz/test0.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c4:tinyint>

```
### Results 
Spark produced 200 rows and Comet produced 200 rows.
First difference at row 0:
Spark: `[1.584962500721156]`
Comet: `[-Infinity]`

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PedroMDuarte**
## Which issue does this PR close?

Closes #485 

## Rationale for this change

Compatibility with how Spark handles logarithms of values <=0. 

## What changes are included in this PR?

Use IfExpr to check when input to log2 is <=0 and return null.  This is done to match Spark's behavior, which in turn is implemented to match Hive's behavior.

## How are these changes tested?

The existing test for `ln`, `log2` and `log10` was modified so that it includes negative numbers as part of the inputs being tested.

### CODE REVIEW

**Review by andygrove — COMMENTED** [review]
This is looking good so far. Thanks @PedroMDuarte

File: core/src/execution/datafusion/planner.rs [hunk 1]
```diff
@@ -1397,7 +1397,18 @@ impl PhysicalPlanner {
             args.is_empty(),
         ));
 
-        Ok(scalar_expr)
+        match fun_name.as_str() {
```
Comment (viirya) [inline core/src/execution/datafusion/planner.rs:1400]: Hmm, please don't put this special handling in `create_scalar_function_expr`. Could you move it to `create_comet_physical_fun` where special handling of scalar functions should be located?

Comment (PedroMDuarte) [reply core/src/execution/datafusion/planner.rs:1400]: Thanks for bringing that up!

Just to clarify, if we were to do this as part of `create_comet_physical_fun` then it would be all reimplemented at a lower level and not able to reuse the Datafusion Log2 implementation via an IfExpr.  Is that right? 

Happy to go either way. @andygrove's original hint mentioned using IfExpr, but I couldn't quite get that working inside of `create_comet_physical_fun` because it doesn't have access to the arg exprs.

Comment (andygrove) [reply core/src/execution/datafusion/planner.rs]: Apologies for the delay in responding here. I will start reviewing this on Monday.

**Comment by kazuyukitanimura** [comment]
I would rather do this in QueryPlanSerde, E.g.
```
        case Log2(child) =>
          val childExpr = exprToProtoInternal(nullIfNegative(child), inputs)

def nullIfNegative(expression: Expression): {
    val zero = Literal.default(expression.dataType)
    If(LessThanOrEqual(expression, zero), Literal.create(null, expression.dataType), expression)
}
```

See `nullIfWhenPrimitive` for a similar case.

**Comment by PedroMDuarte** [comment]
> I would rather do this in QueryPlanSerde, E.g.
> 
> ```
>         case Log2(child) =>
>           val childExpr = exprToProtoInternal(nullIfNegative(child), inputs)
> 
> def nullIfNegative(expression: Expression): {
>     val zero = Literal.default(expression.dataType)
>     If(LessThanOrEqual(expression, zero), Literal.create(null, expression.dataType), expression)
> }
> ```
> 
> See `nullIfWhenPrimitive` for a similar case.

thanks for this suggestion!

**Review by andygrove — APPROVED** [review]
LGTM pending CI. I confirmed that the change to the unit test does demonstrate the incorrect behavior. Thanks @PedroMDuarte

**Comment by andygrove** [comment]
Could you also update this section in expressions.md 

```
| Log        | log(0) will produce `-Infinity` unlike Spark which returns `null`   |
| Log2       | log2(0) will produce `-Infinity` unlike Spark which returns `null`  |
| Log10      | log10(0) will produce `-Infinity` unlike Spark which returns `null` |
```

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 2]
```diff
@@ -1703,18 +1703,21 @@ object QueryPlanSerde extends Logging with ShimQueryPlanSerde with CometExprShim
               optExprWithInfo(optExpr, expr, child)
           }
 
+        /// The expression for `log` functions is defined as  null on numbers less than or equal
+        /// to 0.  This matches Spark and Hive behavior, where non positive values eval to null
+        /// instead of NaN or -Infinity
```
Comment (andygrove) [inline spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:1708]: CI is failing with scalastyle error `Insert a space after the start of the comment` for these lines. Changing `///` to `//` should resolve it.

```suggestion
        // The expression for `log` functions is defined as  null on numbers less than or equal
        // to 0.  This matches Spark and Hive behavior, where non positive values eval to null
        // instead of NaN or -Infinity
```

**Review by kazuyukitanimura — APPROVED** [review]

**Comment by kazuyukitanimura** [comment]
hmm, ci is failing...

**Comment by PedroMDuarte** [comment]
thanks for the guidance here, really appreciate you all taking the time to show me how to contribute this fix.

**Comment by kazuyukitanimura** [comment]
Merged, thanks @PedroMDuarte @andygrove

**Comment by kazuyukitanimura** [comment]
And thanks @viirya
