### PR TITLE
fix: default values for native_datafusion scan

### LINKED ISSUE #1750: [native_datafusion] No support for default values for Parquet columns
### Describe the bug

`native_datafusion` produces incorrect results when reading Parquet for columns that contain null and have a default value assigned.

### Steps to reproduce

Add this test to `CometExpressionSuite`:

```scala
  test("parquet default values") {
    withTable("t1") {
      sql(s"create table t1(col1 boolean) using parquet")
      sql(s"insert into t1 values(true)")
      sql(s"alter table t1 add column col2 string default 'hello'")
      checkSparkAnswerAndOperator("select * from t1")
    }
  }
```

Results:

```
!== Correct Answer - 1 ==           == Spark Answer - 1 ==
 struct<col1:boolean,col2:string>   struct<col1:boolean,col2:string>
![true,hello]                       [true,null]
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mbutrovich**
This change is only needed for native_datafusion since native_iceberg_compat works at the column granularity and seems to populate that fine.
## Which issue does this PR close?

Closes #1750.

## What changes are included in this PR?

- Serialize default values from the query plan, deserialize on native side, and embed in `SchemaMapper`.
- Default null columns now use compact scalar representation for the column.
- Refactored some old comments and unused fields in SparkParquetOptions.

## How are these changes tested?

@andygrove's simple unit test, and added a new fuzz test that tests all primitive types for default values.

### CODE REVIEW

File: native/core/src/parquet/parquet_support.rs [hunk 1]
```diff
@@ -60,9 +60,6 @@ pub struct SparkParquetOptions {
     pub allow_incompat: bool,
     /// Support casting unsigned ints to signed ints (used by Parquet SchemaAdapter)
     pub allow_cast_unsigned_ints: bool,
-    /// We also use the cast logic for adapting Parquet schemas, so this flag is used
-    /// for that use case
-    pub is_adapting_schema: bool,
```
Comment (mbutrovich) [inline native/core/src/parquet/parquet_support.rs:65]: This is dead code from when we used the cast logic (and `CastOptions`) to handle Parquet type conversion.

File: native/core/src/parquet/schema_adapter.rs [hunk 2]
```diff
@@ -196,15 +198,43 @@ impl SchemaMapper for SchemaMapping {
...
             // and zip it with the index that maps fields from the projected table schema to the
             // projected file schema in `batch`
             .zip(&self.field_mappings)
             // and for each one...
-            .map(|(field, file_idx)| {
+            .map(|((field_idx, field), file_idx)| {
                 file_idx.map_or_else(
-                    // If this field only exists in the table, and not in the file, then we know
-                    // that it's null, so just return that.
-                    || Ok(new_null_array(field.data_type(), batch_rows)),
```
Comment (mbutrovich) [inline native/core/src/parquet/schema_adapter.rs:207]: Got rid of instantiating an entire null array in favor of a single null value for column.

File: spark/src/test/scala/org/apache/comet/CometFuzzTestSuite.scala [hunk 3]
```diff
@@ -99,6 +100,56 @@ class CometFuzzTestSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+  test("select column with default value") {
+    // This test fails in Spark's vectorized Parquet reader for DECIMAL(36,18) or BINARY default values.
+    withSQLConf(SQLConf.PARQUET_VECTORIZED_READER_ENABLED.key -> "false") {
+      // This test relies on two tables: 1) t1 the Parquet file generated by ParquetGenerator with random values, and
+      // 2) t2 is a new table created with one column which we add a second column with different types and random values.
+      // We use the schema and values of t1 to simplify random value generation for the default column value in t2.
+      val df = spark.read.parquet(filename)
+      df.createOrReplaceTempView("t1")
+      for (col <- df.columns
+          .slice(1, 14)) { // All the primitive columns based on ParquetGenerator.makeParquetFile.
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/CometFuzzTestSuite.scala:112]: this code could break if we change the parquet generator in the future. It would probably be best to filter instead. Something like:

```scala
    val columns = df.schema.fields.filter(f => !isComplexType(f.dataType)).map(_.name)
```

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 4]
```diff
@@ -2327,18 +2346,18 @@ object QueryPlanSerde extends Logging with CometExprShim {
           val requiredSchema = schema2Proto(scan.requiredSchema.fields)
           val dataSchema = schema2Proto(scan.relation.dataSchema.fields)
 
-          val data_schema_idxs = scan.requiredSchema.fields.map(field => {
+          val dataSchemaIndexes = scan.requiredSchema.fields.map(field => {
```
Comment (mbutrovich) [inline spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:2349]: Just fixing incorrectly formatted variables as I find them.

File: native/core/src/execution/planner.rs [hunk 5]
```diff
@@ -1108,6 +1108,44 @@ impl PhysicalPlanner {
...
+                            literal
+                                .as_any()
+                                .downcast_ref::<DataFusionLiteral>()
+                                .ok_or_else(|| {
+                                    GeneralError("Expected literal of default value.".to_string())
+                                })
+                                .map(|literal| literal.value().clone())
+                                .unwrap()
+                        })
+                        .collect::<Vec<ScalarValue>>();
```
Comment (andygrove) [inline native/core/src/execution/planner.rs:1133]: nit: we can avoid unwrap here:

```suggestion
                    let default_values: Result<Vec<ScalarValue>, DataFusionError> = scan
                        .default_values
                        .iter()
                        .map(|expr| {
                            let literal = self.create_expr(expr, Arc::clone(&required_schema))?;
                            let df_literal = literal
                                .as_any()
                                .downcast_ref::<DataFusionLiteral>()
                                .ok_or_else(|| {
                                GeneralError("Expected literal of default value.".to_string())
                            })?;
                            Ok(df_literal.value().clone())
                        })
                        .collect();
                    let default_values = default_values?;
```

Comment (mbutrovich) [reply native/core/src/execution/planner.rs]: Looks good, thank you for the suggestion!

**Comment by mbutrovich** [comment]
I accidentally pushed the int96 docs changes to the wrong branch :(

I'll just leave it here since CI is already running.

**Comment by mbutrovich** [comment]
Something else to look at for Spark 3.4...
```
select column with default value (native_comet, native shuffle) *** FAILED *** (449 milliseconds)
  org.apache.spark.sql.AnalysisException: Failed to execute ALTER TABLE ADD COLUMNS command because the destination table column col2 has a DEFAULT value with type ByteType, but the statement provided a value of incompatible type IntegerType
```

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @mbutrovich!

File: native/core/src/parquet/parquet_exec.rs [hunk 6]
```diff
@@ -61,12 +63,14 @@ pub(crate) fn init_datasource_exec(
...
+    default_values: Option<HashMap<usize, ScalarValue>>,
     session_timezone: &str,
 ) -> Result<Arc<DataSourceExec>, ExecutionError> {
     let (table_parquet_options, spark_parquet_options) = get_options(session_timezone);
-    let mut parquet_source = ParquetSource::new(table_parquet_options).with_schema_adapter_factory(
-        Arc::new(SparkSchemaAdapterFactory::new(spark_parquet_options)),
-    );
+    let mut parquet_source =
+        ParquetSource::new(table_parquet_options).with_schema_adapter_factory(Arc::new(
+            SparkSchemaAdapterFactory::new(spark_parquet_options, default_values),
```
[the remark this answers is not in the document]
Comment (parthchandra) [reply native/core/src/parquet/parquet_exec.rs:72]: I don't think it makes sense to do that even though it might make the code. a little bit simpler. `default_values` are not exactly options. But I'm not going to argue if you choose to do it that way.

File: native/core/src/parquet/mod.rs [hunk 7]
```diff
@@ -715,6 +715,7 @@ pub unsafe extern "system" fn Java_org_apache_comet_parquet_Native_initRecordBat
             file_groups,
             None,
             data_filters,
+            None,
```
[the remark this answers is not in the document]
Comment (parthchandra) [reply native/core/src/parquet/mod.rs:718]: It's handled in the `ConstantColumnReader` which is shared between native_comet and native_iceberg_compat.
Also see `ResolveDefaultColumns.getExistenceDefaultValues`. Not quite sure what the difference between ExistenceDefaultValues and simply default values is.

**Review by parthchandra — APPROVED** [review]
