### PR TITLE
fix: Support type coercion for ScalarUDFs

### LINKED ISSUE #841: `make_array` doesn't support mixed types with dictionaries
### Describe the bug

Discovered this working on new array functions. DataFusion's `make_array` doesn't play nice with underlying Dictionary types. Kinda yet another issue related to https://github.com/apache/datafusion/issues/11513 imo. 

### Steps to reproduce

Two separate cases that are easy to recreate with existing unit test setup:

```
checkSparkAnswerAndOperator(df.select(array(col("_13"), col("_13"))))
```
produces
```
  org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 11.0 failed 1 times, most recent failure: Lost task 0.0 in stage 11.0 (TID 11) (10.10.0.29 executor driver): org.apache.comet.CometNativeException: Invalid argument error: column types must match schema types, expected List(Field { name: "item", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }) but found List(Field { name: "item", data_type: Dictionary(Int32, Utf8), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }) at column index 0
```

Letting DataFusion infer the return type instead of specifying it results in
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 11.0 failed 1 times, most recent failure: Lost task 0.0 in stage 11.0 (TID 11) (10.10.0.29 executor driver): java.lang.NullPointerException: Cannot invoke "org.apache.comet.shaded.arrow.vector.dictionary.DictionaryProvider.lookup(long)" because "dictionaryProvider" is null
```
which seems like an internal Comet issue? Haven't dug into this but presumably is fixable.

And doing a mixed dictionary/non-dictonary like
```
checkSparkAnswerAndOperator(df.select(array(col("_8"), col("_13"))))
```
produces
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 8.0 failed 1 times, most recent failure: Lost task 0.0 in stage 8.0 (TID 8) (10.10.0.29 executor driver): org.apache.comet.CometNativeException: assertion `left == right` failed: Arrays with inconsistent types passed to MutableArrayData
  left: Utf8
 right: Dictionary(Int32, Utf8)
```
in datafusion/functions-nested/src/make_array.rs:231

### Expected behavior

Not sure what the expected behavior or fix is. Either implement this function from scratch with better dictionary handling, or add some wrapper around invoking the UDF to flatten dictionary encoded arrays

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Kimahriman**
## Which issue does this PR close?

Closes #841 

## Rationale for this change

`make_array` doesn't support mixed types of dictionaries and non-dictionaries. Type coercion is the fundamental piece that DataFusion uses at analysis time that is missing from Comet's use of ScalarUDFs.

## What changes are included in this PR?

In the planning for ScalarUDFs on the Rust side, check the function to see if the input types should be coerced to other types, and if so wrap the Expression in a cast to the appropriate type.

## How are these changes tested?

`CreateArray` unit test is updated with cases that were previously failing.

### CODE REVIEW

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 1]
```diff
@@ -2003,10 +2003,17 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
-        makeParquetFileAllTypes(path, dictionaryEnabled = dictionaryEnabled, 10000)
+        makeParquetFileAllTypes(path, dictionaryEnabled = dictionaryEnabled, 1000)
         val df = spark.read.parquet(path.toString)
         checkSparkAnswerAndOperator(df.select(array(col("_2"), col("_3"), col("_4"))))
         checkSparkAnswerAndOperator(df.select(array(col("_4"), col("_11"), lit(null))))
+        checkSparkAnswerAndOperator(
+          df.select(array(array(col("_4")), array(col("_4"), lit(null)))))
+        checkSparkAnswerAndOperator(df.select(array(col("_8"), col("_13"))))
+        // TODO: Some part of this converts the null to an empty string
+        // checkSparkAnswerAndOperator(df.select(array(col("_8"), col("_13"), lit(null))))
```
Comment (Kimahriman) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:2014]: This one is really odd and I haven't been able to figure it out. Somewhere along the way the `lit(null)` ends up becoming an empty string instead of null whenever it has to get cast to a dictionary array. I logged the full plan for this one
```
Projection: ProjectionExec { expr: [(ScalarFunctionExpr { fun: "<FUNC>", name: "make_array", args: [CastExpr { expr: Column { name: "col_0", index: 0 }, cast_type: Dictionary(Int32, Utf8), cast_options: CastOptions { safe: false, format_options: FormatOptions { safe: true, null: "", date_format: None, datetime_format: None, timestamp_format: None, timestamp_tz_format: None, time_format: None, duration_format: ISO8601 } } }, Column { name: "col_1", index: 1 }, CastExpr { expr: Literal { value: Utf8(NULL) }, cast_type: Dictionary(Int32, Utf8), cast_options: CastOptions { safe: false, format_options: FormatOptions { safe: true, null: "", date_format: None, datetime_format: None, timestamp_format: None, timestamp_tz_format: None, time_format: None, duration_format: ISO8601 } } }], return_type: List(Field { name: "item", data_type: Dictionary(Int32, Utf8), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }) }, "col_0")], schema: Schema { fields: [Field { name: "col_0", data_type: List(Field { name: "item", data_type: Dictionary(Int32, Utf8), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }, input: ScanExec { exec_context_id: 0, input_source: Some(GlobalRef { inner: GlobalRefGuard { obj: JObject { internal: 0x12010b128, lifetime: PhantomData<&()> }, vm: JavaVM(0x10b7aeb10) } }), input_source_description: "CometScan parquet  (unknown)", data_types: [Utf8, Utf8], batch: Mutex { data: Some(Batch([StringArray
[
  null,
  null,
  "222222222222222222222222222222222222222222222222",
  null,
  null,
  "111111111111111111111111111111111111111111111111",
  null,
  "333333333333333333333333333333333333333333333333",
  "000000000000000000000000000000000000000000000000",
  null,
  ...80 elements...,
  "222222222222222222222222222222222222222222222222",
  null,
  null,
  "111111111111111111111111111111111111111111111111",
  "222222222222222222222222222222222222222222222222",
  "333333333333333333333333333333333333333333333333",
  null,
  "111111111111111111111111111111111111111111111111",
  "222222222222222222222222222222222222222222222222",
  "333333333333333333333333333333333333333333333333",
], DictionaryArray {keys: PrimitiveArray<Int32>
[
  null,
  null,
  0,
  null,
  null,
  1,
  null,
  2,
  3,
  null,
  ...80 elements...,
  0,
  null,
  null,
  1,
  0,
  2,
  null,
  1,
  0,
  2,
] values: StringArray
[
  "2",
  "1",
  "3",
  "0",
]}
], 100)), poisoned: false, .. }, cache: PlanProperties { eq_properties: EquivalenceProperties { eq_group: EquivalenceGroup { classes: [] }, oeq_class: OrderingEquivalenceClass { orderings: [] }, constants: [], schema: Schema { fields: [Field { name: "col_0", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "col_1", data_type: Dictionary(Int32, Utf8), nullable: true, dict_id: 1, dict_is_ordered: false, metadata: {} }], metadata: {} } }, partitioning: UnknownPartitioning(1), execution_mode: Bounded, output_ordering: None }, metrics: ExecutionPlanMetricsSet { inner: Mutex { data: MetricsSet { metrics: [] } } } }, metrics: ExecutionPlanMetricsSet { inner: Mutex { data: MetricsSet { metrics: [] } } }, cache: PlanProperties { eq_properties: EquivalenceProperties { eq_group: EquivalenceGroup { classes: [] }, oeq_class: OrderingEquivalenceClass { orderings: [] }, constants: [], schema: Schema { fields: [Field { name: "col_0", data_type: List(Field { name: "item", data_type: Dictionary(Int32, Utf8), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} } }, partitioning: UnknownPartitioning(1), execution_mode: Bounded, output_ordering: None } }
```

Comment (Kimahriman) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:2014]: I was able to recreate with a test on v41.0.0, but it seems to be fixed on master

Comment (Kimahriman) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:2014]: Found it: https://github.com/apache/datafusion/commit/27304239ef79b50a443320791755bf74eed4a85d

**Comment by andygrove** [comment]
Thanks @Kimahriman. I think this looks good but want to do some testing before approving.

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 2]
```diff
@@ -2002,10 +2002,21 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
     Seq(true, false).foreach { dictionaryEnabled =>
       withTempDir { dir =>
         val path = new Path(dir.toURI.toString, "test.parquet")
-        makeParquetFileAllTypes(path, dictionaryEnabled = dictionaryEnabled, 10000)
+        makeParquetFileAllTypes(path, dictionaryEnabled = dictionaryEnabled, 1000)
```
Comment (andygrove) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:2005]: What is the reason for the change from `10000` to `1000`?

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @Kimahriman

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala (hunk 2 above)
Comment (Kimahriman) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:2005]: I had to scroll up really far while debugging the empty string vs null issue which dumped all 10k records to the terminal 😂 happy to change it back, not sure how much it matters to do 10k rows or not.
