### PR TITLE
fix: Fallback to Spark for LIKE with custom escape character

### LINKED ISSUE #462: bug: LIKE with custom escape char produces incorrect results
### Describe the bug

Repro test case for `CometExpressionSuite`:

```scala
  test("like with custom escape") {
    val names = Seq("", "a_b", "d_e_f")
    withTempDir { dir =>
      val filename = "/tmp/percent.parquet"
      names.toDF("a").write.mode(SaveMode.Overwrite).parquet(filename)
      spark.read.parquet(filename).coalesce(1).createOrReplaceTempView("t")
      val query = sql("select a from t where a like '%$_%' escape '$'")
      checkSparkAnswerAndOperator(query)
    }
  }
```

Output:

```
== Results ==
!== Correct Answer - 2 ==   == Spark Answer - 0 ==
!struct<a:string>           struct<>
![a_b]                      
![d_e_f]   
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sujithjay**
Fallback to Spark for LIKE with custom escape character because currently, LIKE with custom escape character produces incorrect results.

## Which issue does this PR close?

Closes #462 

## What changes are included in this PR?
An `if` clause is introduced for LIKE in `exprToProtoInternal` in `QueryPlanSerde.scala`. It ensures that we fallback to Spark in case LIKE has a custom escape character.

## How are these changes tested?
A test was added to `org.apache.comet.CometExpressionSuite`.

### CODE REVIEW

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 1]
```diff
@@ -981,7 +981,7 @@ object QueryPlanSerde extends Logging with ShimQueryPlanSerde {
             None
           }
 
-        case Like(left, right, _) =>
+        case Like(left, right, escapeChar) if escapeChar == '\\' =>
```
Comment (andygrove) [inline spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:984]: I tihnk it would be better to have a check for escape char within the match and then call `withInfo` if the escape char is not `\\` so that we can give the user a specific error such as `escape char not supported` otherwise I think we fall through to the catchall logic and the user will get an error `like is not supported`, which could be confusing

Comment (sujithjay) [reply spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala]: @andygrove I have made this change in https://github.com/apache/datafusion-comet/pull/478/commits/bfac08a2e8029464c1d7ec44bb46d9d33384a1ef. Please review.

**Review by andygrove — APPROVED** [review]
LGTM. Thank you @sujithjay

**Review by viirya — APPROVED** [review]

File: spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala [hunk 2]
```diff
@@ -578,6 +578,24 @@ class CometExpressionSuite extends CometTestBase with AdaptiveSparkPlanHelper {
...
+    val table = "names"
+    withTable(table) {
+      sql(s"create table $table(id int, name varchar(20)) using parquet")
+      sql(s"insert into $table values(1,'James Smith')")
+      sql(s"insert into $table values(2,'Michael_Rose')")
+      sql(s"insert into $table values(3,'Robert_R_Williams')")
+
+      // Filter column having values that include underscores
+      val queryDefaultEscape = sql("select id from names where name like '%\\_%'")
+      checkAnswer(queryDefaultEscape, Row(2) :: Row(3) :: Nil)
```
Comment (kazuyukitanimura) [inline spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:591]: Strictly speaking, `checkSparkAnswerAndOperator()` to be used to make sure native comet is actually executed?

Comment (andygrove) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala:591]: Good point. @sujithjay could you make that change?

Comment (sujithjay) [reply spark/src/test/scala/org/apache/comet/CometExpressionSuite.scala]: Done in https://github.com/apache/datafusion-comet/pull/478/commits/496e885da9c938519822bf021505e7fcf90395b5. Please review @kazuyukitanimura @andygrove.

**Review by kazuyukitanimura — APPROVED** [review]
LGTM Pending CI
