### PR TITLE
fix: Improve support for nested structs

### LINKED ISSUE #799: Supported for nested structs
### Describe the bug

In #731 support for structs was added but only for top level ones and not nested. To me this looks like this was mostly missed in the PR and not intentiaonl.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by eejbyfeldt**
## Which issue does this PR close?

Closes #799.

## Rationale for this change

Looks like this was mostly missed in the implemenation of #731 which extended support for structs.

## What changes are included in this PR?

The parameter `allowStruct` in `supportedDataType` is forwarded to recursive calls.

## How are these changes tested?

New test case.

### CODE REVIEW

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 1]
```diff
@@ -65,7 +65,8 @@ object QueryPlanSerde extends Logging with ShimQueryPlanSerde with CometExprShim
         _: DateType | _: BooleanType | _: NullType =>
       true
     case dt if isTimestampNTZType(dt) => true
-    case s: StructType if allowStruct => s.fields.map(_.dataType).forall(supportedDataType(_))
+    case s: StructType if allowStruct =>
+      s.fields.map(_.dataType).forall(supportedDataType(_, allowStruct))
```
Comment (Kimahriman) [inline spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:69]: Good catch, I initially had `allowStruct` default to true which is why I didn't pass it on here, but missed this when I changed the default

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @eejbyfeldt and @Kimahriman
