### PR TITLE
feat: enable debug assertions in CI profile, fix unaligned memory access bug

### LINKED ISSUE #3653: Spark SQL test failure when debug assertions are enabled
### Describe the bug

```
Comet native panic: panicked at core/src/execution/shuffle/spark_unsafe/row.rs:293:29:
misaligned pointer dereference: address must be a multiple of 0x8 but is 0xc1a80000c
```

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andygrove**
Closes https://github.com/apache/datafusion-comet/issues/3653

## Summary
- Enable `debug-assertions = true` in the CI cargo profile to catch potential issues with unsafe code at test time
- Enable `RUST_BACKTRACE=1` in all CI workflows to get full stack traces when panics occur

## Rationale
We want to verify whether any debug assertions fire on the main branch, particularly in the columnar-to-row and other unsafe code paths.

### CODE REVIEW

**Comment by andygrove** [comment]
```
Comet native panic: panicked at core/src/execution/shuffle/spark_unsafe/row.rs:293:29:
misaligned pointer dereference: address must be a multiple of 0x8 but is 0xc1a80000c
```

**Comment by andygrove** [comment]
@mbutrovich I think this explains the bus error you saw recently

File: native/core/src/execution/jni_api.rs [hunk 1]
```diff
@@ -570,10 +571,29 @@ pub unsafe extern "system" fn Java_org_apache_comet_Native_executePlan(
                     let (tx, rx) = mpsc::channel(2);
                     let mut stream = stream;
                     get_runtime().spawn(async move {
-                        while let Some(batch) = stream.next().await {
-                            if tx.send(batch).await.is_err() {
-                                break;
+                        let result = std::panic::AssertUnwindSafe(async {
```
Comment (andygrove) [inline native/core/src/execution/jni_api.rs:574]: These changes are for catching panics that happen in tokio threads

File: native/core/src/errors.rs [hunk 2]
```diff
@@ -145,7 +145,10 @@ pub enum CometError {
 }
 
 pub fn init() {
-    std::panic::set_hook(Box::new(|_panic_info| {
+    std::panic::set_hook(Box::new(|panic_info| {
+        // Log the panic message and location to stderr so it is visible in CI logs
+        // even if the exception message is lost crossing the FFI boundary
+        eprintln!("Comet native panic: {panic_info}");
```
Comment (andygrove) [inline native/core/src/errors.rs:151]: This is the main change for improving reporting of panics

**Review by parthchandra — APPROVED** [review]
Let's get this in. It's important to catch these issues early.

**Comment by andygrove** [comment]
Thanks @parthchandra
