### PR TITLE
fix: Unsupported types for SinglePartition should fallback to Spark

### LINKED ISSUE #766: Unsupported types for SinglePartition should fallback to Spark
### Describe the bug

This is a regression brought by #760.

For supported partitioning like SinglePartition, we still need to check input data types.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #766.

### CODE REVIEW

File: spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala [hunk 1]
```diff
@@ -2931,8 +2931,8 @@ object QueryPlanSerde extends Logging with ShimQueryPlanSerde with CometExprShim
           msg = s"unsupported Spark partitioning expressions: $expressions"
         }
         supported
-      case SinglePartition => true
-      case RoundRobinPartitioning(_) => true
+      case SinglePartition => inputs.forall(attr => supportedDataType(attr.dataType))
+      case RoundRobinPartitioning(_) => inputs.forall(attr => supportedDataType(attr.dataType))
```
Comment (viirya) [inline spark/src/main/scala/org/apache/comet/serde/QueryPlanSerde.scala:2935]: I brought this regression in #760. We still need to check input data types for SinglePartition, etc.

**Review by huaxingao — APPROVED** [review]
LGTM

**Comment by viirya** [comment]
Thanks @huaxingao
